### ISSUE TITLE
Not Posible Change Colors

### ISSUE THREAD

**Issue by tjaoc** [uilibrary/Stocky-Issues-and-Feature-request#1]
Not Posible Change Colors

**Comment by naime-hossain** [comment]
> Not Posible Change Colors

which colors do you want to change?

**Comment by tjaoc** [comment]
The violet for others, choice for me, for my logo etc

**Comment by naime-hossain** [comment]
You need to customize the scss theme file  `stocky/resources/src/assets/styles/sass/themes/`. thank you

**Comment by tjaoc** [comment]
The App have potencial, but with these responses for you not sell much more.

**Comment by naime-hossain** [comment]
> The App have potencial, but with these responses for you not sell much more.

can you explain in detail, what responses? we are fixing all your issues here :) , do you want to change colors from settings/customization bar ? I think other code canyon items don't have options like in our app. thank you

**Comment by naime-hossain** [comment]
And also if we don't get enough sales it's not possible to continue development because we already spent lots of time on this. Thank you for your support

**Comment by tjaoc** [comment]
I have already reported too many bugs and improvements that dozens of apps of this style have in codecanyon. You are the developers, look for you from now on.

**Comment by naime-hossain** [comment]
We are working on your issues. thank you
