### ISSUE TITLE
Is there any chance to get only Native laravel code.

### ISSUE THREAD

**Issue by dhavalpatel2374** [uilibrary/Stocky-Issues-and-Feature-request#100]
hello. is there any chance to get product in only laravel. Our team dont have knowlage of Vue so they are asking for only laravel code. so is thre any chance to get only laravel version product?

**Comment by hamzakifani** [comment]
Stocky is based in laravel api & vue js . but we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
