### ISSUE TITLE
scan the barcode via mobile/scanner

### ISSUE THREAD

**Issue by ousmansiop** [uilibrary/Stocky-Issues-and-Feature-request#101]
we are really interested in having in the software the scan by the barcode via mobile / scanner

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by airwavesmi** [comment]
This is a must for most of the pos system! Do add it!! Thank you!

**Comment by hamzakifani** [comment]
we will add it . Thank you!

**Comment by hamzakifani** [comment]
Barcode scanner added . Please use the latest version 3.0
Thank you
