### ISSUE TITLE
Create Adjustment - Cannot Search Product

### ISSUE THREAD

**Issue by cheramor** [uilibrary/Stocky-Issues-and-Feature-request#102]
Hi

I'm creating Adjustment Record, but the search product is not working. I already updated to the latest version, v2.3.0

Thanks

**Comment by naime-hossain** [comment]
Search product in which page not working? screenshot?
Thank you

**Comment by cheramor** [comment]
![image](https://user-images.githubusercontent.com/364125/118941068-ef34c780-b983-11eb-88f5-d56abf1d50a1.png)

**Comment by cheramor** [comment]
![image](https://user-images.githubusercontent.com/364125/118941701-931e7300-b984-11eb-9cae-6edeffda7046.png)

**Comment by hamzakifani** [comment]
Hi. To add adjustment you have to purchase the product first. Because the adjustments comes when you have stock. Thank you.
Please you need create purchase via http://stocky.ui-lib.com/app/purchases/store

**Comment by cheramor** [comment]
Thanks. I thought that the adjustment would be for the beginning inventory of the product. For example, I already purchased a product from long time ago and I would like to set the quantity of the said product as of today.

Anyway, maybe I would make a one time purchase of all the items on hand.

Thank you.

**Comment by hamzakifani** [comment]
Great , if you need any further help, let us know :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
I am closing the issue if you need any further help, let us know :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
