### ISSUE TITLE
I don't want it to be mandatory

### ISSUE THREAD

**Issue by yavuzdemir3452** [uilibrary/Stocky-Issues-and-Feature-request#104]
Hello, I do not want the form to be mandatory when adding a customer. How do I remove the requirement?

**Comment by hamzakifani** [comment]
All fields is required . Thank you

**Comment by yavuzdemir3452** [comment]
But I do not want mandatory I want to remove the obligation, it is not mandatory

**Comment by hamzakifani** [comment]
You have a option to make walk in customer in pos . thank you

**Comment by eduardn1** [comment]
> You have a option to make walk in customer in pos . thank you

hei where's that option ? i'm checking your demo and can't seem to find it 

i want to use the pos only for walking customers and not select everytime client

**Comment by yavuzdemir3452** [comment]
Name mail phone is mandatory, I do not want the others to be mandatory. What should I do for this?

**Comment by yavuzdemir3452** [comment]
> Pozisyonda müşteriyi gezme seçeneğiniz var. teşekkür ederim

I want the customer country, address, city not mandatory when registering

**Comment by naime-hossain** [comment]
> Name mail phone is mandatory, I do not want the others to be mandatory. What should I do for this?

Simple, you have to edit the code and for this, you need to be familiar with Laravel+vue . or you can hire someone to do this 
 thank you

**Comment by hamzakifani** [comment]
> > You have a option to make walk in customer in pos . thank you
> 
> hei where's that option ? i'm checking your demo and can't seem to find it
> 
> i want to use the pos only for walking customers and not select everytime client

walk in customer is now available in latest version 2.3.0
