### ISSUE TITLE
printer setting

### ISSUE THREAD

**Issue by yavuzdemir3452** [uilibrary/Stocky-Issues-and-Feature-request#106]
Hello, when I want to print out, there are gaps on the right, left, up and down.

The receipt is in the middle, how can I get it to the left?

it didn't happen when i set it from the printer

https://www.hizliresim.com/47jqu7c

**Comment by yavuzdemir3452** [comment]
?

**Comment by hamzakifani** [comment]
We will check this issue . thank you

**Comment by yavuzdemir3452** [comment]
it doesn't matter if you check it. I want to use it anymore? date not attached printer output problematic? I solved the compulsory fields, but what is the point of not using emergency aid in my workplace, am I always waiting for you?

**Comment by yavuzdemir3452** [comment]
![image](https://user-images.githubusercontent.com/84523818/119679355-f575e880-be48-11eb-9a64-cbe22e5cd54e.png)

**Comment by yavuzdemir3452** [comment]
I have bought a lot of codecanyon and themeforest software and sites before and their support was great, but you really have a problem with voice, where I could not, the friends in the support edited themselves by requesting the information each time and I extended their support, but you do not help at all. I said what's the point, I want to remove the mandatory fields, you didn't help at all, while other companies said let's share the information, you said privatize.

I made customization, now you say update, what has been done in the update will be lost, you will not support it again.

**Comment by naime-hossain** [comment]
Please make a backup and then follow the upgrade guide, in case you lost modification then you can pug these again. thank you

**Comment by hamzakifani** [comment]
> Hello, when I want to print out, there are gaps on the right, left, up and down.
> 
> The receipt is in the middle, how can I get it to the left?
> 
> it didn't happen when i set it from the printer
> 
> https://www.hizliresim.com/47jqu7c

Hi , Please check docs  : http://test.local/documentation/index.html we added Guide to Setting Up Receipt Printer to work with POS Small Receipts . Thank you

**Comment by yavuzdemir3452** [comment]
Hello
printer settings are already standard size in all of them, they come automatically, because that's the paper size.

But since the output in your system is in A4 size, it looks like the image I sent you.

How can I set the output settings to the left? I want it or you can send it, let's upload it. It's been a long time since it was active on the system. Please don't get carried away, we want a solution. Many people have the same problem.

Thanks

![image](https://user-images.githubusercontent.com/84523818/120280564-81ac6380-c2c0-11eb-8958-2a719ad7f7a6.png)

**Comment by hamzakifani** [comment]
Please give us some time we will fix this issue. thank you

**Comment by yavuzdemir3452** [comment]
Ok, we are waiting to hear from you. Please solve the problem, where you need to add the files, we will add them and share the file download link with us.

**Comment by hamzakifani** [comment]
> Ok, we are waiting to hear from you. Please solve the problem, where you need to add the files, we will add them and share the file download link with us.

thanks for your understanding .  we will fix this issue don't worry.  thank you

**Comment by yavuzdemir3452** [comment]
thanks for the help

I'm adding, I'm saving, because I don't understand the code, there is no setting?

Can you run it and send it to me, I will download the file and post it?

actually did you write this wrong: /resources/src/assets/styles/sass/globals/views/_pos.scss


thanks

**Comment by hamzakifani** [comment]
please wait in tonight we will add new version 2.4.0 then you can upgrade to new version. thank you

**Comment by yavuzdemir3452** [comment]
thanks

**Comment by hamzakifani** [comment]
I can send you the file but if you have already made changes to the code it will be deleted .

**Comment by hamzakifani** [comment]
if you upgrade to the new version all your customization it well be deleted .

**Comment by yavuzdemir3452** [comment]
yes i have customization done please send it to me thank you

**Comment by hamzakifani** [comment]
send us these customizations to compile it here and we will send you the file compiled .

**Comment by yavuzdemir3452** [comment]
Removing the required fields when adding the customer to the customization area, but I don't know these files, the friend who made them knows, I can't reach him either

you just send me the pos output size, printer setting and if you have added the receipt date files, I will add them where I need to add them.

**Comment by yavuzdemir3452** [comment]
or send me your email

i send you cpanel ?

**Comment by yavuzdemir3452** [comment]
as customization

- We made the name of the add customer form mandatory

other input fields are not required

we did this

**Comment by yavuzdemir3452** [comment]
![image](https://user-images.githubusercontent.com/84523818/120490275-f1097c80-c3c0-11eb-96e5-5e5e163a36ee.png)

**Comment by hamzakifani** [comment]
> or send me your email
> 
> i send you cpanel ?

Please contact via : uilib.help@gmail.com with your cpanel access

**Comment by yavuzdemir3452** [comment]
Hello, I have sent you the information, were you able to check it?

**Comment by yavuzdemir3452** [comment]
![image](https://user-images.githubusercontent.com/84523818/120649972-01cff600-c486-11eb-8a63-f53b54d0c8ad.png)

Thank you for a great job updating it.

This is terrible, there are no gaps in the margin, it will be enough to do it on the left, but whatever

**Comment by hamzakifani** [comment]
> Thank you for a great job updating it.
> 
> This is terrible, there are no gaps in the margin, it will be enough to do it on the left, but whatever

we have not updated demo .

**Comment by hamzakifani** [comment]
![pos printer](https://user-images.githubusercontent.com/50219942/120677241-c71e8b80-c48e-11eb-8ae1-eabba13b16e4.PNG)


we have updated the demo. check now .

**Comment by yavuzdemir3452** [comment]
great now thanks
good luck to your hands
sorry

**Comment by hamzakifani** [comment]
> great now thanks
> good luck to your hands
> sorry

We have added auto select for walk in customer . Thank you

**Comment by yavuzdemir3452** [comment]
For example, you can develop it in this direction

for a newly added customer, it will be automatically added to that customer

Do not have to choose again after adding

just a suggestion :)

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by yavuzdemir3452** [comment]
![b337b1d1-86f4-49e0-9a46-4fd01a4c7a34](https://user-images.githubusercontent.com/84523818/120799222-217b2300-c547-11eb-922f-4f65fc75b22e.jpg)


![4496dad3-efec-420e-9ecf-0a58270811c3](https://user-images.githubusercontent.com/84523818/120799248-2a6bf480-c547-11eb-9820-de9b01c9fb78.jpg)

It outputs like this, it was better on the other system, why?

thanks

**Comment by hamzakifani** [comment]
We will check . and let you know . Thank you

**Comment by hamzakifani** [comment]
we fixed this problem 
Please test print receipt on this demo . 
http://demo.gesttio.com/login

and let us know if all is well . thank you

![receipt](https://user-images.githubusercontent.com/50219942/120842096-2c907c00-c564-11eb-94d9-815b21503ae2.PNG)

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
????

**Comment by hamzakifani** [comment]
we fixed this problem
Please test print receipt on this demo .
http://demo.gesttio.com/login

and let us know if all is well . thank you


![120842096-2c907c00-c564-11eb-94d9-815b21503ae2](https://user-images.githubusercontent.com/50219942/120907087-ac970e80-c656-11eb-86a7-8fe487332a47.png)

**Comment by yavuzdemir3452** [comment]
![image](https://user-images.githubusercontent.com/84523818/120991596-75297e80-c78a-11eb-8da0-0983b24f1656.png)
Hello
it looks cut again if you can take it in a little more

Also, can you make the text very small and big and thicken it?

**Comment by hamzakifani** [comment]
please add me on skype to fix this problem . Thank you

![Screenshot_2021-06-07-13-09-33-104_com skype raider](https://user-images.githubusercontent.com/50219942/121014263-b1141200-c791-11eb-8106-d445986adcc9.jpg)

**Comment by hamzakifani** [comment]
Please test now  .
http://demo.gesttio.com/login

and let us know if all is well . thank you

**Comment by yavuzdemir3452** [comment]
you are great it is very good

 can you do the font size?   font-size: 16px;

![resim](https://user-images.githubusercontent.com/84523818/121209279-65419580-c883-11eb-91ef-b375401b8ddb.jpg)

picture 1. we can delete (It doesn't need to be written on the receipt.)
picture 2.  instead of - Can we write what is written below?

Mali Değeri Yoktur.
Fişinizi Almayı Unutmayınız


If you send me the files, I can upload or I will email you the information ?

thanks for your help you are great

**Comment by hamzakifani** [comment]
Send us your cpanel access . Thank you

**Comment by yavuzdemir3452** [comment]
uilib.help@gmail.com i posted it here

http://akar.webzirve.com/

thank you

**Comment by hamzakifani** [comment]
we will check . thank you

**Comment by naime-hossain** [comment]
> you are great it is very good
> 
> can you do the font size? font-size: 16px;
> 
> ![resim](https://user-images.githubusercontent.com/84523818/121209279-65419580-c883-11eb-91ef-b375401b8ddb.jpg)
> 
> picture 1. we can delete (It doesn't need to be written on the receipt.)
> picture 2. instead of - Can we write what is written below?
> 
> Mali Değeri Yoktur.
> Fişinizi Almayı Unutmayınız
> 
> If you send me the files, I can upload or I will email you the information?
> 
> thanks for your help you are great

Custom work is not included, we will let you know . 

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
