### ISSUE TITLE
Scan Barcode using mobile camera

### ISSUE THREAD

**Issue by Stridesdata** [uilibrary/Stocky-Issues-and-Feature-request#11]
Vendors balance and payment..
Customer balances
Scan using mobile camera

**Comment by naime-hossain** [comment]
> Vendors balance and payment..
> Customer balances
> Scan using mobile camera

Please Give a proper Description of each future so that we can implement it in the future. thank you

**Comment by Stridesdata** [comment]
Thank you for your email.

I checked the vendor and customer list and I could not find the amount due

Also I need to use my mobile phone to scan bar codes while entering Items.

Thank you.




Lead Strategist,
strides data Consulting

**Comment by hamzakifani** [comment]
to see all reports customer or vendor got to
http://stocky.ui-lib.com/app/reports/customers_report

**Comment by Stridesdata** [comment]
Thanks..

Can I use Mobile phone camera as scanner...?




Lead Strategist,
strides data Consulting

**Comment by hamzakifani** [comment]
Please wait in the next version this week . Thank you

**Comment by hamzakifani** [comment]
Barcode scanner added . Please use the latest version 3.0
Thank you

**Comment by Stridesdata** [comment]
Great...I can't find it in the demo




Lead Strategist,
strides data Consulting

**Comment by Stridesdata** [comment]
Does it what like my crude implementation?

See attachment

https://user-images.githubusercontent.com/82326559/123376132-dff7f980-d581-11eb-9dcc-44c1c8c29b20.mp4

**Comment by hamzakifani** [comment]
> Great...I can't find it in the demo

we will update it soon . thank you

**Comment by naime-hossain** [comment]
Demo Updated :) if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by ernsk** [comment]
Hello, i don't see any scan option for mobile phone camera in your demo. Could you please help me with that? @hamzakifani 
,@naime-hossain. Do you have any feature like @Stridesdata video post?
