### ISSUE TITLE
How to update/build vue.js code in cPanel?

### ISSUE THREAD

**Issue by takrimabdullah** [uilibrary/Stocky-Issues-and-Feature-request#110]
- How to run `npm run prod` in cPanel?

**Comment by hamzakifani** [comment]
yes you can with SSH ACCESS

**Comment by takrimabdullah** [comment]
Do I have to install Node JS for the same directory?

**Comment by naime-hossain** [comment]
Please search on google or youtube, How to run npm command in Cpanel. If you won't find any solution then let us know.  Thank you
