### ISSUE TITLE
Duplicated product in the system

### ISSUE THREAD

**Issue by teehanming** [uilibrary/Stocky-Issues-and-Feature-request#112]
Duplicated product in the system but not listed in the Product List.
![image](https://user-images.githubusercontent.com/65308523/119637252-0d00a180-be48-11eb-9ab2-bb904c594237.png)
![image](https://user-images.githubusercontent.com/65308523/119637365-2bff3380-be48-11eb-8ab2-8e2b3abb69f2.png)

**Comment by teehanming** [comment]
The product list looks just fine
![image](https://user-images.githubusercontent.com/65308523/119637579-62d54980-be48-11eb-87bf-99879b6f45fc.png)

**Comment by hamzakifani** [comment]
we will check this issue . thank you

**Comment by hamzakifani** [comment]
bug fixed in version 2.4.0 . Thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
