### ISSUE TITLE
Error on Installation in Localhost (XAMPP)

### ISSUE THREAD

**Issue by ibrafayez** [uilibrary/Stocky-Issues-and-Feature-request#113]
I followed the steps in the [documentation](https://stocky.ui-lib.com/documentation/index.html) for Installation in Localhost

I got this error:
<img width="917" alt="Screen Shot 2021-05-26 at 6 49 00 PM" src="https://user-images.githubusercontent.com/44995398/119709712-2e708600-be66-11eb-8b18-a905a8c711ef.png">

Could you please help me,
Thank you

**Comment by hamzakifani** [comment]
Please go to  :  C:\xampp\apache\conf\extra\httpd-vhosts.conf

**_and then change_**

```
 <VirtualHost stocky.local>
                     ServerAdmin stocky.local
                     DocumentRoot "C:/xampp/htdocs/stocky"
                     ServerName stocky.local
                     ErrorLog "logs/stocky.local.log"
                     CustomLog "logs/stocky.local.log" common
  </VirtualHost>
```

**_To_**

```
<VirtualHost stocky.local:80>
    ServerAdmin webmaster@stocky.local
    DocumentRoot "C:/xampp/htdocs/stocky"
    ServerName www.stocky.local
    ServerAlias stocky.local

     <Directory "C:/xampp/htdocs/stocky">
            Options Indexes FollowSymLinks Includes ExecCGI
            AllowOverride All
            Require all granted
        </Directory>

    ErrorLog "logs/stocky.local-error.log"
    CustomLog "logs/stocky.local-access.log" common
</VirtualHost>
```

Restart the Xampp. That's it!

**Comment by ibrafayez** [comment]
Still I got the same error 
<img width="1322" alt="Screen Shot 2021-05-26 at 11 14 24 PM" src="https://user-images.githubusercontent.com/44995398/119725152-45b86f00-be78-11eb-9ddf-bb28a7198b8e.png">



I'm using Mac btw

**Comment by hamzakifani** [comment]
Please read this 
https://dev.to/josiemhardy/how-to-fix-error-403-forbidden-access-new-xampp-security-concept-on-macbook-n2k

**Comment by ibrafayez** [comment]
I followed the instructions, the page wouldn't load it's stuck on loading

<img width="1392" alt="Screen Shot 2021-05-30 at 4 09 30 PM" src="https://user-images.githubusercontent.com/44995398/120106036-21081400-c164-11eb-8c04-6b0df1d84232.png">

**Comment by ibrafayez** [comment]
What did I do:

I changed httpd-vhosts.conf to :
```
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/opt/lampp/docs/dummy-host.example.com"
    ServerName dummy-host.example.com
    ServerAlias www.dummy-host.example.com
    ErrorLog "logs/dummy-host.example.com-error_log"
    CustomLog "logs/dummy-host.example.com-access_log" common
</VirtualHost>

<VirtualHost stocky.local:80>
    ServerAdmin webmaster@stocky.local
    DocumentRoot "/opt/lampp/htdocs/stocky"
    ServerName www.stocky.local
    ServerAlias stocky.local

     <Directory "/opt/lampp/htdocs/stocky">
            Options Indexes FollowSymLinks Includes ExecCGI
            AllowOverride All
            Require all granted
        </Directory>

    ErrorLog "logs/stocky.local-error.log"
    CustomLog "logs/stocky.local-access.log" common
</VirtualHost>
```

Added 127.0.0.1 stocky.local to hosts:
<img width="481" alt="Screen Shot 2021-05-30 at 7 00 33 PM" src="https://user-images.githubusercontent.com/44995398/120111198-b06bf200-c179-11eb-900a-9906ef6cdc53.png">

I followed all the required steps still doesn't work...

**Comment by hamzakifani** [comment]
Please replace
127.0.0.1 localhost 
With 
#127.0.0.1 localhost

**Comment by ibrafayez** [comment]
I tried commenting the localhost, still the same issue.

**Comment by hamzakifani** [comment]
you need to configure XAMPP Virtual Host to set the document root to correct directory of Stocky  project and to also assign a name to the Stocky by which we will be accessing it in browser.

Navigate and open file /Applications/XAMPP/etc/httpd.conf file and uncomment the line that includes the virtual host file.

Navigate and open file /Applications/XAMPP/etc/extra/httpd-vhosts.conf and include following Virtual host entry in this file.

```
<VirtualHost stocky.local:80>
  DocumentRoot "C:\xampp\htdocs\stocky"
  ServerAdmin laravel.local
  <Directory "C:\xampp\htdocs\stocky">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
  </Directory>
</VirtualHost>
```

With this entry your apache is listening to stocky.local, but you also have to edit your hosts file to include an entry for the new domain.

Edit file /etc/hosts and add following entry to that file.

127.0.0.1 stocky.local

Restart your apache and access stocky.local on your browser .

**Comment by ibrafayez** [comment]
I went through all the steps, now when I access stocky.local it shows me "Error 403 Access Forbidden!"

I tried googling the problem I couldn't find anything useful. Can I put on an AWS server? if yes can you please show me the needed steps... because I'm not really familiar with Laravel, and AWS I'm just a beginner.

**Comment by hamzakifani** [comment]
> I went through all the steps, now when I access stocky.local it shows me "Error 403 Access Forbidden!"
> 
> I tried googling the problem I couldn't find anything useful. Can I put on an AWS server? if yes can you please show me the needed steps... because I'm not really familiar with Laravel, and AWS I'm just a beginner.

You can upload it to the server (cpanel) it's a better way .

**Comment by ibrafayez** [comment]
I tired to upload it to my Bluehost server it didn't work, I contacted support they told me I need VPC do I really need that?

**Comment by hamzakifani** [comment]
> I tired to upload it to my Bluehost server it didn't work, I contacted support they told me I need VPC do I really need that?

Please contact via : uilib.help@gmail.com with your cpanel access
I well fix this problem

**Comment by ibrafayez** [comment]
I made it work through Digital Ocean server, one comment though you should mention I have to install Laravel in the documentation since it can't work without it.

Thank you
