### ISSUE TITLE
Deleted Sales - Stock quantity Issue

### ISSUE THREAD

**Issue by teehanming** [uilibrary/Stocky-Issues-and-Feature-request#115]
When deleting sales, the stock unit willl be gone and not return to the amount before in Product. 
How can I restore this? because I cant manually edit the quantity.

**Comment by naime-hossain** [comment]
use adjustment ->https://stocky.ui-lib.com/app/adjustments/store
Thank you

**Comment by teehanming** [comment]
oh just found it, but the product is missing in other section, it only  exist in product list

**Comment by teehanming** [comment]
the product did not appear when I search in the "product search"

**Comment by naime-hossain** [comment]
Please give us clear details about your issue. if possible with video. thank you

**Comment by teehanming** [comment]
Example: Product sakura exist in product list
![image](https://user-images.githubusercontent.com/65308523/119829754-2714af80-bf2e-11eb-9771-240f23cda225.png)

Sakura did not exist in adjustment
![image](https://user-images.githubusercontent.com/65308523/119829898-4f041300-bf2e-11eb-81fc-a266e96619d1.png)

sales too
![image](https://user-images.githubusercontent.com/65308523/119829983-64793d00-bf2e-11eb-9285-a2578faa4f41.png)

but it appear in purchases
![image](https://user-images.githubusercontent.com/65308523/119830079-7bb82a80-bf2e-11eb-99b5-3664d9e33f52.png)

**Comment by teehanming** [comment]
1. have purchase and have stock
2. create sales, but then deleted it
3. now it 0 stock and can't be modified

**Comment by hamzakifani** [comment]
When stock 0 Purchase product again
