### ISSUE TITLE
Problem with the language

### ISSUE THREAD

**Issue by c300** [uilibrary/Stocky-Issues-and-Feature-request#116]
Hello,
I edited en.js to adapt to my language and executed 
run : npm install
run : npm run watch
run : npm run prod
then reuploaded in the server all files, but yet the language is not updated.

Can you help me ?

**Comment by hamzakifani** [comment]
Please upload also public/js . Thank you

**Comment by c300** [comment]
I have uploaded the entire public folder after i run : 
 npm install
 npm run watch
 npm run prod

still the same.

**Comment by hamzakifani** [comment]
> I have uploaded the entire public folder after i run :
> npm install
> npm run watch
> npm run prod
> 
> still the same.

Upload it after running cmd .

**Comment by c300** [comment]
after i run all commands,i uploaded them

**Comment by hamzakifani** [comment]
If you don't fix it . Please contact via : uilib.help@gmail.com with your cpanel access

**Comment by hamzakifani** [comment]
your issue is fixed please check now  . thank you

**Comment by c300** [comment]
Can u tell me what was wrong because i have to do it many times alter for
some edits and i dont want to bother.

**Comment by hamzakifani** [comment]
you must refresh folder /js in public so if you want edit tranlsation . 
clone stocky in localhost 
1) Go to /resources/src/translations/locales/

2) run : npm install
3) run : npm run watch
4) run : npm run prod

5) upload your file translation en.js edited and folder /js in server  .
