### ISSUE TITLE
POS receipt printing issue 

### ISSUE THREAD

**Issue by lifetill** [uilibrary/Stocky-Issues-and-Feature-request#117]
Can't print receipt with 55mm pos printer.
Paper size need to be fixed. It prints a long black paper.

**Comment by hamzakifani** [comment]
we will check this issue . thank you

**Comment by lifetill** [comment]
**I am very disappointed to see your way of acting.** You don't give any solution in support and just say that we will look into the matter.

**Comment by hamzakifani** [comment]
> Can't print receipt with 55mm pos printer.
> Paper size need to be fixed. It prints a long black paper.

Hi , Please check docs : http://test.local/documentation/index.html we added Guide to Setting Up Receipt Printer to work with POS Small Receipts . Thank you

**Comment by yavuzdemir3452** [comment]
Hello
printer settings are already standard size in all of them, they come automatically, because that's the paper size.

But since the output in your system is in A4 size, it looks like the image I sent you.

How can I set the output settings to the left? I want it or you can send it, let's upload it. It's been a long time since it was active on the system. Please don't get carried away, we want a solution. Many people have the same problem.

Thanks

![image](https://user-images.githubusercontent.com/84523818/120281265-65f58d00-c2c1-11eb-940d-8ffdb7115487.png)

**Comment by hamzakifani** [comment]
> Hello
> printer settings are already standard size in all of them, they come automatically, because that's the paper size.
> 
> But since the output in your system is in A4 size, it looks like the image I sent you.
> 
> How can I set the output settings to the left? I want it or you can send it, let's upload it. It's been a long time since it was active on the system. Please don't get carried away, we want a solution. Many people have the same problem.
> 
> Thanks
> 
> ![image](https://user-images.githubusercontent.com/84523818/120281265-65f58d00-c2c1-11eb-940d-8ffdb7115487.png)

Please give us some time we will fix this issue. thank you

**Comment by yavuzdemir3452** [comment]
Ok, we are waiting to hear from you. Please solve the problem, where you need to add the files, we will add them and share the file download link with us.

**Comment by hamzakifani** [comment]
![print](https://user-images.githubusercontent.com/50219942/120407000-1efcab80-c344-11eb-845a-36318c50c3bb.PNG)

we fixed this issue.
Go to \resources\src\assets\styles\sass\globals\views_pos.scss

and replace this:

#invoice-POS{
padding:2mm;
margin: 0 auto;
max-width: 400px;
}

with :

#invoice-POS{
padding:0;
margin: 0;
max-width: 470px;
}

run : npm install
run : npm run watch
run : npm run prod

**Comment by lifetill** [comment]
Please provide the custom code for the 55mm pos printer.

**Comment by naime-hossain** [comment]
issue fixed

**Comment by hamzakifani** [comment]
we fixed this problem
Please test print receipt on this demo .
http://demo.gesttio.com/login

and let us know if all is well . thank you

![Uploading 120842096-2c907c00-c564-11eb-94d9-815b21503ae2.png…]()

**Comment by lifetill** [comment]
Thank you dear
