### ISSUE TITLE
Please add a 'Clear Cache' Option

### ISSUE THREAD

**Issue by takrimabdullah** [uilibrary/Stocky-Issues-and-Feature-request#118]
Feature Request for Cache Control.

**Comment by naime-hossain** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
this feature has been added . thanks

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
