### ISSUE TITLE
Arabic language problem in pdf They appear as incomprehensible symbols

### ISSUE THREAD

**Issue by FRDOSI** [uilibrary/Stocky-Issues-and-Feature-request#119]
Arabic language problem in pdf
They appear as incomprehensible symbols

![image](https://user-images.githubusercontent.com/85011125/120062038-a8705d00-c068-11eb-8307-1aa5904037c9.png)

**Comment by naime-hossain** [comment]
Thank you for report this issue, we will fix this in the next updates.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by FRDOSI** [comment]
Another note
The script cannot be installed in a sub-file
www.111111.com/xxx

**Comment by FRDOSI** [comment]
Another note..
How do I use Google Fonts to change the font type in the script?

**Comment by naime-hossain** [comment]
> Another note
> The script cannot be installed in a sub-file
> [www.111111.com/xxx](http://www.111111.com/xxx)

its not develop to work in sub folder. create subdomain or use it in main domain thank you

**Comment by naime-hossain** [comment]
> Another note..
> How do I use Google Fonts to change the font type in the script?

if you type the same question in google you could've get the answer :)  you have use CDN and then add the font-family in scss , if you are developer you can do this otherwise will be tough for you. thank you

**Comment by FRDOSI** [comment]
Another note..
point of sale invoice
When displaying in Arabic, the direction is correct
When printing, the orientation changes to ltr .
It's supposed to be rtl

**Comment by FRDOSI** [comment]
> > Another note..
> > How do I use Google Fonts to change the font type in the script?
> 
> if you type the same question in google you could've get the answer :) you have use CDN and then add the font-family in scss , if you are developer you can do this otherwise will be tough for you. thank you

I mean the name of the folder and the name of the file to do the work
I have enough experience with css codes

**Comment by FRDOSI** [comment]
Another note
When changing to Dark Mode
Some writings disappear due to the color inconsistency of the design

**Comment by naime-hossain** [comment]
Please give us some time we will answer all your questions. thank you

**Comment by FRDOSI** [comment]
> Please give us some time we will answer all your questions. thank you

Don't worry about time..
I will just write notes here that will find a solution to the problems and contribute to the development of the script for the better..

**Comment by FRDOSI** [comment]
؟؟؟؟؟؟؟؟؟؟؟؟؟

**Comment by naime-hossain** [comment]
Ok Thank you for report these.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by FRDOSI** [comment]
FRDOSI commented 27 days ago

**Comment by FRDOSI** [comment]
naime-hossain commented 27 days ago
Please give us some time we will answer all your questions. thank you

**Comment by hamzakifani** [comment]
> Another note..
> How do I use Google Fonts to change the font type in the script?
If you want change css you will get all files sass on resources/src/assets/styles/sass .
after :
run : npm install
run : npm run watch
run : npm run prod

**Comment by hamzakifani** [comment]
> Another note
> When changing to Dark Mode
> Some writings disappear due to the color inconsistency of the design

Please send us the screen of probleme . Thank you

**Comment by hamzakifani** [comment]
> > > Another note..
> > > How do I use Google Fonts to change the font type in the script?
> > 
> > 
> > if you type the same question in google you could've get the answer :) you have use CDN and then add the font-family in scss , if you are developer you can do this otherwise will be tough for you. thank you
> 
> I mean the name of the folder and the name of the file to do the work
> I have enough experience with css codes

If you want change css you will get all files sass on resources/src/assets/styles/sass .

**Comment by hamzakifani** [comment]
> Another note..
> point of sale invoice
> When displaying in Arabic, the direction is correct
> When printing, the orientation changes to ltr .
> It's supposed to be rtl

Send us the screen of issue . Thank you
