### ISSUE TITLE
SMS API

### ISSUE THREAD

**Issue by lifetill** [uilibrary/Stocky-Issues-and-Feature-request#12]
Please add a SMS notification option for purchasers.

**Comment by lifetill** [comment]
How long it may take to update the feature?

**Comment by naime-hossain** [comment]
We are not sure about the exact date but will add for sure :), we have lots of features on the queue. We will let you know when you add this feature, if you like our work, you can leave a review that will motivate our team toward further development if possible.  If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by hamzakifani** [comment]
Good new !! for your suggestion about SMS API it will be on next update .
You can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
SMS API (Twilio) is added in version2.2.0 .  if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by mustercorder** [comment]
thank you for the update
