### ISSUE TITLE
How do I know the quantity of products  in the one warehouse

### ISSUE THREAD

**Issue by raar4ever** [uilibrary/Stocky-Issues-and-Feature-request#120]
How do I know the number of products in the warehouse? 
Add expiration date products with alarm,
Add the ability to collect several products and sell them as a combo offer
In addition to the possibility of buying at the wholesale price and the possibility of selling in bulk or by the single price pill
 .. Regards

**Comment by hamzakifani** [comment]
You will get all report of warehouse in 
https://stocky.ui-lib.com/app/reports/warehouse_report

Thank you for your suggestions, we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
