### ISSUE TITLE
Sale and Purchase return section totally wrong

### ISSUE THREAD

**Issue by AntZ-Dush** [uilibrary/Stocky-Issues-and-Feature-request#122]
Your System is very good compare with other Inventory Management systems with POS. But the Stocky sale and Purchase return section totally wrong. I have already informed you via git

in the usual sale and Purchase system, we have to flow the below steps

1- search sale or Purchase by a sale/ Purchase ID 2- just need to update the return quantity 3- submit as wastage return or stock agest return

but in your system, we need crate return manually its not the correct way

Please fix this major issue as soon as possible

**Comment by naime-hossain** [comment]
Thank you, we will check this issue and take action if needed.

**Comment by rafey022** [comment]
This isssue is not solved yet

**Comment by hamzakifani** [comment]
This feature has been fixed in latest version 4.0.2 .
Thanks
