### ISSUE TITLE
Products not showing on purchase products page.

### ISSUE THREAD

**Issue by Zackyismail** [uilibrary/Stocky-Issues-and-Feature-request#123]
Hello, I am having a problem, I have uploaded a product and I want to add a purchase but the problem is, when I go to the add purchase page and search for the product, it is not showing. Please help.

**Comment by hamzakifani** [comment]
Not showing product in search ?

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your app access

**Comment by Zackyismail** [comment]
Why are you taking me to different sides, I have just contacted you via the email you provided and you are telling to send the issue here. I am really confused?

**Comment by Zackyismail** [comment]
Also, login does not work in localhost while the credentials are correct.  I am really disappointed with your support team.

**Comment by hamzakifani** [comment]
> Why are you taking me to different sides, I have just contacted you via the email you provided and you are telling to send the issue here. I am really confused?

if you have uploaded stocky in server send us your app access to check this problem . how can we know this problem? please collaborate with us . thank you

**Comment by hamzakifani** [comment]
> Also, login does not work in localhost while the credentials are correct. I am really disappointed with your support team.

it's working fine in localhost . but you can check console and send us the error . thank you
