### ISSUE TITLE
Wrong Flag for Thailand

### ISSUE THREAD

**Issue by ongarta** [uilibrary/Stocky-Issues-and-Feature-request#124]
The Flag for Thai in the language picker is currently wrong. 
It should be flag-icon-th not flag-icon-tw.

**Comment by hamzakifani** [comment]
Thank you we will fix this issue soon. 

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
Fixed
