### ISSUE TITLE
What is wrong with installation?

### ISSUE THREAD

**Issue by karolisrak** [uilibrary/Stocky-Issues-and-Feature-request#125]
Hey all. each time I'm trying to install Stocky to server, I always get white background and after installation, nothing happening.
![image](https://user-images.githubusercontent.com/85228610/120468344-c5c76300-c3a9-11eb-99b0-bfaf8089b9dc.png)
![image](https://user-images.githubusercontent.com/85228610/120468752-3cfcf700-c3aa-11eb-96e0-0a39c5f310b4.png)

Created subdomain and trying to install everything into subdomain. What I should do to solve this?

**Comment by hamzakifani** [comment]
I see you are not creating a subdomain

**Comment by karolisrak** [comment]
> I see you are not creating a subdomain

How I can contact you personally? There is a subdomain in a system...

**Comment by karolisrak** [comment]
found the problem..... thanks

**Comment by hamzakifani** [comment]
Great job . if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by Zackyismail** [comment]
Please reply to this *******
*********************************************************
I have installed on my localhost.
Let me explain my problem.

I have imported the products and I tried to purchase the products I just imported. When I go to the purchase products page and try to search for the product I found that it is empty. Similarly, at the POS, there are no products but on the product page, it is showing it has successfully imported and I can see them very well but they are not visible in purchases page.

Please help me solve this issue as I want to move forward and purchase more licenses. 

Also in your next update please add a balance to the POS when a customer is paying for a product.


Looking forward to hearing from you.
