### ISSUE TITLE
Can't log in and can't reset password

### ISSUE THREAD

**Issue by hificom** [uilibrary/Stocky-Issues-and-Feature-request#127]
Forgot my login password.
And Program will not reset
It shows error 
![Screen Shot 2021-06-03 at 8 26 10 AM](https://user-images.githubusercontent.com/85292687/120644608-85b5be00-c445-11eb-8635-ab5f131c99d0.JPG)

**Comment by hamzakifani** [comment]
Smtp config invalid

**Comment by hificom** [comment]
what is correct smtp info, and how do we check this.

THERE IS NO REAL TUTORIAL.  AND THE DOCUMENTATION DOES NOT EXPLAIN ANYTHING AT ALL!!
THIS IS SOOOOO FRUSTRATING!!!

**Comment by ashiqdey** [comment]
SMPT details can be found in your web host, try contacting  your web host and put in env file
