### ISSUE TITLE
Can not add purchase

### ISSUE THREAD

**Issue by hificom** [uilibrary/Stocky-Issues-and-Feature-request#130]
Creating a Purchase is not working... 
It seems to freeze and takes over 10 minutes to even process.

I tried adding a purchase using POS and the standard way... they both only freeze

![Screen Shot 2021-06-03 at 7 39 03 PM](https://user-images.githubusercontent.com/85292687/120725219-79f8e480-c4a3-11eb-97b3-0bb96fc53699.JPG)

**Comment by hamzakifani** [comment]
if you choose payment with credit credit you must add stripe key in setting. how you can pay with credit card without entering the info?
