### ISSUE TITLE
How to Change Logo on Login Page

### ISSUE THREAD

**Issue by muneshprasad** [uilibrary/Stocky-Issues-and-Feature-request#133]
How can i Change Logo on Login Page so that it reflects my logo.. same for the favicon icon.

**Comment by muneshprasad** [comment]
please advise on above

**Comment by naime-hossain** [comment]
We will add an option to dynamically update the logo in the next update. thank you

**Comment by ashiqdey** [comment]
change from here
`project_url\public\images`
