### ISSUE TITLE
Alpha SMS API integration 

### ISSUE THREAD

**Issue by mustercorder** [uilibrary/Stocky-Issues-and-Feature-request#137]
### Hi, there 
Please provide custom code integrate with alpha SMS API.

### **Send SMS (Example)**

**Example GET Method:**

`http://alphasms.biz/index.php?app=ws&u=username&h=a45a02791b2fe2fedb078c39fd83637a&op=pv&to=01979547393&msg=test+only`

**When succeeded Server will returns OK status message in JSON format:**

`{'data':[{'status':'OK','error':'0','smslog_id':'30','queue':'afb5f34575e30ec4efe4471cf5d1bee4','to':'01979547393'}],'error_string':null}
`

### _Single SMS_

`http://msk.sms.net.bd/api/mt/SendSMS?user=demo&password=demo123&senderid=WEBSMS&channel=Normal&DCS=0&flashsms=0&number=91989xxxxxxx&text=test `

`Response : {"ErrorCode":"000","ErrorMessage":"Done","JobId":"20047","MessageData":[{"Number":"91989xxxxxxx","MessageId":"mvHdpSyS7UOs9hjxixQLvw"},{"Number":"917405080952","MessageId":"PfivClgH20iG6G5R3usHwA"}]}`

**Multiple SMS**

`http://msk.sms.net.bd/api/mt/SendSMS?user=demo&password=demo123&senderid=WEBSMS&channel=Normal&DCS=0&flashsms=0&number=91989xxxxxxx,91999xxxxxxx&text=test `

`Response : {"ErrorCode":"000","ErrorMessage":"Done","JobId":"20047","MessageData":[{"Number":"91989xxxxxxx","MessageId":"mvHdpSyS7UOs9hjxixQLvw"},{"Number":"91999xxxxxxx","MessageId":"PfivClgH20iG6G5R3usHwA"}]}`

**Schedule SMS**

`http://msk.sms.net.bd/api/mt/SendSMS?user=demo&password=demo123&senderid=WEBSMS&channel=Normal&DCS=0&flashsms=0&number=91989xxxxxxx&text=test `

**Group SMS**

`http://msk.sms.net.bd/api/mt/SendSMS?user=demo&password=demo123&senderid=WEBSMS&channel=Normal&DCS=0&flashsms=0&number=91989xxxxxxx&text=test`

`Response : {"ErrorCode":"000","ErrorMessage":"Done","JobId":"20047","MessageData":[{"Number":"91989xxxxxxx","MessageId":"mvHdpSyS7UOs9hjxixQLvw"},{"Number":"91999xxxxxxx","MessageId":"PfivClgH20iG6G5R3usHwA"}]}`

**Check Delivery API**

```
`http://msk.sms.net.bd/api/mt/GetDelivery?user=demo&password=demo123&jobid=#######`

Response {"ErrorCode":"0","ErrorMessage":"Done","MessageId":null,"DeliveryReports":[{"MessageId":"mvHdpSyS7UOs9hjxixQLvw","DeliveryStatus":"Delivered","DeliveryDate":"2015-09-28T06:17:00"},{"MessageId":"PfivClgH20iG6G5R3usHwA","DeliveryStatus":"Delivered","DeliveryDate":"2015-09-28T06:17:00"}]}
`

**Check Balance API**

`http://msk.sms.net.bd/api/mt/GetBalance?User=demo&Password=demo123
`
`Response :- {"ErrorCode":"0","ErrorMessage":"Done","Balance":"Wallet:"}
`

**Comment by mustercorder** [comment]
For more you can check this [link](https://alpha.net.bd/SMS/API/)

**Comment by mustercorder** [comment]
Looking for update?

**Comment by mustercorder** [comment]
I'm looking for attention on this issue!
@naime-hossain

**Comment by mustercorder** [comment]
### **API URL**
http(s)://alphasms.biz/index.php?app=ws

Send SMS (Example)
Example GET Method:

http://alphasms.biz/index.php?app=ws&u=YOUR_API_USERNAME&h=YOUR_API_HASH_TOKEN&op=pv&to=01979547393&msg=test+only

### When succeeded Server will returns OK status message in JSON format:

`{'data':[{'status':'OK','error':'0','smslog_id':'30','queue':'afb5f34575e30ec4efe4471cf5d1bee4','to':'01979547393'}],'error_string':null}`

### SMS API Codes Samples in PHP

   ```
 $username = "YOUR_API_USERNAME";
    $hash = "YOUR_API_HASH_TOKEN"; 
    $numbers = "017xxxxxxxx,018xxxxxxxx"; //Recipient Phone Number multiple number must be separated by comma
    $message = "Simple text message.";


    $params = array('app'=>'ws', 'u'=>$username, 'h'=>$hash, 'op'=>'pv', 'unicode'=>'1','to'=>$numbers, 'msg'=>$message);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, "http://alphasms.biz/index.php?".http_build_query($params, "", "&"));
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type:application/json", "Accept:application/json"));
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);

    $response = curl_exec($ch);
    curl_close ($ch);
```

**Comment by mustercorder** [comment]
@naime-hossain @mh-rafi

**Comment by hamzakifani** [comment]
Hi , 
You still want to add this ??
