### ISSUE TITLE
Can't resolve './views/app/pages/expense/Create_expense

### ISSUE THREAD

**Issue by SamuelMwangiW** [uilibrary/Stocky-Issues-and-Feature-request#138]
Kindly rename `create_expense.vue` and `edit_expense.vue` to `Create_expense.vue` and `Edit_expense.vue`.

Failing with the above error at build.

**Comment by hamzakifani** [comment]
Delete your package-lock.json file and node_modules folder. Then run :

npm cache clean—force
npm install
npm run watch
npm run prod

**Comment by SamuelMwangiW** [comment]
Thanks @hamzakifani for your suggestions but I already indicated how to resolve the issue: the files in question are incorrectly named (first letter is lowercase). 
Whereas npm may not throw an error in windows, running npm on MacOS or Linux will always throw the error above.
