### ISSUE TITLE
Tip: Artisan Command

### ISSUE THREAD

**Issue by SamuelMwangiW** [uilibrary/Stocky-Issues-and-Feature-request#139]
Whereas the step-by-step setup procedure works well for most cases, there are those that prefer to get up and running using artisan command line tool. 
Am sharing below my simplified version of `php artisan stocky:setup` should it interest anyone. 
This is a proxy to the commands below and assumes you have correctly configured `.env`

- `php artisan migrate:fresh --seed --force` 
- `php artisan storage:link`
- `php artisan passport:install`
- `touch storage/app/public/installed`

```PHP
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Database\Console\Migrations\FreshCommand;
use Illuminate\Foundation\Console\StorageLinkCommand;
use Illuminate\Support\Facades\Storage;
use Laravel\Passport\Console\InstallCommand as PassportInstallCommand;

class SetupApplicationCommand extends Command
{
    protected $signature = 'stocky:setup';
    protected $description = 'Setup Stocky for first time use';

    public function handle(): int
    {
        $this->call(FreshCommand::class, ['--force' => true,'--seed'=>true]);
        $this->call(StorageLinkCommand::class);
        $this->call(PassportInstallCommand::class);
        Storage::disk('public')->put('installed', '');
        return 0;
    }
}

```

**Comment by hamzakifani** [comment]
thank you for your suggestion we will add more features in the future.
if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
