### ISSUE TITLE
Auto Print Receipt From POS

### ISSUE THREAD

**Issue by BKB16** [uilibrary/Stocky-Issues-and-Feature-request#14]
Request Features Auto Print Receipt From POS

**Comment by naime-hossain** [comment]
We already have feature that pop up receipt after pos sale, can you describe in details about this feature ?

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
