### ISSUE TITLE
Adjustments Restrictions 

### ISSUE THREAD

**Issue by SamuelMwangiW** [uilibrary/Stocky-Issues-and-Feature-request#140]
I note that you have restricted adjustments to items with stock levels higher than 0.
In my humble opinion, restricting adjustments only to items with stock items in the system defeats the whole purpose of adjustment and have disabled it on my setup. 
It's perfectly possible during physical stock count to discover items whose system count is 0 hence a need to adjust. It also makes it hard to record initial stock levels during initial setup. I know there's an option to record initial stock as purchases but a more practical approach would be to record initial stock as quantity adjustments. 
I appreciate the rationale may be to avoid negative stock but still...

**Comment by hamzakifani** [comment]
Hi. To add adjustment you have to purchase the product first. Because the adjustments comes when you have stock.

Adjustment can only occur when you have stock. Without stock how can you adjust quantity? So purchase that product first. Then you can make adjustment. Thank you

**Comment by SamuelMwangiW** [comment]
How then do you handle a situation where system shows an item as sold out but then realize some items in the store. Is that still a purchase?
