### ISSUE TITLE
Stocky setup page not found after upload to webhost

### ISSUE THREAD

**Issue by mm2multimedia** [uilibrary/Stocky-Issues-and-Feature-request#141]
I have some issues getting the initial setup page up and running. 

I copied the full content of the Stocky_V2.5.0 folder inside the zip, downloaded from Codecanyon. After uploading it to my external subdomain.domain webhost (no cPanel) which meets all the php and mysql requirements.

- The http://subdomain.domain/setup page is reported as not found.
- The root http://subdomain.domain shows a forbidden page. 
- http://subdomain.domain/server.php shows a Stocky styled 500 | server error. 

I see some comments of you referring to _npm run prod_ commands. But this is not mentioned in the instruction manual so I assume this is not required for Stocky to run by default. I also assume I can run Stocky on a passive webserver, without NPM as it’s not stated as a requirement. 

Can I please get some help getting the setup working so I can install Stocky in the MySQL database? 
Any help is very much appreciated.

**Comment by naime-hossain** [comment]
You post the issue 40 min ago and its 2.19am here , and without waiting for our reply why you gave Bad rating ? is this fair ?

**Comment by mm2multimedia** [comment]
That's great! I'll wait patiently for your response. Thank you!

**Comment by hamzakifani** [comment]
Please check all the php and mysql requirements. Thank you

**Comment by mm2multimedia** [comment]
> Please check all the php and mysql requirements. Thank you

Thank you for your response. As mentioned in my initial post the requirements look good to me:
- MySQL Ver 15.1 Distrib 10.3.24-MariaDB, for Linux
- PHP v7.4.16
- PHP info shows I have all these plugins enabled/active:
BCMath PHP Extension
Ctype PHP Extension
Fileinfo PHP Extension
GD2 PHP Extension
JSON PHP Extension
Mbstring PHP Extension
OpenSSL PHP Extension
PDO PHP Extension
Tokenizer PHP Extension
XML PHP Extension

**Comment by hamzakifani** [comment]
we have not tested stocky on free host .
Please use cpanel is better than free host 
, thank you .
