### ISSUE TITLE
no carga imagen al producto

### ISSUE THREAD

**Issue by vbossa** [uilibrary/Stocky-Issues-and-Feature-request#142]
Al subir en distintas extensiones las imágenes de los productos, este no lo carga queda en estado cargando y no guarda el producto.

**Comment by hamzakifani** [comment]
English Please

**Comment by vbossa** [comment]
When uploading the images of the products in different extensions, this is not loaded in the loading state and does not save the product.

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your App access . Thank you
