### ISSUE TITLE
Project not working while placed in folder

### ISSUE THREAD

**Issue by ashiqdey-takeoff** [uilibrary/Stocky-Issues-and-Feature-request#144]
![not-working-in-folder](https://user-images.githubusercontent.com/83806448/121932419-7d715300-cd62-11eb-8f87-56c47086b64c.png)
I had setup the project in a folder "projects/pos" but the here's what i can see while hitting the URL

**Comment by ashiqdey-takeoff** [comment]
It working when placed in root folder, but i want it to be in specific folder,
Somehow managed to install stocky in subdomain but in setup screen when i click next it shows "page expired"

please help me with setup

**Comment by hamzakifani** [comment]
not develop to work in sub folder. create subdomain or use it in main domain.

**Comment by hamzakifani** [comment]
If you don't fix it . Please contact via : uilib.help@gmail.com with your cpanel access
