### ISSUE TITLE
Dashboard didn't show the correct data

### ISSUE THREAD

**Issue by teehanming** [uilibrary/Stocky-Issues-and-Feature-request#146]
![image](https://user-images.githubusercontent.com/65308523/122085227-16709e80-ce35-11eb-9da9-9e61d9004b0f.png)

**Comment by hamzakifani** [comment]
Why ??

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
