### ISSUE TITLE
XAMPP Setup Issue

### ISSUE THREAD

**Issue by ofsanlialp** [uilibrary/Stocky-Issues-and-Feature-request#148]
Hi,
I followed all the setup instructions for XAMPP on Ubuntu desktop. (your virtual environment directory paths were for windows so I modified for ubuntu). However, it doesn't able to locate stocky.local/setup. I check the zip file but couldn't find any index file directly under stocky folder

Here is the virtual host config file:
                             
```
<VirtualHost stocky.local:80>
        ServerAdmin webmaster@stocky.local
        DocumentRoot "/opt/lampp/htdocs/stocky"
        ServerName www.stocky.local
        ServerAlias stocky.local

        <Directory "/opt/lampp/htdocs/stocky">
                 Options Indexes FollowSymLinks Includes ExecCGI
                 AllowOverride All
                 Require all granted
        </Directory>

        ErrorLog "logs/stocky.local-error.log"
        CustomLog "logs/stocky.local-access.log" common
</VirtualHost>
```

**Comment by hamzakifani** [comment]
test with : 
http://localhost/stocky

**Comment by ofsanlialp** [comment]
stocky.local/setup is working on windows server but, I couldn't run on ubuntu. What it can be the issue?

**Comment by hamzakifani** [comment]
we have not tested on ubuntu . Thank you
