### ISSUE TITLE
After deleting USD from currency all products has gone.

### ISSUE THREAD

**Issue by mustercorder** [uilibrary/Stocky-Issues-and-Feature-request#149]
After deleting USD from currency all products has gone.
https://prnt.sc/15kj9pr

**Comment by hamzakifani** [comment]
There is not a problem . I deleted all currency and it works fine . 

![currency](https://user-images.githubusercontent.com/50219942/122210916-148ef580-ce9e-11eb-93ff-ee2a892ae203.PNG)

![pp](https://user-images.githubusercontent.com/50219942/122210936-18bb1300-ce9e-11eb-95b0-7c9e1b8a6f12.PNG)

**Comment by mustercorder** [comment]
What's the issue? 
![Screenshot_5](https://user-images.githubusercontent.com/83014495/122214710-3acb8a00-cecc-11eb-890f-616b7fbe1a25.png)
![Screenshot_7](https://user-images.githubusercontent.com/83014495/122214718-3c954d80-cecc-11eb-86d7-1275fb85f914.png)

**Comment by mustercorder** [comment]
Hey can you please come over anydesk?

**Comment by hamzakifani** [comment]
> What's the issue?
> ![Screenshot_5](https://user-images.githubusercontent.com/83014495/122214710-3acb8a00-cecc-11eb-890f-616b7fbe1a25.png)
> ![Screenshot_7](https://user-images.githubusercontent.com/83014495/122214718-3c954d80-cecc-11eb-86d7-1275fb85f914.png)

This is not issue . Please choose warehouse to show products . Thank you

**Comment by mustercorder** [comment]
Thank you for your update.

**Comment by mustercorder** [comment]
.
