### ISSUE TITLE
Auto Select For Walk In Customer

### ISSUE THREAD

**Issue by BKB16** [uilibrary/Stocky-Issues-and-Feature-request#15]
request Features Auto Select For Walk In Customer

**Comment by naime-hossain** [comment]
Can you give an elaborate Description of this feature? thank you

**Comment by hamzakifani** [comment]
Walk in customer added . Please use the latest version 2.2.0 .thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
