### ISSUE TITLE
Edit code show 500 server error

### ISSUE THREAD

**Issue by weimeng3149** [uilibrary/Stocky-Issues-and-Feature-request#150]
Hi I edited some code and run:
1) download nodejs 
2) run : npm install 
3) npm run prod
But it show 500 server error, please assist

**Comment by hamzakifani** [comment]
npm install
npm run watch
npm run prod

**Comment by weimeng3149** [comment]
I tried and successful but didn't change anything with the code

**Comment by weimeng3149** [comment]
I changed login logo and sidebar.vue and run that but it didn't change.

**Comment by naime-hossain** [comment]
Please check some tutorials on the basic Laravel+vue project .
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
