### ISSUE TITLE
Xampp Issue

### ISSUE THREAD

**Issue by AhmedMaherPro** [uilibrary/Stocky-Issues-and-Feature-request#151]
hello 
when try to install it on xampp this this issue show
![layoutProblem](https://user-images.githubusercontent.com/25661721/122222638-bcaeb980-ceb2-11eb-949e-08bf1265b616.PNG)

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by hamzakifani** [comment]
please check docs and follow the setup installation http://stocky.ui-lib.com/documentation/index.html

**Comment by AhmedMaherPro** [comment]
![subdomain](https://user-images.githubusercontent.com/25661721/122223480-7c037000-ceb3-11eb-81a7-14e7de25fb43.PNG)

**Comment by hamzakifani** [comment]
It's working fine . follow the setup installation http://stocky.ui-lib.com/documentation/index.html

**Comment by hamzakifani** [comment]
Installation in Localhost
you need to download XAMPP or LAMPP Server

Step 1 : Go to C:\Windows\system32\drivers\etc\ open the "hosts" file in Administrator mode.

Step 2 : Add the following code to it. Here

127.0.0.1 stocky.local

Step 3 : Now go to, C:\xampp\apache\conf\extra for xampp users and for the wamp user "C:\wamp\bin\apache\Apache2.4.4\conf\extra" and open "httpd-vhosts.conf" file. Now add the following code into it.

Notes :Change the Document root as per your project also add domain name as you define into the "hosts" file.


               ```
<VirtualHost stocky.local:80>
                  ServerAdmin webmaster@stocky.local
                  DocumentRoot "C:/xampp/htdocs/stocky"
                  ServerName www.stocky.local
                  ServerAlias stocky.local
              
                   <Directory "C:/xampp/htdocs/stocky">
                          Options Indexes FollowSymLinks Includes ExecCGI
                          AllowOverride All
                          Require all granted
                      </Directory>
              
                  ErrorLog "logs/stocky.local-error.log"
                  CustomLog "logs/stocky.local-access.log" common
              </VirtualHost>
```
Step 4 : Last but the important step is to restart your Xampp or Wamp

Setup Installation : Access the url http://stocky.local/setup

**Comment by AhmedMaherPro** [comment]
it's working , thank you 
another questions please

**Comment by hamzakifani** [comment]
You can change it on : 
resources/src/assets/styles/sass/globals/_globals.scss
 and run :

npm install
npm run watch
npm run prod

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
