### ISSUE TITLE
CSS changes possible?

### ISSUE THREAD

**Issue by ashiqdey** [uilibrary/Stocky-Issues-and-Feature-request#152]
1. I want to change the theme color according to my brand color, is it possible?
2. I want to rearrange /remove sidebar's cards
3. Payment spelling on report page is "Paiements" how can i change it?
4. I want to remove the doc card form sidebar
5. Everytime i perform some operation i have to select the warehouse, can we make a warehouse default?
6. Dark mode is not complete when can we expect complete dark mode?

**Comment by naime-hossain** [comment]
If you know laravel and vue then you can do these customizations, we will check the dark mode.
edit navigation.js file for remove doc link
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
If you want change css you will get all files sass on resources/src/assets/styles/sass . 
after : 
run : npm install
run : npm run watch
run : npm run prod

3) If you need change translation

Go to /resources/src/translations/locales/
after : 

run : npm install
run : npm run watch
run : npm run prod

5)  This option is available on last version Stocky V 2.5.0 .
