### ISSUE TITLE
Barcode and add other options at products 

### ISSUE THREAD

**Issue by DjTazTqM** [uilibrary/Stocky-Issues-and-Feature-request#153]
How I add stuff at products like size, color, i have check all settings 
and i dont see how to make this changes and the other is the barcode i 
have my own barcodes,

**Comment by hamzakifani** [comment]
You have this option multi variants . 

![var](https://user-images.githubusercontent.com/50219942/122580794-3dee8380-d04e-11eb-8c6e-b07662e33a52.PNG)

But we will add more features in future if you have any specific feature request then you can submit here https://github.com/uilibrary/Stocky-Issues-and-Feature-request . Thank you :)
