### ISSUE TITLE
installation problem in wampserver

### ISSUE THREAD

**Issue by hamidhada** [uilibrary/Stocky-Issues-and-Feature-request#154]
Hi there,
Can you help me please on installing the application on my local machine. But not by using the local.stocky url I want to use wampserver as the server for the application cause it will be accessible via lan network. So far I did manage to make wampserver accessible via lan network but when I run the application from the http://localhost/stocky it's not running properly cause the resources are not loaded correctly help me please solving this problem.
Thank you

**Comment by hamzakifani** [comment]
Please see this issue . 
https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues/151

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
