### ISSUE TITLE
npm run dev long time

### ISSUE THREAD

**Issue by MarcelCH** [uilibrary/Stocky-Issues-and-Feature-request#155]
I have executed npm run dev and it running a long time, 
**how to run faster?**

> @ development C:\xampp\htdocs\stocky
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

92% chunk asset optimization targets-optimize-chunk-assets

**Comment by hamzakifani** [comment]
Hi ,
You can remove this plugin from webpack . This plugin for transcompiling final bundles so they support legacy browsers .thank you

**Comment by hamzakifani** [comment]
Please watch this video 
https://www.loom.com/share/5996281ca03a4380b9fa4103b5f3e9d0

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
