### ISSUE TITLE
Changes not reflecting

### ISSUE THREAD

**Issue by ashiqdey** [uilibrary/Stocky-Issues-and-Feature-request#157]
I had made some changes in vue template.
I had remove language selection, RTL selector, link for docs from sidebar but my website is not showing the changes. Is there anything to do?

**Comment by hamzakifani** [comment]
After change :
run : npm install
run : npm run watch
run : npm run prod

**Comment by ashiqdey** [comment]
I can perform npm only in my local system not in server, so I just used `display:none;` using css to hide the elements.

As m not aware if the project can be copied to server after performing npm on local. please revert back with response.

**Comment by hamzakifani** [comment]
make your modification in local.  
and run npm.  
after upload the files you modified + folder public/js in your cpanel

**Comment by ashiqdey** [comment]
Thanks alot, You guy's support is really appreciable, your product will definitely make the way in market

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
