### ISSUE TITLE
App not signing in => The issue was in php version 8 which is not compatible now :)

### ISSUE THREAD

**Issue by Stridesdata** [uilibrary/Stocky-Issues-and-Feature-request#16]
I have installed on my local server, But it's not signing in. When you click sign in .. No action occurs, No error message

**Comment by naime-hossain** [comment]
Can you please send a screenshot? and what dev server are you using? Xamp/Laragon/or ? Thank you

**Comment by Stridesdata** [comment]
![image](https://user-images.githubusercontent.com/82326559/115108771-27528000-9f6a-11eb-9754-c9aea07cd989.png)


I am using Xampp

**Comment by hamzakifani** [comment]
Please give us a screenshot of console when to click Sign In

**Comment by Stridesdata** [comment]
![image](https://user-images.githubusercontent.com/82326559/115114392-fc2a5980-9f86-11eb-89f7-c4697b97ddc4.png)

**Comment by hamzakifani** [comment]
click on the last error and capture it

**Comment by Stridesdata** [comment]
![image](https://user-images.githubusercontent.com/82326559/115115770-27fd0d80-9f8e-11eb-8409-aa960702a415.png)

**Comment by hamzakifani** [comment]
Please click in : http:// stocky.local/api/login 
And capture the error .

**Comment by Stridesdata** [comment]
![image](https://user-images.githubusercontent.com/82326559/115116081-bb830e00-9f8f-11eb-926f-9e09d3698ed7.png)

**Comment by hamzakifani** [comment]
Click in response to show what this error

**Comment by Stridesdata** [comment]
{
    "message": "Server Error"
}

**Comment by hamzakifani** [comment]
on your project there is a file ".env"
![env](https://user-images.githubusercontent.com/50219942/115116389-be2e3500-9f88-11eb-86b0-375c40b339cd.PNG)

open it and make sure you put APP_DEBUG = true to see the errors
and make sure you have put the correct DB_DATABASE
![ennv](https://user-images.githubusercontent.com/50219942/115116431-fb92c280-9f88-11eb-9e79-2d2e4a9b663a.PNG)

**Comment by Stridesdata** [comment]
{
    "message": "It was not possible to parse your key, reason: ",
    "exception": "Lcobucci\\JWT\\Signer\\InvalidKeyProvided",
    "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\lcobucci\\jwt\\src\\Signer\\InvalidKeyProvided.php",
    "line": 17,
    "trace": [
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\lcobucci\\jwt\\src\\Signer\\OpenSSL.php",
            "line": 85,
            "function": "cannotBeParsed",
            "class": "Lcobucci\\JWT\\Signer\\InvalidKeyProvided",
            "type": "::"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\lcobucci\\jwt\\src\\Signer\\OpenSSL.php",
            "line": 42,
            "function": "validateKey",
            "class": "Lcobucci\\JWT\\Signer\\OpenSSL",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\lcobucci\\jwt\\src\\Signer\\OpenSSL.php",
            "line": 18,
            "function": "getPrivateKey",
            "class": "Lcobucci\\JWT\\Signer\\OpenSSL",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\lcobucci\\jwt\\src\\Signer\\BaseSigner.php",
            "line": 38,
            "function": "createHash",
            "class": "Lcobucci\\JWT\\Signer\\OpenSSL",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\lcobucci\\jwt\\src\\Builder.php",
            "line": 588,
            "function": "sign",
            "class": "Lcobucci\\JWT\\Signer\\BaseSigner",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\lcobucci\\jwt\\src\\Builder.php",
            "line": 547,
            "function": "createSignature",
            "class": "Lcobucci\\JWT\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\league\\oauth2-server\\src\\Entities\\Traits\\AccessTokenTrait.php",
            "line": 71,
            "function": "getToken",
            "class": "Lcobucci\\JWT\\Builder",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\league\\oauth2-server\\src\\Entities\\Traits\\AccessTokenTrait.php",
            "line": 79,
            "function": "convertToJWT",
            "class": "Laravel\\Passport\\Bridge\\AccessToken",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\league\\oauth2-server\\src\\ResponseTypes\\BearerTokenResponse.php",
            "line": 31,
            "function": "__toString",
            "class": "Laravel\\Passport\\Bridge\\AccessToken",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\league\\oauth2-server\\src\\AuthorizationServer.php",
            "line": 202,
            "function": "generateHttpResponse",
            "class": "League\\OAuth2\\Server\\ResponseTypes\\BearerTokenResponse",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\passport\\src\\PersonalAccessTokenFactory.php",
            "line": 116,
            "function": "respondToAccessTokenRequest",
            "class": "League\\OAuth2\\Server\\AuthorizationServer",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\passport\\src\\PersonalAccessTokenFactory.php",
            "line": 71,
            "function": "dispatchRequestToAuthorizationServer",
            "class": "Laravel\\Passport\\PersonalAccessTokenFactory",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\passport\\src\\HasApiTokens.php",
            "line": 67,
            "function": "make",
            "class": "Laravel\\Passport\\PersonalAccessTokenFactory",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\app\\Http\\Controllers\\AuthController.php",
            "line": 40,
            "function": "createToken",
            "class": "App\\Models\\User",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
            "line": 54,
            "function": "getAccessToken",
            "class": "App\\Http\\Controllers\\AuthController",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 239,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 196,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\public\\index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\bookeepit\\server.php",
            "line": 21,
            "function": "require_once"
        }
    ]
}

**Comment by hamzakifani** [comment]
downgrading from php version 8 to version 7.3 solved this issue

**Comment by hamzakifani** [comment]
download this version of xampp 
https://www.apachefriends.org/download.html
![apache](https://user-images.githubusercontent.com/50219942/115116738-c8e9c980-9f8a-11eb-8ada-99d6e4a6db91.PNG)

**Comment by Stridesdata** [comment]
I have other application running on PHP 8

I hope i do not have issues with other applications

**Comment by Stridesdata** [comment]
How do I downgrade safely

**Comment by hamzakifani** [comment]
you can use laragon very easy

**Comment by naime-hossain** [comment]
> I have other application running on PHP 8
> 
> I hope i do not have issues with other applications

Please use laragon this best for Laravel and you can use multiple PHP version https://laragon.org/

**Comment by Stridesdata** [comment]
The process for installing on laragon is not in your docimentation

**Comment by Stridesdata** [comment]
This installation process has been too hectic.. I have never had it so difficult

**Comment by hamzakifani** [comment]
1) add your folder in C:\laragon\www 
2) Then reload your laragon server
3) make sure your xampp server is off

Then you should see your project is up at http://name_of_folder.test

**Comment by Stridesdata** [comment]
I have been able to log in downgrading my PHP on Xampp, however I do not like the fact that I have to downgrade to a lower version. As my other apps require a 7.4 and above

I will start working with what I have, kindly let me know when it becomes compatible with higher php versions

**Comment by Stridesdata** [comment]
One last question.. how do I prevent my motivations conflicting with future updates...

And I appreciate you sticking with me though all this issue.

Adding My review now

**Comment by naime-hossain** [comment]
> I have been able to log in downgrading my PHP on Xampp, however I do not like the fact that I have to downgrade to a lower version. As my other apps require a 7.4 and above
> 
> I will start working with what I have, kindly let me know when it becomes compatible with higher php versions

The app is working on php7.4 fine , we will add php8 support soon. thank you

**Comment by naime-hossain** [comment]
> One last question.. how do I prevent my motivations conflicting with future updates...
> 
> And I appreciate you sticking with me though all this issue.
> 
> Adding My review now

We added an auto Upgrade guide, you can update the app with a future versions by following the installation guide. thank you

**Comment by naime-hossain** [comment]
The issue was in php version 8 which is not compatible now :)

**Comment by naime-hossain** [comment]
> Adding My review now
Thank you for cooperate and your review will motivate us :)

**Comment by naime-hossain** [comment]
> > Adding My review now
> 
> Thank you for cooperate and your review will motivate us :)

if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
> > > Adding My review now
> > 
> > 
> > Thank you for cooperate and your review will motivate us :)
> 
> if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

Problem Fixed

**Comment by naime-hossain** [comment]
> 
> And I appreciate you sticking with me though all this issue.
> 
> Adding My review now

Hello, Hope you are doing well, Can you spare some time to review our item on codecanyon, if possible. thank you :)
