### ISSUE TITLE
Setup url cannot access

### ISSUE THREAD

**Issue by sam2909** [uilibrary/Stocky-Issues-and-Feature-request#161]
Hi Team,

I have just bough your code and set it up to my server.

My server was configured with Centos 7, PHP 4, Nginx,....

After I had upload code to my server, I tried to acess setup URL: http://mydomain.com/setup

**It show 500 error 

This page isn’t working right now mydomain.com can't currently handle this request.
HTTP ERROR 500**

Pls help and ty very much.

**Comment by hamzakifani** [comment]
you will need to make sure your server meets the following requirements:

PHP >= 7.3.0
Mysql 5.x or higher
BCMath PHP Extension
Ctype PHP Extension
Fileinfo PHP Extension
GD2 PHP Extension
JSON PHP Extension
Mbstring PHP Extension
OpenSSL PHP Extension
PDO PHP Extension
Tokenizer PHP Extension
XML PHP Extension

**Comment by sam2909** [comment]
Hi, I'm sure my server met requirement:

you can check here
http://test.bmpp.me/info.php

Mysql version:

mysql -V
mysql  Ver 15.1 Distrib 5.5.65-MariaDB, for Linux (x86_64) using readline 5.1

Document root I using /root_folder/public -> show 500 error when i access http://test.bmpp.me/setup
Document root I use /root_folder -> show 404 error when i access http://test.bmpp.me/setup

**Comment by sam2909** [comment]
This error had fixed.
Thanks team.

**Comment by naime-hossain** [comment]
Great job, what was the issue and how you fix this
Thank you
