### ISSUE TITLE
Quotation Design

### ISSUE THREAD

**Issue by ibrafayez** [uilibrary/Stocky-Issues-and-Feature-request#162]
Hello,

Is there a way to design a quotation instead of the given design? (i.e add colors, add footer, add company logo...etc)

<img width="601" alt="Screen Shot 2021-06-21 at 11 55 09 PM" src="https://user-images.githubusercontent.com/44995398/122826924-672c3f80-d2ec-11eb-9a67-75dec718f5a3.png">

Thank you

**Comment by hamzakifani** [comment]
you can download pdf of quotation already designed . Thank you

**Comment by ibrafayez** [comment]
When I click download PDF it doesn't work, it just shows the loading icon on the top-right.

**Comment by hamzakifani** [comment]
It's working fine on demo . You can check . 
But contact via : mr.hamza.kifani@gmail.com with your app access

**Comment by ibrafayez** [comment]
https://user-images.githubusercontent.com/44995398/122828977-081bfa00-d2ef-11eb-9889-8aba5f36c7cc.mp4

**Comment by hamzakifani** [comment]
Please watch this video
https://www.loom.com/share/ee18667e98f94080873c34831dc2e950

**Comment by hamzakifani** [comment]
we fixed this problem . Please use the latest version 3.0 
Thank you
