### ISSUE TITLE
Project Always Redirecting To Setup Page

### ISSUE THREAD

**Issue by Dilouette** [uilibrary/Stocky-Issues-and-Feature-request#163]
I have purchased stocky and I would like to make some changes to the project by adding an expiry date feature to products.
I have set up the project on Visual Studio Code, 
I created the database,
I set up my env parameters,
I ran `php artisan migrate:fresh --seed`
I ran cleared the config cache

But wen I try to login it always redirects me to the setup page 

I have also tried to restore the db backup that came with the solution I still cant seem to get past the login page

**Comment by hamzakifani** [comment]
Hi , please follow setup installation

**Comment by Dilouette** [comment]
I know what the setup document says.
The setup only details how to deploy for a production environment. I am trying to add some functionality to the solution hence my need to run it using `php artisan serve` from VSCODE without setting up an entire apache server and configuring my host files

**Comment by hamzakifani** [comment]
Step 1: run php artisan migrate:fresh --seed
Step 2: run php artisan passport:install
Step 3: Go to    \storage\app\public     and create a empty file  (installed)

![installed](https://user-images.githubusercontent.com/50219942/123148969-ad061680-d458-11eb-95e4-5113b5fa3a82.PNG)
