### ISSUE TITLE
i wnt to develop this project. how to edit this code

### ISSUE THREAD

**Issue by sanchitha-prasad** [uilibrary/Stocky-Issues-and-Feature-request#164]

**Comment by sanchitha-prasad** [comment]
i want to edit this code

**Comment by hamzakifani** [comment]
Hi ,
Stocky is based in laravel & Vue js

Frontend :
Go to
/resources/src/views/app/pages/

Backend :
Go to
/app/Http/Controllers

After edit code Run :

npm install
npm run watch
npm run prod

We will add developer guide in future .
Thank you

**Comment by sanchitha-prasad** [comment]
Thanks
