### ISSUE TITLE
SQLSTATE[HY000]: General error: 1709 Index column size too large.

### ISSUE THREAD

**Issue by siusang** [uilibrary/Stocky-Issues-and-Feature-request#165]
Hello Team

This is refer to my issue on this comments : https://codecanyon.net/comments/26866513

thank you

**Comment by hamzakifani** [comment]
Hi , 
you have a problem with the mysql version 5.6
Solution: Go to Folder: App\Providers
extract the zip and copy paste  file **AppServiceProvider.php**
[AppServiceProvider.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6716586/AppServiceProvider.zip)

**Comment by hamzakifani** [comment]
Please watch this video 
https://www.loom.com/share/50cf0481d2fd4b269a26a76232340beb

**Comment by siusang** [comment]
> Hi ,
> you have a problem with the mysql version 5.6
> Solution: Go to Folder: App\Providers
> extract the zip and copy paste file **AppServiceProvider.php**
> [AppServiceProvider.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6716586/AppServiceProvider.zip)

Thank you.
I just tried copy paste file AppServiceProvider.php to App\Providers (replace the exist one), but ... it doesn't work, I still got that error message. I've also tried delete the database and create a new one, it not help.. can you login to my FTP and phpMyAdmin to install the app for me? thank you so much.

**Comment by hamzakifani** [comment]
Please send your ftp access via
mr.hamza.kifani@gmail.com
Thank you

**Comment by siusang** [comment]
> Please send your ftp access via
> [mr.hamza.kifani@gmail.com](mailto:mr.hamza.kifani@gmail.com)
> Thank you

email sent, please check, thank you!

**Comment by hamzakifani** [comment]
Hello , 
Your issue is fixed 
https://pos.winsonshop.com/

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by siusang** [comment]
> Hello ,
> Your issue is fixed
> https://pos.winsonshop.com/
> 
> if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

Hello, thank you so much, I'll make a positive rating for your app for sure. 
One more quick question, why there only USD currency can be chose in setting page? can i change it to our currency HKD? thank you.

![qooah-screenshot_2796](https://user-images.githubusercontent.com/86476694/123500881-ce8f1a00-d673-11eb-98c7-c01c2b6a0cfd.jpg)

**Comment by siusang** [comment]
> Hello ,
> Your issue is fixed
> 
> 
> if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

one more thing, can you please edit and delete or make some mask on the URL in your above comment? it is not for public usage, thank you so much.

**Comment by hamzakifani** [comment]
> > Hello ,
> > Your issue is fixed
> > if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
> 
> Hello, thank you so much, I'll make a positive rating for your app for sure.
> One more quick question, why there only USD currency can be chose in setting page? can i change it to our currency HKD? thank you.
> 
> ![qooah-screenshot_2796](https://user-images.githubusercontent.com/86476694/123500881-ce8f1a00-d673-11eb-98c7-c01c2b6a0cfd.jpg)

Yes you can change it . Thank you

**Comment by siusang** [comment]
The installation issue was fixed, so i close this thread, thank you so much.
