### ISSUE TITLE
Label printer for barcode prints?

### ISSUE THREAD

**Issue by Bytepie** [uilibrary/Stocky-Issues-and-Feature-request#166]
I want to update the app to latest version.

**Comment by hamzakifani** [comment]
check doc for upgrade guide. thank you

**Comment by Bytepie** [comment]
okay thanks. can you also recommend label printer for barcode prints. How should they be printed what should be the sticker paper size. I can't find them in docs.

**Comment by Bytepie** [comment]
please also recommend a scanner model.

**Comment by hamzakifani** [comment]
Any barcode scanner should work. Just plug the scanner, hover the mouse cursor on the Barcode scanner input field and scan the barcode. If your scanner can read the product code from barcode correctly then it will work.

**Comment by Bytepie** [comment]
What about label printer? What label printer should I use and what type of
paper should I buy for your format of barcodes in one page in print label.

**Comment by hamzakifani** [comment]
We tested this script with a Tysso thermal printer. So it should work if you set up all the things properly.

**Comment by Bytepie** [comment]
Does it print pos receipts or labels. I need to know about Label/barcode
printing which would be pasted on products for scanning later on. Right now
your print barcode results in a page full of barcodes. Is that the right
format for label printers or do they work on specific label printers?

**Comment by hamzakifani** [comment]
we don't tested barcode printer . Thank you

**Comment by Bytepie** [comment]
Can you please explain this in more detail after testing it. It will help
us understand barcode printing and buy the right barcode printer. Just as
you explained the pos reciept printer in documentation.

**Comment by hamzakifani** [comment]
Fixed
