### ISSUE TITLE
after updating : white pages

### ISSUE THREAD

**Issue by bahaajaw** [uilibrary/Stocky-Issues-and-Feature-request#170]
hello, this is first time i update stocky , i am not  expert on web hosting , i have web hosted at hostinger ,  i had version 2.5 and i did back up then went to download 3.0 , i tried to copy new specifed  file server says files already exits so i had to replace them with 3.00 only require files ,then went mysite/update then cleard cache , there is no button to restart the server its says server automatically get changed, i went to stocky , still not updated , i can't access any page on stocky its white page , help plesae 
![image](https://user-images.githubusercontent.com/86600641/123620389-d802b880-d812-11eb-8291-b734df9ed0cb.png)

**Comment by hamzakifani** [comment]
Please contact via: uilib.help@gmail.com with your cpanel access. Thank you

**Comment by bahaajaw** [comment]
since i am using hpanel not cpanel , i trust you to access my website
https://hpanel.hostinger.com/
***@***.***
Mm0595455057***
please be quick since i am working on it as primary thing

**Comment by hamzakifani** [comment]
Send us your access . Thank you

**Comment by hamzakifani** [comment]
Or just your app access to iqraa.link

Le lun. 28 juin 2021 à 13:52, hamza kifani ***@***.***> a
écrit :

> Send us your access . Thank you
>
> Le lun. 28 juin 2021 à 13:45, bahaajaw ***@***.***> a
> écrit :
>
>> since i am using hpanel not cpanel , i trust you to access my website
>> https://hpanel.hostinger.com/
>> ***@***.***
>> Mm0595455057***
>> please be quick since i am working on it as primary thing
>>

**Comment by hamzakifani** [comment]
Or just your app access to iqraa.link

**Comment by bahaajaw** [comment]
***@***.***
adminadmin
Database should be fine

**Comment by hamzakifani** [comment]
please send us your hpanel and your app access so we can help you .

**Comment by bahaajaw** [comment]
I have sent my hpanel,access to the app at your gmail ulbi help , plz check
out fast

**Comment by hamzakifani** [comment]
Hi , 
you have done the update process well 
you are just a problem of browser cash please empty your browser cache

Please show this video
https://www.awesomescreenshot.com/video/4288865

**Comment by bahaajaw** [comment]
This is  werid I have tried othér computer,also phone I can't access
anything , same thing , also the link you provide not working

**Comment by hamzakifani** [comment]
Please Show this video

https://www.awesomescreenshot.com/video/4288865?key=e73cae3dc69bc142f1082f049f7ccc06

**Comment by bahaajaw** [comment]
issued still not fixed ,seems software still stored my ip addresses , cache files , i have tried to go incognito mode on phone with same network not working , i tried other network with incognito mode its work , i have to detete stored information on code how i can delete them

**Comment by bahaajaw** [comment]
if i ask someone to visit my website its working , but in my own its not working

**Comment by hamzakifani** [comment]
your hpanel access is invalid please send us your hpanel we will fix your issue .

**Comment by hamzakifani** [comment]
if you need clear cache of your app



Go to  \storage\framework\cache\
and delete all files or folder Delete all files or folder except bellow on image

![cache](https://user-images.githubusercontent.com/50219942/123701354-a6611000-d859-11eb-9873-c78bbb4fe799.PNG)

Go to \storage\framework\views\

and delete all files or folder Delete all files 
![views](https://user-images.githubusercontent.com/50219942/123701613-fcce4e80-d859-11eb-88f8-3edad5acf057.PNG)


\storage\framework\sessions\

![sessions](https://user-images.githubusercontent.com/50219942/123701672-0e175b00-d85a-11eb-8c97-848928d8db67.PNG)

**Comment by bahaajaw** [comment]
i tried its same thing , i don't know what to do

**Comment by hamzakifani** [comment]
are you cleared browser cache ??

**Comment by bahaajaw** [comment]
Yes, I did. , I even working on incognito, can you please access my hpanel
Rebuild the software , we still have the database , please help

**Comment by hamzakifani** [comment]
Your hpanel access is invalid ???

**Comment by bahaajaw** [comment]
No, it's not. ، wait I will try to access hpanel

**Comment by bahaajaw** [comment]
I logged out

**Comment by hamzakifani** [comment]
i can't access your hpanel 
![hpanel](https://user-images.githubusercontent.com/50219942/123710663-0e6a2300-d867-11eb-9951-2ec04336451f.PNG)

**Comment by bahaajaw** [comment]
Do you have a way to talk like chat
I just tried and its work
I sent information again

**Comment by hamzakifani** [comment]
my skype
![skype](https://user-images.githubusercontent.com/50219942/123711697-cc41e100-d868-11eb-9d80-ba4d1b3fdfd9.PNG)
