### ISSUE TITLE
Request for warehouse permission per user or role

### ISSUE THREAD

**Issue by alifpramanarasa** [uilibrary/Stocky-Issues-and-Feature-request#179]
I think its made more amazing if it can handle warehouhse permission for user/role

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by kashifleo55** [comment]
This is very important point please must be added. Thanks

**Comment by hamzakifani** [comment]
This feature added in latest version v4.0
