### ISSUE TITLE
Feature request: Variations in products

### ISSUE THREAD

**Issue by tjmthome** [uilibrary/Stocky-Issues-and-Feature-request#180]
Hi guys
A) I think that adding the possibility of product variations, will be very useful for Stocky, I mean if a store offer shoes or clothes, they have same product (model), but with variations in sizes and colors

**Comment by hamzakifani** [comment]
Hi .
we have already Product variants . you can check demo in the right of adding product 
![122580794-3dee8380-d04e-11eb-8c6e-b07662e33a52](https://user-images.githubusercontent.com/50219942/123853338-4039c300-d915-11eb-84e7-68ac7e4a9cac.png)

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
