### ISSUE TITLE
error en npm run dev

### ISSUE THREAD

**Issue by MarcelCH** [uilibrary/Stocky-Issues-and-Feature-request#182]
Dears,

I have executed npm run dev and i getting
ERROR in ./resources/js/assets/styles/sass/themes/lite-purple.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: It's not clear which file to import. Found:
  resources\js\assets\styles\sass\globals\_globals.scss
  resources\js\assets\styles\sass\globals\globals.scss
why?
also it file globals.scss is empty why?

the same error with npm run prod.

**Comment by MarcelCH** [comment]
the same with npm run prod.

**Comment by hamzakifani** [comment]
please change css in resources\js\assets\styles\sass\globals\_globals.scss

**Comment by hamzakifani** [comment]
resources\js\assets\styles\sass\globals\_globals.scss
