### ISSUE TITLE
How to connect external barcode scanner machine?

### ISSUE THREAD

**Issue by waelamad** [uilibrary/Stocky-Issues-and-Feature-request#191]
We need to connect barcode scanner machine to be connected with the website POS, so instead of selecting the products and adding them to the cart manually, the salesman can just use the barcode scanner to read the items and the POS cart system updated with the the selected scanned products automatically.
How we can do that?

**Comment by hamzakifani** [comment]
Just plug the scanner, hover the mouse cursor on the barcode scanner text field and scan the barcode. If your scanner can read the product code from barcode correctly then it will work.

**Comment by waelamad** [comment]
> This script is compatible with barcode scanners. Just plug the scanner, hover the mouse cursor on the barcode scanner text field and scan the barcode. If your scanner can read the product code from barcode correctly then it will work.

OK, thanks, what about if I am using My mobile as reader for barcode, I try it just right now but not connecting and not recognizing the barcode?

**Comment by hamzakifani** [comment]
Hello,

The only requirement for barcode scanners/readers is that they must send return command after typing the codes. If your barcode scanner does this, you are ready to use it with this script. Just focus the barcode scanner input and start scanning. If you already have one, you are try it on demo.

Thank you
