### ISSUE TITLE
Adding Product variant results in incomplete barcode image.

### ISSUE THREAD

**Issue by Bytepie** [uilibrary/Stocky-Issues-and-Feature-request#192]
I think you should start testing barcode printing.
Barcode printing is unclear and not mention in documentation. Moreover it sometimes go beyond the bounds and results in faulty unreadable barcode as you can below.

![fault](https://i.imgur.com/LurcUCp.png)

**Comment by hamzakifani** [comment]
We will fix this bug in next update . Thank you

**Comment by hamzakifani** [comment]
Fixed
