### ISSUE TITLE
Barcode printing Format for Label Rolls and Label Printer

### ISSUE THREAD

**Issue by Bytepie** [uilibrary/Stocky-Issues-and-Feature-request#193]
Please Add Barcode printing formats for Label Rolls and Label Printer. Right now you have to print a full page document on a sticker paper and cut each barcode sticker separately which is a tedious task and not efficient. It also waste the remaining sheet.

**Comment by hamzakifani** [comment]
We will fix it . Thank you

**Comment by hamzakifani** [comment]
Hi , 
is the size paper correct? 
![sheet](https://user-images.githubusercontent.com/50219942/124342776-561de100-dbbe-11eb-882c-9d8dc3c98917.PNG)

**Comment by Bytepie** [comment]
Yes Smaller is better. I prefer the first two 1.799x1.003 and 2.625 x 1.
It would be beneficial if you add multiple formats. In one of the pos at
codecanyon they have multiple formats. I am not sure how to test these on a
barcode/label printer. The way I understand them I think they accept
continuous format for printing like in pos reciept printer.

**Comment by hamzakifani** [comment]
please add me on skype to test with you the printing barcode /labels

![Screenshot_2021-07-04-00-49-45-290_com skype raider](https://user-images.githubusercontent.com/50219942/124369268-e06b5100-dc61-11eb-94e4-c357c79d5b83.jpg)

**Comment by hamzakifani** [comment]
Fixed

**Comment by hamzakifani** [comment]
Ok
