### ISSUE TITLE
corrections in spanish translation file

### ISSUE THREAD

**Issue by tjmthome** [uilibrary/Stocky-Issues-and-Feature-request#194]
Corrections to file stocky/resources/src/translations/locale/es.js

line 169 says:   AlreadyAdd: "Questo prodotto è già stato aggiunto",
must say:        AlreadyAdd: "Este producto ya ha sido agregado",

line 170 says:   AddProductToList: "Si prega di aggiungere il prodotto all'elenco",
must say:        AddProductToList: "Agregue un producto a la lista",

line 171 says:   AddQuantity: "Si prega di aggiungere la quantità",
must say:        AddQuantity: "Agregue la cantidad",

line 172 says:   InvalidData: "Dati non validi",
must say:        InvalidData: "Fecha inválida",

line 174 says:   WarehouseIdentical: "I due repository non possono essere identici",
must say:        WarehouseIdentical: "Los almacenes no pueden ser iguales",

line 175 says:   VariantDuplicate: "Questa variabile è ridondante",
must say:        VariantDuplicate: "Esta variante está duplicada",

line 260 says:   Close: "Cerca",
must say:        Close: "Cerrar",

line 413 says:   PleaseSelectStatut: "seleccione Statut",
must say:        PleaseSelectStatut: "seleccione estado",

line 419 says     submit: "someter",
must say:         submit: "guardar",

line 616 says:    SelectPeriod: "Seleccionar período",
must say:         SelectPeriod: "Seleccionar periodo",

line 618 say:     ThisToday: "Esto hoy",
must say:         ThisToday: "hoy",

[es.js.txt](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6750299/es.js.txt)

**Comment by hamzakifani** [comment]
Thank you for you help
