### ISSUE TITLE
Add Feature-request

### ISSUE THREAD

**Issue by Robelrana** [uilibrary/Stocky-Issues-and-Feature-request#195]
how to add warranty option for electronics item and show product image size for add image box

**Comment by hamzakifani** [comment]
unfortunately we did not understand your need .
please explain your need so that we can help you 
Thank you

**Comment by Robelrana** [comment]
i am sell  electronics item how can i add in invoice  warranty option

**Comment by Robelrana** [comment]
i am sell electronics item how can i add in invoice warranty option

**Comment by hamzakifani** [comment]
you want to print the number of years warranty on the invoice if the product got any warranty ??

**Comment by Robelrana** [comment]
yes

**Comment by hamzakifani** [comment]
Great . We will add this option in next update . 
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
This feature has been added in latest version
