### ISSUE TITLE
change /app/ to the other name without put code to subfolder

### ISSUE THREAD

**Issue by sam2909** [uilibrary/Stocky-Issues-and-Feature-request#196]
I'd like to change /app in mydomain/app to the other example mydomain/myapp. So what files which need to edit to do that.
Thanks team.

**Comment by hamzakifani** [comment]
Unfortunately, we did not understand exactly what you need, but I think you can not do this thing from our application, try to go to your host and explain about it .
Thank you

**Comment by sam2909** [comment]
I had complete setup my application at url: http://mydomain.com/app/dashboard.

I need to change to http://mydomain.com/MYAPP/dashboard without put my code to subfolder.

I think that I need to change some files, I tried to ask at codecanyone, and your team said that I need to make an request from github.

Thanks.

**Comment by hamzakifani** [comment]
Hi,
Please watch this video
https://www.awesomescreenshot.com/video/4364919?key=26b4420d17a04118ce918302f8309704

**Comment by sam2909** [comment]
> Hi,
> Please watch this video
> https://www.awesomescreenshot.com/video/4364919?key=26b4420d17a04118ce918302f8309704

Hi,

Many many .... thanks about your support.

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by sam2909** [comment]
> if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

okie, sure I'll leave a feedback with excellent support.
