### ISSUE TITLE
Problem in Xampp installation Reason, did not follow setup guide correctly 

### ISSUE THREAD

**Issue by naime-hossain** [uilibrary/Stocky-Issues-and-Feature-request#20]
Error if  run the script with php artisan serve command 
![image](https://user-images.githubusercontent.com/12586039/115118155-cd7ea400-9fc3-11eb-8da6-875a99e79ac2.png)

**Comment by naime-hossain** [comment]
Fix : 
If you use php artisan serve you have to type the command `php artisan config: clear` after `php artisan serve` , or you can use Xampp and follow the installation guide or use Laragon https://laragon.org/ . thank you hope this will fix the issue.

**Comment by mathonw** [comment]
i am using xampp server

**Comment by naime-hossain** [comment]
> i am using xampp server

Follow the localhost  installation  guide from doc

**Comment by mathonw** [comment]
![image](https://user-images.githubusercontent.com/22096987/115118935-1e7f9f80-9fa6-11eb-8dbd-bd5d33d29e6d.png)

**Comment by naime-hossain** [comment]
Please follow these step : https://stocky.ui-lib.com/documentation/index.html
![image](https://user-images.githubusercontent.com/12586039/115119015-1e909700-9fc8-11eb-8c1e-b9f3ade7b747.png)

**Comment by mathonw** [comment]
![image](https://user-images.githubusercontent.com/22096987/115119102-fcd2e800-9fa6-11eb-913c-34c56d185b2b.png)
already done that

**Comment by naime-hossain** [comment]
in your screenshot, the URL is not stocky.local but this 
![image](https://user-images.githubusercontent.com/12586039/115119140-b2faf980-9fc8-11eb-9c19-38d16b1de6f1.png)
why >

**Comment by mathonw** [comment]
![image](https://user-images.githubusercontent.com/22096987/115119220-8be00000-9fa7-11eb-9dd8-40cdbf02dda8.png)

**Comment by mathonw** [comment]
![image](https://user-images.githubusercontent.com/22096987/115119353-36f0b980-9fa8-11eb-9826-4809702d67b5.png)

**Comment by hamzakifani** [comment]
i ts working ?

**Comment by mathonw** [comment]
yes

**Comment by naime-hossain** [comment]
Please remove the current files and start with the new zip you downloaded from codecanyon and then follow the installation. if still have the let us know. thank you

**Comment by hamzakifani** [comment]
ok congratulations , let us know if you have any issue

**Comment by naime-hossain** [comment]
> yes

Great Job. if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by mathonw** [comment]
default logins admin@example.com?

**Comment by hamzakifani** [comment]
> default logins [admin@example.com](mailto:admin@example.com)?

yes

**Comment by mathonw** [comment]
not going through

**Comment by mathonw** [comment]
![image](https://user-images.githubusercontent.com/22096987/115119504-f7769d00-9fa8-11eb-9499-f89aa08c41e6.png)

**Comment by naime-hossain** [comment]
admin@example.com
123456

by the way what was your first problem, the URL right?

**Comment by mathonw** [comment]
first problem url but now psw not ging through

**Comment by hamzakifani** [comment]
Please remove the current files and start with the new zip you downloaded from codecanyon and then follow the installation.

**Comment by mathonw** [comment]
re-install?

**Comment by hamzakifani** [comment]
yes

**Comment by mathonw** [comment]
Thanks all is well now

**Comment by naime-hossain** [comment]
Great Job. if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items  Your review will motivate us thank you

**Comment by naime-hossain** [comment]
> Thanks all is well now

Great. if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & reviews please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Your review will motivate us. thank you

**Comment by mehrab-amin-01** [comment]
@mathonw how you solved the setup page problem?

**Comment by mathonw** [comment]
Yes
