### ISSUE TITLE
Weight scale product label barcode scan

### ISSUE THREAD

**Issue by kashifleo55** [uilibrary/Stocky-Issues-and-Feature-request#210]
Hi,
    Please add the feature for weighing scale product like if we are using weight scale that print label according to product weight if we scan that barcode on POS its should recognize the product and weight from that barcode and add product to cart according to weight. That is very important point for POS for custom weight products. Thanks

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by kashifleo55** [comment]
Barcode scan is available that's working fine butt the issue is bar code san does not recognize the product code and and weight from weight scale label please add this feature this is very important for custom weight items. Thanks
