### ISSUE TITLE
Not showing product on POS system

### ISSUE THREAD

**Issue by mukurr** [uilibrary/Stocky-Issues-and-Feature-request#211]
I have an add a product, but it's not showing on my POS system. Could you please tell me how I can add a product to the POS system?

**Comment by hamzakifani** [comment]
Hi. To add sale you have to purchase the product first. Because the sales comes when you have stock.

So purchase that product first. Then you can make Sale.

create purchase via http://stocky.ui-lib.com/app/purchases/store 

Thank you

**Comment by mukurr** [comment]
Thanks for your reply. I can make purchases, I can make sales. But I can't see my products on my POS system. I mean here https://stocky.ui-lib.com/app/pos

I'm really sorry if I asked a dummy question.

**Comment by hamzakifani** [comment]
Please check if product has stock

**Comment by mukurr** [comment]
Thank you so much!

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
