### ISSUE TITLE
I want to help you in Arabic Translation

### ISSUE THREAD

**Issue by waelamad** [uilibrary/Stocky-Issues-and-Feature-request#213]
Dears,
I purchased your great software, I want to participate and help you **for free** to develop the software. 
Since I am Native Arabic Language speaker, so I want to advise you with better translation, How I can do that?

Best regards
Wael

**Comment by hamzakifani** [comment]
Hi , 
Thank you for your help , 
Please send us the file like this https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues/194

**Comment by waelamad** [comment]
Hi, The modified file attached
Best regards

[ar.js.txt](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6765771/ar.js.txt)

**Comment by hamzakifani** [comment]
we will fix it in next update . thank you
