### ISSUE TITLE
Problem with Backup, mail and mobile phone and other things

### ISSUE THREAD

**Issue by waelamad** [uilibrary/Stocky-Issues-and-Feature-request#215]
Dear sirs,
I installed your software the latest version, while I found that:

1. Automatic Backup is not working, once I click on the Backup of DB nothing happened. Could you please check it for me and solve the issue.
2. Another Problem, once we open the software using mobile phone, it is very much slow to open (Speed 1mb per sec), how we can make it much faster on mobile? Is there any Cache for it?
3. Password reset utility is not working, it gives us SMTP error, while I have entered the user name, password, port number, TLS and mail server, but still not working.
4. Search utility is only searching the letters of first word of any product, NOT any part of the name product? How we can make search within the whole phrase of the product.
5. I have one issue I could not understand: What do we mean by products multiple variants (what is the benefits of it, for what I can use it?).
6. I made some modifications to the Arabic translation file, but once I upload it to the directory resources/src/translations/locales , and delete the stored Temporarily memory, new translations were not reflected to the system. 

 
Could you please check it once for me and help.
 
Best regards
Wael

**Comment by hamzakifani** [comment]
Hello wael , 

I upgraded your app to v3.3

1) Automatic Backup is not working : it's not issue but your server disabled function "exec()"
for that the generate backup not working but you can use method 2 via phpMyAdmin . 
I genereted your backup via phpMyAdmin I copy it to the /storage/app/public/backup , save it to your pc . 
Please follow docs to show how can you export database

2) App slow in mobile : our app is based in laravel & vue js (single page) it's very faster. check your connection or maybe your hosting slow

3) SMTP error : working now , I fixed this issue by changing tls to ssl

4) Searching product : it's solved now with v3.3 

5) product variant : if your product has variant (size , color ...)

**Comment by naime-hossain** [comment]
Your issue is fixed :) if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & reviews please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
