### ISSUE TITLE
Arabic and RTL as default?

### ISSUE THREAD

**Issue by hs777it** [uilibrary/Stocky-Issues-and-Feature-request#218]
How can I set RTL and Arabic as a Default ? Also How Can I remove Languages Icon and RTL/Dark Mode Icon from Your Script? Thanks

**Comment by hamzakifani** [comment]
Hi , 
RTL and Arabic set in LocalStorage 
Do you know Vue js ? 
so Go to \resources\src\components\common\customizer.vue

**Comment by hs777it** [comment]
hamzakifani please:
I want to Make RTL as default 
also Arabic lang as default 

please help me 

 ustomizer.vue hasn't anything to set default lang or layout

**Comment by mohamad19941994** [comment]
To make RTL fefault just edit this file (resources/src/store/modules/config.js) line 8, change it to true value.
That's work with me
