### ISSUE TITLE
Send Invoice To Customer Through Mail

### ISSUE THREAD

**Issue by mukurr** [uilibrary/Stocky-Issues-and-Feature-request#219]
Hi! Can I send an invoice to my customer via Email from the POS system? If yes, then how can I do that?

Thanks in advance

**Comment by hamzakifani** [comment]
Hi , 
Please watch this video 
https://www.awesomescreenshot.com/video/4382623?key=685a6d14753b4b38956c0449190bf401
Thank you

**Comment by deansga** [comment]
hi I am having this same problem as the SMTP error keeps appearing for me.

My SMTP details are entered correctly as the forgot password works fine.  But I can't send invoice or purchases.

Any help will be appreciated?

**Comment by hamzakifani** [comment]
If still this issue .

> hi I am having this same problem as the SMTP error keeps appearing for me.
> 
> My SMTP details are entered correctly as the forgot password works fine. But I can't send invoice or purchases.
> 
> Any help will be appreciated?

Please contact via : uilib.help@gmail.com with your cpanel + app access . Thank you
