### ISSUE TITLE
Code showing error on VScode.. although all is working fine

### ISSUE THREAD

**Issue by Stridesdata** [uilibrary/Stocky-Issues-and-Feature-request#22]
![image](https://user-images.githubusercontent.com/82326559/115124462-4416a400-9fba-11eb-9c1b-83b4ad42c3ab.png)

There is this error on vs code asking for key

**Comment by hamzakifani** [comment]
this is not an error it is just the new versions VsCode need a v: key by the way  not important, thank you

**Comment by naime-hossain** [comment]
> this is not an error it is just the new versions VsCode need a v: key by the way not important, thank you

@hamzakifani  We can use  :key="detail_invoice.name" as key binding to resolve the warning.

**Comment by Stridesdata** [comment]
slot-scope deprecated. Can we change it to the new v-slot attribute?

**Comment by naime-hossain** [comment]
> slot-scope deprecated. Can we change it to the new v-slot attribute?

On which page did you get it? thank you

**Comment by Stridesdata** [comment]
![image](https://user-images.githubusercontent.com/82326559/116536186-873b1600-a8dc-11eb-93a1-45f72be71881.png)

Its almost every where

**Comment by naime-hossain** [comment]
These are warning not errors. it's for code editor setting may be. thank you
