### ISSUE TITLE
Currency symbol not updating

### ISSUE THREAD

**Issue by kashifleo55** [uilibrary/Stocky-Issues-and-Feature-request#221]
1- Currency symbol not updating on POS screen in discount and shipping fields
2- In Admin side discount and shipping fields of add/edit Sale, Quotation, Purchase, Transfer, Sale return, Purchase return.

**Comment by hamzakifani** [comment]
1) currency symbol just icon .
2) this option already is available

**Comment by kashifleo55** [comment]
![image](https://user-images.githubusercontent.com/12426582/124900068-275a9d00-dffa-11eb-9438-2d71324e088c.png)

I am talkin about these currency symbols these are not changes these symbol are static make it dynamic as others. Thanks
1- Currency symbol not updating on POS screen in discount and shipping fields
2- In Admin side discount and shipping fields of add/edit Sale, Quotation, Purchase, Transfer, Sale return, Purchase return.

**Comment by hamzakifani** [comment]
Issue fixed
