### ISSUE TITLE
Profits 

### ISSUE THREAD

**Issue by Johnson-Ichangai** [uilibrary/Stocky-Issues-and-Feature-request#226]
Hello, let me first begin by thanking you for the amazing work you've done on this system. It has really been of help. However, there's just one issue I noticed that I think would be pertinent to address it. It regards the Profit spectrum. The system does not accurately depict or reflect the profit. On the dashboard, the sales are the same as profit. The profit is supposed to be (product cost - final product price). For example, a pair of jeans cost $10, and the final price is $15. If I sell it, the dashboard should display sales as $15, and the profit as $5. However, the dashboard is displaying sales as $15 and profit as $15.

**Comment by Johnson-Ichangai** [comment]
I am a junior programmer, and I understand Laravel a bit. If you could point me out to where I can rectify that, I will highly, highly, highly, highly appreciate it, very very much. Aside from that, this system is just amazing and really awesome. It's the best and I've recommended three of my friends to purchase it.

**Comment by hamzakifani** [comment]
> Hello, let me first begin by thanking you for the amazing work you've done on this system. It has really been of help. However, there's just one issue I noticed that I think would be pertinent to address it. It regards the Profit spectrum. The system does not accurately depict or reflect the profit. On the dashboard, the sales are the same as profit. The profit is supposed to be (product cost - final product price). For example, a pair of jeans cost $10, and the final price is $15. If I sell it, the dashboard should display sales as $15, and the profit as $5. However, the dashboard is displaying sales as $15 and profit as $15.

we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
> I am a junior programmer, and I understand Laravel a bit. If you could point me out to where I can rectify that, I will highly, highly, highly, highly appreciate it, very very much. Aside from that, this system is just amazing and really awesome. It's the best and I've recommended three of my friends to purchase it.

If want edit code 
Go to /app/Http/Controllers/ReportController.php

Thank you

**Comment by Johnson-Ichangai** [comment]
Hello, I'm really grateful that you found time and responded to my query. Much appreciated. Let me once again kindly ask for your assistance.  Fortunately, I found that you were calculating profit the right way under Shop Report (Value by Cost and Price). I want to also have expenses there. So currently it's (Price - Cost). I want it to be (Price - cost - expense). I'm having a challenge referencing the expense from the database. 

Currently its
`
public function Warhouse_Count_Stock(Request $request)
    {
        $this->authorizeForUser($request->user('api'), 'WarehouseStock', Product::class);

        $stock_count = product_warehouse::join('products', 'product_warehouse.product_id', '=', 'products.id')
            ->join('warehouses', 'product_warehouse.warehouse_id', '=', 'warehouses.id')
            ->where('product_warehouse.deleted_at', '=', null)
            ->select(
                DB::raw("count(DISTINCT products.id) as value"),
                DB::raw("warehouses.name as name"),
                DB::raw('(IFNULL(SUM(qte),0)) AS value1'),
            )
            ->where('qte', '>', 0)
            ->groupBy('warehouses.name')
            ->get();

        $stock_value = product_warehouse::join('products', 'product_warehouse.product_id', '=', 'products.id')
            ->join('warehouses', 'product_warehouse.warehouse_id', '=', 'warehouses.id')
            ->where('product_warehouse.deleted_at', '=', null)
            ->select(
                DB::raw("SUM(products.price) as price"),
                DB::raw("SUM(products.cost) as cost"),
                DB::raw("warehouses.name as name"),
            )
            ->where('qte', '>', 0)
            ->groupBy('warehouses.name')
            ->get();

        $data = [];
        foreach ($stock_value as $key => $value) {
            $item['name'] = $value->name;
            $item['value'] = $value->price;
            $item['value1'] = $value->cost;
            $item['value2'] = $value->price - $value->cost;
            $data[] = $item;
        }
`

**Comment by Johnson-Ichangai** [comment]
Please assist me in referencing the expense table so I can be able to calculate the profit more accurately. Any help will be highly appreciated.
(I don't know how to join the expense table, I'm still new to programming. I know I'll have
 $item['expense'] = $value-> expense
 $item['value2'] = $value -> price - $value->cost)

**Comment by hamzakifani** [comment]
Expense::with('warehouse')->get();

**Comment by Johnson-Ichangai** [comment]
Hello, thanks for the super lightning-fast response. That's awesome. Please assist me again, where will I place the code (Expense::with('warehouse')->get();) I will highly appreciate if you could demonstrate for me. Thanks again

**Comment by Johnson-Ichangai** [comment]
Hello Hamzakifani, I apologize for being so inquistive, but I really need
your help. Ive tried raising the issue again, I tried commenting on my
issue but you haven't responded. I'm kindly requesting you help me. Where
do I place the code  ****Expense::with('warehouse')->get();****
