### ISSUE TITLE
Currency Symbol not update on some sections

### ISSUE THREAD

**Issue by kashifleo55** [uilibrary/Stocky-Issues-and-Feature-request#229]
![123456](https://user-images.githubusercontent.com/12426582/125067206-60177680-e0cd-11eb-8c27-21b5e9950dd5.png)

 These currency symbols these are not changes these symbol are static make it dynamic as others. Thanks
1- Currency symbol not updating on POS screen in discount and shipping fields
2- In Admin side discount and shipping fields of add/edit Sale, Quotation, Purchase, Transfer, Sale return, Purchase return.

**Comment by hamzakifani** [comment]
This issue fixed . Please upgrade to latest version v3.3.2 . Thank you

**Comment by kashifleo55** [comment]
Thanks
