### ISSUE TITLE
Can't Sign In to the move to dashboard -> PHP 8 version not supported yet 

### ISSUE THREAD

**Issue by blinipdk** [uilibrary/Stocky-Issues-and-Feature-request#23]
I'm using the system through artisan serve and it doesn't let me sign in or reset password. 
![image](https://user-images.githubusercontent.com/79044976/115158675-a5f50d80-a08f-11eb-9f56-b6bcb512bda0.png)
It just stays like this it doesn't take any action.
![image](https://user-images.githubusercontent.com/79044976/115158696-cc1aad80-a08f-11eb-8cc5-c4486c395f73.png)

**Comment by hamzakifani** [comment]
Hi . For now php 8 not compatible . please use php 7.3 or 7.4 . the next update will support php 8 . thank you

**Comment by naime-hossain** [comment]
Please check this issue # https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues/21
if still won't solve your issue then let us know 
Thank you
