### ISSUE TITLE
npn run dev / prod take time 

### ISSUE THREAD

**Issue by kashifleo55** [uilibrary/Stocky-Issues-and-Feature-request#242]
![image](https://user-images.githubusercontent.com/12426582/125079927-9d840000-e0dd-11eb-89a1-53e50aa326b6.png)

At this point it takes to much time to compile any suggesting? Thanks

**Comment by kashifleo55** [comment]
Also please guide me on this. bundle of thanks
![image](https://user-images.githubusercontent.com/12426582/125084936-7d573f80-e0e3-11eb-978c-34fb6a844fff.png)

**Comment by hamzakifani** [comment]
Hi ,
You can remove this plugin from webpack . This plugin for transcompiling final bundles so they support legacy browsers
Please watch this video
https://www.loom.com/share/5996281ca03a4380b9fa4103b5f3e9d0
 .thank you

**Comment by hamzakifani** [comment]
> Also please guide me on this. bundle of thanks
> ![image](https://user-images.githubusercontent.com/12426582/125084936-7d573f80-e0e3-11eb-978c-34fb6a844fff.png)

Go to /ressources/src/main.js
![Screenshot_2021-07-09-19-12-03-457_com android chrome](https://user-images.githubusercontent.com/50219942/125119927-a8dd2880-e0e9-11eb-95fc-d056759b99af.jpg)

And set Vue.config.devtools = true;

**Comment by kashifleo55** [comment]
Thanks

**Comment by naime-hossain** [comment]
If you like our item and support you can rate it . If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Thank you
