### ISSUE TITLE
POS Duplicate receipt 

### ISSUE THREAD

**Issue by kashifleo55** [uilibrary/Stocky-Issues-and-Feature-request#243]
If first time receipt print missed due to any reason on POS how can we print duplicate receipt? Thanks

**Comment by hamzakifani** [comment]
there is a button below "print".  or you can also go to sales section and click to "invoice pos"

![Screenshot_2021-07-09-19-06-51-651_com android chrome](https://user-images.githubusercontent.com/50219942/125119520-1e94c480-e0e9-11eb-96b9-11a945f0ded5.jpg)

![Screenshot_2021-07-09-19-07-14-413_com android chrome](https://user-images.githubusercontent.com/50219942/125119531-23597880-e0e9-11eb-8c94-5e13cba3b7b3.jpg)

**Comment by kashifleo55** [comment]
Awesome, Thanks
