### ISSUE TITLE
When i click save button more than one times at a time same data also saved more than one times

### ISSUE THREAD

**Issue by sureshksundar** [uilibrary/Stocky-Issues-and-Feature-request#244]
When i click save button more than one times at a time same data also saved more than one times

**Comment by hamzakifani** [comment]
We will fix this issue . Thank you

**Comment by hamzakifani** [comment]
This issue fixed . Please upgrade to latest version v3.3.2 . Thank you

**Comment by sureshksundar** [comment]
Sorry, the issue is not fixed, please see below attachment video.

Regards,

S.SURESHKUMAR.
(+91-9976880192)
