### ISSUE TITLE
Urgent Please. Number of decimal digits in purchases and products prices and costs

### ISSUE THREAD

**Issue by waelamad** [uilibrary/Stocky-Issues-and-Feature-request#246]
Dear,
Our suppliers provide us with products invoices with prices such as: USD253.98745625865
11 decimal digits.
While in purchase orders, I found it approximate the number to the last three decimals only. How I can configure to add the exact cost, because it gives us difference in Grand Totals between us and the suppliers. 

Best regards
Wael

**Comment by hamzakifani** [comment]
We will check this issue . Thank you

**Comment by hamzakifani** [comment]
I checked this issue , all is well , the calculation is correct , but is showing just three decimals only .
Please watch this video 
Thank you

https://www.awesomescreenshot.com/video/4445727?key=5eb074896bcd6cd899d5956312a675bc
