### ISSUE TITLE
Problem: Barcode Scanner Can not recall the product!!

### ISSUE THREAD

**Issue by waelamad** [uilibrary/Stocky-Issues-and-Feature-request#247]
Dear sirs,
When we use barcode scanner on the product, it add the product to the client order only if the product is displayed on the right view page, But suppose the product is on page 5, and the view of products are on page 1, scanner can not recall the product and can not add it to the client order.

I attached the video to explain the issue.
I how you can fix that bug please.
Wael

https://user-images.githubusercontent.com/86734372/125202881-66992000-e27e-11eb-8328-1c1f82e704a6.mp4

**Comment by hamzakifani** [comment]
we fixed the bug .we will launch new release tomorrow . thank you

**Comment by hamzakifani** [comment]
This issue fixed . Please upgrade to latest version v3.3.2 . Thank you
