### ISSUE TITLE
Error on POS

### ISSUE THREAD

**Issue by kashifleo55** [uilibrary/Stocky-Issues-and-Feature-request#248]
When we search any product on POS screen and hit enter key product not filtered according to keyword search its show error in console please fix this ASAP. Thanks
![image](https://user-images.githubusercontent.com/12426582/125284540-fdbfaf80-e332-11eb-9ba1-1fc544915657.png)

**Comment by hamzakifani** [comment]
Please upgrade to latest version v3.3.2 . Thank you

**Comment by kashifleo55** [comment]
Thanks

**Comment by kashifleo55** [comment]
Issue not resolved still exist in 3.3.2

when write name of product in search bar and and press enter for search its show error in  console and does not search product. please resolve its asap. Thanks
