### ISSUE TITLE
import products from csv with arabic language

### ISSUE THREAD

**Issue by a7m13** [uilibrary/Stocky-Issues-and-Feature-request#249]
import products from csv with arabic language also need to save the csv with utf-8 coding please fix the issue

**Comment by a7m13** [comment]
cannot import!

**Comment by hamzakifani** [comment]
Check this issue . https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues/74

**Comment by a7m13** [comment]
why this problem occur?
