### ISSUE TITLE
login 

### ISSUE THREAD

**Issue by abdfarisy** [uilibrary/Stocky-Issues-and-Feature-request#250]
hi
Incorrect Login .. when I got out and then tried to get in

**Comment by hamzakifani** [comment]
are you chenged  email or password ?

**Comment by abdfarisy** [comment]
no

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your app access

**Comment by hamzakifani** [comment]
Issue fixed 
we have reset the password by default 123456. 
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
