### ISSUE TITLE
Backup Issue

### ISSUE THREAD

**Issue by mustercorder** [uilibrary/Stocky-Issues-and-Feature-request#251]
Hi, there 
I'm having issues with generating backup.
Can you guys help me to generate a backup and restoring it with a fresh installation

![Screenshot_17](https://user-images.githubusercontent.com/83014495/125363283-2e830180-e392-11eb-819f-10b83f0052c6.png)
.

**Comment by hamzakifani** [comment]
Hi ,
Please check doc http://stocky.ui-lib.com/documentation/index.html

Thank you

**Comment by mustercorder** [comment]
There is a bug I'm having an issue with generating backup. You can see in my screenshot there is no file.

**Comment by mustercorder** [comment]
Dear one more thing I dont use cPanel . I use cloud vps. Can you please provide my commends for centos ssh command?

**Comment by hamzakifani** [comment]
> There is a bug I'm having an issue with generating backup. You can see in my screenshot there is no file.

It's no bug . There a exec() function desabled in your server . 
But you can use Method 2 to export your backup .
So go to you phpMyAdmin and follow the steps in doc
Thank you

**Comment by mustercorder** [comment]
How can I enable the function ?

**Comment by hamzakifani** [comment]
exec function is usually disabled in a server, as it allows attackers to execute external programs that can crack a server.

You can enable the “shell_exec()” function from below steps:

> For that login to WHM.
> Click on MultiPHP INI Editor.
> Then go to Editor Mode and choose particular version in which you want to make changes.
> Here find the “disable_functions” and remove the shell_exec() function to enable the function.
>

**Comment by hamzakifani** [comment]
If you want export your database with command line ssh read this 
https://www.bluehost.com/help/article/managing-databases-with-command-line-ssh

**Comment by mustercorder** [comment]
Can you please mention the file or directory where I can find the database name I'm using for stockey.

https://prnt.sc/1apy3b7

**Comment by hamzakifani** [comment]
Storage/app/public/backup
