### ISSUE TITLE
POS issue not resolved in 3.3.2

### ISSUE THREAD

**Issue by kashifleo55** [uilibrary/Stocky-Issues-and-Feature-request#253]
![image](https://user-images.githubusercontent.com/12426582/125452068-664b3e96-a5aa-46ca-b948-c350e5445584.png)

Issue not resolved still exist in 3.3.2

when write name of product in search bar and and press enter for search its show error in console and does not search product. please resolve its asap. Thanks

**Comment by hamzakifani** [comment]
why you click enter . just enter the name or code of product . if exist then will be show in search . But we will check this error  . Thank you

**Comment by kashifleo55** [comment]
I want to search product by clicking enter and result should show in product list that not working

**Comment by hamzakifani** [comment]
this plugin we used on search not use enter to search product.  we have activated the automatic selection just on the barcode scanner . just enter the name or code of product and result should show in product list. 
Thank you

**Comment by kashifleo55** [comment]
Ok , but on click it should also search desired product so user can chose form product list. Thanks
