### ISSUE TITLE
Invoice not closed on cross or side click

### ISSUE THREAD

**Issue by kashifleo55** [uilibrary/Stocky-Issues-and-Feature-request#254]
![image](https://user-images.githubusercontent.com/12426582/125459475-dc1f27fe-0303-4b8f-ace4-170bd2884eb4.png)

 

Invoice not close on cross or side click and page does not refresh or close. I think you guys does not test your build properly before upload it.  please fix it thanks.,

**Comment by hamzakifani** [comment]
This is automatically open the print page first close the print page
