### ISSUE TITLE
Bug with partial payment for POS invoice

### ISSUE THREAD

**Issue by waelamad** [uilibrary/Stocky-Issues-and-Feature-request#256]
Dear,
Once we select the product at the POS, and the due amount to be paid is: 1500, > **input amount is 500 NOT 1500**, the process is working without any notification that the paid amount is less than the due amount, and directly the invoice appeared to be printed with total amount paid 1500, not mention that the customer pay 500 and there is -1000 negative balance on his account should be paid.

I think this should be corrected to be like this:
1. there should be a checking step for the paid amount, if more than the due amount (2500) system should inform that (1000) should be considered as a change to be returned by the cashier. If less than the due amount system should inform the balance difference.
2. the system should not accept partial payment of invoices unless the customer is registered customer not walkthrough customer, so the debt would be registered on his account to be paid later on.
3. There should be an option should be added to the method of payment (partial cash payment or credit or debt etc.)
4. Invoice after printing should declare clearly the actual paid amount. and should declare clearly the negative debt amount.

Best regards
![001](https://user-images.githubusercontent.com/86734372/125505953-f37095b6-2274-4960-8301-ad5819d4ee50.jpg)
![002](https://user-images.githubusercontent.com/86734372/125505964-9c1943b9-f93d-4334-b71c-e112b7615b3d.jpg)
![003](https://user-images.githubusercontent.com/86734372/125505970-235c9f2b-a079-491d-a750-f94a75c40bc1.jpg)
[POS _ Ultimate Inventory With POS.pdf](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6811159/POS._.Ultimate.Inventory.With.POS.pdf)

I hope you can solve it.
Best regards
Wael

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.thank you

**Comment by hamzakifani** [comment]
Please contact me via skype 
![Screenshot_2021-07-13-23-45-40-315_com skype raider](https://user-images.githubusercontent.com/50219942/125534713-ffca7b27-55d3-4c82-9076-8452ed527340.jpg)

**Comment by hamzakifani** [comment]
Version 3.4.0 - 30 July 2021

Added : Server requirements in Installation
Added: Automatically increase the quantity in POS when scanning items
Added: Option to choose unit when creating Transaction
Added: Paid Amount & due Amount in pos receipt
Fixed: Show Items in the dashboard with permissions
Fixed: if Transaction deleted the stock return to the previous status
Fixed: Profit Calculation based on (price & cost)
Fixed: Report Profit And Loss
Fixed: Bug in editing Transaction
Fixed: Bug in Units
Updated: Improve security
Updated : Documentation Updated

Please follow doc for update
https://stocky.ui-lib.com/documentation/index.html
