### ISSUE TITLE
Need to solve: Issue with pre-existing products stock and Adjustment Utility

### ISSUE THREAD

**Issue by waelamad** [uilibrary/Stocky-Issues-and-Feature-request#257]
Dears,
If my physical store has already previous stock of many products.
I created products, but the stock or available quantities still ZERO.
I could not add that stock without making a new purchase order, such new purchases orders would be not convenient, since it would interfere with new purchases orders from same supplier even if we make it totally paid. It will disturb the accounting balance.

I think, there should be a utility to add available stock manually without purchase orders such as (opening balance for products stock)  

**Adjustment**
When we try to create a new adjustment for stock, it could not call the products of ZERO stock, it display only the products which already has a stock (come from purchase orders.).

**I have another issue with Adjustment Utility I will post it with new post**

**Comment by hamzakifani** [comment]
Hi. To add adjustment you have to purchase the product first. Because the adjustments comes when you have stock.

Adjustment can only occur when you have stock. Without stock how can you adjust quantity? So purchase that product first. Then you can make adjustment. Thank you

**Comment by hamzakifani** [comment]
Version 3.4.0 - 30 July 2021

Added : Server requirements in Installation
Added: Automatically increase the quantity in POS when scanning items
Added: Option to choose unit when creating Transaction
Added: Paid Amount & due Amount in pos receipt
Fixed: Show Items in the dashboard with permissions
Fixed: if Transaction deleted the stock return to the previous status
Fixed: Profit Calculation based on (price & cost)
Fixed: Report Profit And Loss
Fixed: Bug in editing Transaction
Fixed: Bug in Units
Updated: Improve security
Updated : Documentation Updated

Please follow doc for update
https://stocky.ui-lib.com/documentation/index.html
