### ISSUE TITLE
Problem of Adjustment Utility need to be solved

### ISSUE THREAD

**Issue by waelamad** [uilibrary/Stocky-Issues-and-Feature-request#258]
When I use the adjustment utility,
I call products with existing stock, and increase or decrease the stock.
The stock of a given product is 10, decrease the amount to new data let's say to 3 and omit 7.
At products panel the new stock of the product is 3.
also, the record of the operation is registered and appeared successfully at the Adjustments List Page.
**But when I delete that record, the problem appear.**
the New stock is still there 3??
that mean, if we create a permission for store Keeper, He can steal 7 pieces of a product, and adjust the stock to 3. and delete the record after adjustment and no body will notice that there are 7 pcs are missing and not sold??

Such case might happened, How we can solve this issue?
1. I think either if the adjustment record deleted the stock should return to it's previous status.
2. Or If the omitted or added amount of products should not be deleted from records list, but I can be shown as cancelled but not disappear totally from the interface. To keep people accountable to any lose or misbehavior regardless the issue of user permissions. 

Best regards
Wael

**Comment by hamzakifani** [comment]
We will fix this issue soon . Thank you

**Comment by hamzakifani** [comment]
This not a SAAS version, if you open an account for a client you will set their permissions limited

![permissions](https://user-images.githubusercontent.com/50219942/125554402-47e095db-22f9-4a7c-90c4-9d93d96a1cf7.png)

Thank you

**Comment by hamzakifani** [comment]
Version 3.4.0 - 30 July 2021

Added : Server requirements in Installation
Added: Automatically increase the quantity in POS when scanning items
Added: Option to choose unit when creating Transaction
Added: Paid Amount & due Amount in pos receipt
Fixed: Show Items in the dashboard with permissions
Fixed: if Transaction deleted the stock return to the previous status
Fixed: Profit Calculation based on (price & cost)
Fixed: Report Profit And Loss
Fixed: Bug in editing Transaction
Fixed: Bug in Units
Updated: Improve security
Updated : Documentation Updated

Please follow doc for update
https://stocky.ui-lib.com/documentation/index.html
