### ISSUE TITLE
[Feature Suggestion] Automatically increase quantity in POS when scanning items or adding barcode manually

### ISSUE THREAD

**Issue by ByteMorocco** [uilibrary/Stocky-Issues-and-Feature-request#261]
When scan an item or add it manfully in the second click or scan, I would like to increase the Qty by one instead of saying "This Product Already Added !!"

Imagine you have items in the line, and they're sorted, so you will have to read the code and increase the quantity manually and that generates a lot of stress and makes it harder for the employee and defeats the purpose of POS

**Comment by hamzakifani** [comment]
Great Feature  ,We will add it soon . Thank you

**Comment by hamzakifani** [comment]
This Feature added
https://www.awesomescreenshot.com/video/4474108?key=41b7fdfb7bb01afaf271498d647e7f52

Thanks

**Comment by ByteMorocco** [comment]
Perfect 👌

**Comment by hamzakifani** [comment]
Version 3.4.0 - 30 July 2021

Added : Server requirements in Installation
Added: Automatically increase the quantity in POS when scanning items
Added: Option to choose unit when creating Transaction
Added: Paid Amount & due Amount in pos receipt
Fixed: Show Items in the dashboard with permissions
Fixed: if Transaction deleted the stock return to the previous status
Fixed: Profit Calculation based on (price & cost)
Fixed: Report Profit And Loss
Fixed: Bug in editing Transaction
Fixed: Bug in Units
Updated: Improve security
Updated : Documentation Updated

Please follow doc for update
https://stocky.ui-lib.com/documentation/index.html

**Comment by ByteMorocco** [comment]
@hamzakifani  Do you guys close issues/suggestions when they're resolved, or I should close them manually?
