### ISSUE TITLE
Twilio SMS API integration

### ISSUE THREAD

**Issue by Zavian-Mali** [uilibrary/Stocky-Issues-and-Feature-request#266]
Hello support team, many thanks for the work done. I want to integrate twilio. How do I go about it?

**Comment by hamzakifani** [comment]
Already added . Please check setting 
Thanks

**Comment by Zavian-Mali** [comment]
Where do I get the Twilio_SID, Twilio_toke, and Twilio_from.... from? Can you outline the process please?
