### ISSUE TITLE
Twilio SMS API integration

### ISSUE THREAD

**Issue by Zavian-Mali** [uilibrary/Stocky-Issues-and-Feature-request#267]
My apologies, I've closed that issue unknowingly. You've directed me to the settings, can you articulate on how I will integrate it? Where do I find the Twilio_SID, twilio_token, and twilio_from?

**Comment by hamzakifani** [comment]
First you need to create and add phone number. then you can easily get account SID, Token and Number.

Create Account from here: www.twilio.com.

Next add Twilio Phone Number

Next you can get account SID, Token and Number and add on settings

**Comment by Zavian-Mali** [comment]
Thank you so much, I will get back to you incase of anything.
