### ISSUE TITLE
Profits

### ISSUE THREAD

**Issue by Johnson-Ichangai** [uilibrary/Stocky-Issues-and-Feature-request#268]
Hello, I had opened this issue a while ago, I really need your assistance. You told me to add this 
*Expense::with('warehouse')->get();*
Where in the code do I add this? Please if you could write/demonstrate where to put, I'll highly appreciate

**Comment by hamzakifani** [comment]
Please wait in next update . We will fix this problem of profit calculation .
Thanks

**Comment by Johnson-Ichangai** [comment]
Hello, thank you for the response. If I could offer a suggestion, you could
display the profit of the day, and the accumulated profit too. Thank you

**Comment by Johnson-Ichangai** [comment]
By the way, I was only insisting because I had installed the system at my
workplace and my boss had been pressuring me to amend those changes.
Honestly, I didn't know anywhere else to turn to. I've been under pressure
telling him I'm working on it. I really do hope the next update is as soon
as now. I just hope you understand. But thank you for taking the issue into
consideration, it will come in handy for the other clients too.

**Comment by hamzakifani** [comment]
we fixed this issue and will launch new release this maybe monday . thank you

**Comment by hamzakifani** [comment]
Contact me on skype

![Screenshot_2021-07-13-23-45-40-315_com skype raider](https://user-images.githubusercontent.com/50219942/126052960-bd04f731-04d8-4911-ae57-c1f762716f59.jpg)

**Comment by Johnson-Ichangai** [comment]
Hello again, thank you so much for fixing the issue. You really provide
excellent support and really do respond to clients' concerns. I can
confidently say that I am glad I chose Stocky. I will also champion
this system to my friends.

**Comment by Johnson-Ichangai** [comment]
Oh, I see that you said the update will be ready this Monday, maybe. Is it
out yet?

**Comment by Johnson-Ichangai** [comment]
Thank you for providing your skype contact information. I'll look for time
outside my work hours to contact you. Notify me when you have made the
update, I will highly appreciate any response. Thank you for the
extraordinary support. I really do appreciate it.

**Comment by hamzakifani** [comment]
Version 3.4.0 - 30 July 2021

Added : Server requirements in Installation
Added: Automatically increase the quantity in POS when scanning items
Added: Option to choose unit when creating Transaction
Added: Paid Amount & due Amount in pos receipt
Fixed: Show Items in the dashboard with permissions
Fixed: if Transaction deleted the stock return to the previous status
Fixed: Profit Calculation based on (price & cost)
Fixed: Report Profit And Loss
Fixed: Bug in editing Transaction
Fixed: Bug in Units
Updated: Improve security
Updated : Documentation Updated

Please follow doc for update
https://stocky.ui-lib.com/documentation/index.html
