### ISSUE TITLE
[Feature Suggestion] Order return from POS based on sale reference ID or edit order based on return situation

### ISSUE THREAD

**Issue by ByteMorocco** [uilibrary/Stocky-Issues-and-Feature-request#269]
Order return from POS based on sale reference ID or edit order based on return situation.
Make it easier to handle sale return based on sale reference ID in the POS dashboard instead of going deep in the system.

Sometimes returns happens in a short period or customer changed his mind about his order. So making it easier to perform this task or cancel order, I will save so much time and hassle especially when you have employees that doesn't quite understand the system. In general, just making it easier to access from the POS.

**Comment by hamzakifani** [comment]
Thanks for this suggestion .

**Comment by hamzakifani** [comment]
This feature has been fixed in latest version 4.0.2 .
Thanks
