### ISSUE TITLE
Add option to create order/sale status from admin area 

### ISSUE THREAD

**Issue by naime-hossain** [uilibrary/Stocky-Issues-and-Feature-request#27]
There should be way more statuses or at least end-user should be added or edit the order status.

There are so many order status that the business owners need such as

Ready To Dispatch Order Dispatched At Local Facility Out For Delivery Failed to collect payment failed to contact Consignee Shipment Refused by Consignee Delivered etc etc

**Comment by babozone** [comment]
when would this be added to the script?

**Comment by naime-hossain** [comment]
There is lots of feature request in the queue and we will let you know.  and if you are not able to continue with this feature then also let us know. thank you

**Comment by babozone** [comment]
what do you mean if I am not able to continue with this feature and let you guys know? You said in the comment on the page this feature will be updated in the new update and it's not included.

**Comment by naime-hossain** [comment]
> what do you mean if I am not able to continue with this feature and let you guys know? You said in the comment on the page this feature will be updated in the new update and it's not included.

If you think without this feature you won't able to use this app then you can request for refund. you ask for a feature and we will try to add it, we have lots of feature requests in the queue and we cant provide an app that will meet all people's expectations. and you bought the code after seeing the existing demo and feature. Thank you

**Comment by naime-hossain** [comment]
> what do you mean if I am not able to continue with this feature and let you guys know? You said in the comment on the page this feature will be updated in the new update and it's not included.

hey .... just ask a refund and leave from our products area , we don't give you custom support and don't add feature that only need you not other buyers

**Comment by naime-hossain** [comment]
> what do you mean if I am not able to continue with this feature and let you guys know? You said in the comment on the page this feature will be updated in the new update and it's not included.

Custom work or custom feature support not include in license and we said your feature will harm the main product and not possible to add and that's why you give us bad rating again and again shamelessly , i said if you don't able to use the product then just ask for refund we will give you refund and you will never use our product if you have personality . And i will report you and your rating again , some people like you never succeed to harm our product reputation don't worry . just make refund request i will refund and never ever use our product and always try to buy product after read license and what is available in demo . we are not here to give you custom work without money .
