### ISSUE TITLE
I cant run the app in the localhost with php artisan serve

### ISSUE THREAD

**Issue by anasch132** [uilibrary/Stocky-Issues-and-Feature-request#270]
i want to run and develop the app in my localhost machine , but i cant really do that because it gives lot of errors , thats why im asking for the good tips to do it , just for more information i tried php artisan serve with npm run hot and npm run dev , but no luck , also i faced too much probs in the installing phase which i didnt used xampp because of my environement (macOS m1 chip) so im asking for the good tips to make it run in my local machine , thank you.

**Comment by hamzakifani** [comment]
Hi ,
We don't tested it on MacOs , but you can test it with valet
https://laravel.com/docs/8.x/valet

Thank you
