### ISSUE TITLE
No data Available

### ISSUE THREAD

**Issue by abdfarisy** [uilibrary/Stocky-Issues-and-Feature-request#271]
hi 
when add Create Adjustment No data Available
and POS No data Available 
and Create Sale No data Available 
i mean data product

**Comment by hamzakifani** [comment]
Hi. To add adjustment you have to purchase the product first. Because the adjustments comes when you have stock.

Adjustment can only occur when you have stock. Without stock how can you adjust quantity? So purchase that product first. Then you can make adjustment. Thank you
