### ISSUE TITLE
Due is not showing on POS print preview

### ISSUE THREAD

**Issue by hmtuhindev** [uilibrary/Stocky-Issues-and-Feature-request#272]
When I create a partial payment for a POS and want to print the **Invoice POS** the due amount is not showing on the print preview.

**Comment by hamzakifani** [comment]
We will add change option in next update .
Thanks

**Comment by hamzakifani** [comment]
Version 3.4.0 - 30 July 2021

Added : Server requirements in Installation
Added: Automatically increase the quantity in POS when scanning items
Added: Option to choose unit when creating Transaction
Added: Paid Amount & due Amount in pos receipt
Fixed: Show Items in the dashboard with permissions
Fixed: if Transaction deleted the stock return to the previous status
Fixed: Profit Calculation based on (price & cost)
Fixed: Report Profit And Loss
Fixed: Bug in editing Transaction
Fixed: Bug in Units
Updated: Improve security
Updated : Documentation Updated

Please follow doc for update
https://stocky.ui-lib.com/documentation/index.html
