### ISSUE TITLE
Problem with adding a product.

### ISSUE THREAD

**Issue by AmjadKhoulani** [uilibrary/Stocky-Issues-and-Feature-request#275]
Hello

I have a problem with adding a product.

I can't find the sale unit or purchase unit, the dropdown is empty. 

![Screenshot 2021-07-15 135519](https://user-images.githubusercontent.com/19230244/126095814-dd055249-15cd-4ce1-9389-652b6e9752db.png)

**Comment by hamzakifani** [comment]
Please go to https://stocky.ui-lib.com/app/settings/Units
And create units sales & purchases

Thanks

**Comment by AmjadKhoulani** [comment]
Thanks for your reply.

Is it possible to disable this options?

**Comment by hamzakifani** [comment]
No units it's required  .
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
