### ISSUE TITLE
Stuck on 92%

### ISSUE THREAD

**Issue by hmtuhindev** [uilibrary/Stocky-Issues-and-Feature-request#276]
When I run `npm run dev` the process stuck at 92% . Please check the images:

![92% chunk asset optimization targets-optimize-chunk-assets](https://i.ibb.co/HKcTHWC/stuck.png)

**Comment by hamzakifani** [comment]
Hi ,
You can remove this plugin from webpack . This plugin for transcompiling final bundles so they support legacy browsers
Please watch this video
https://www.loom.com/share/5996281ca03a4380b9fa4103b5f3e9d0
.thank you

**Comment by hmtuhindev** [comment]
Thanks that solved the issue
