### ISSUE TITLE
The app oly show 1 child Unit from Basic Unit

### ISSUE THREAD

**Issue by sam2909** [uilibrary/Stocky-Issues-and-Feature-request#278]
As title,

I'd created many child unit from basic unit, but when I create a product, at sale unit only show basic unit and 1 child unit although I have many.

Thanks

**Comment by hamzakifani** [comment]
We will fix this issue in next update . Thanks

**Comment by hamzakifani** [comment]
Let me know if you know laravel ?

**Comment by sam2909** [comment]
> Let me know if you know laravel ?
> 
> You want me to send you the code and you paste it?

Okie please send me code. I'll paste by myself
Ty

**Comment by hamzakifani** [comment]
Please Go to \app\Http\Controllers
Extract this zip
[UnitsController.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6855729/UnitsController.zip)

and replace this file UnitsController.php

let us know if all is will , thanks

**Comment by sam2909** [comment]
![1](https://user-images.githubusercontent.com/74373486/126503589-569eec26-de0f-48cd-a7b9-472c2ad26c94.png)
![2](https://user-images.githubusercontent.com/74373486/126503594-359139e5-d207-4d46-ae53-0d16609bb807.png)
![3](https://user-images.githubusercontent.com/74373486/126503602-6386e60f-3b5c-41f2-ac38-2183722b7ae4.png)
![4](https://user-images.githubusercontent.com/74373486/126503607-aa401ea1-4f4a-4aeb-9301-cff7501fd63b.png)
![child unit id](https://user-images.githubusercontent.com/74373486/126503556-4bf4a441-65b0-41dc-8135-f93454b63d43.png) 
> Please Go to \app\Http\Controllers
> Extract this zip
> [UnitsController.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6855729/UnitsController.zip)
> 
> and replace this file UnitsController.php
> 
> let us know if all is will , thanks

It working not so good.

I tried and see that:

1. When saved, and review the product which was edited before, It show child unit's ID instead of child Unit's name.
2. While edingting a product, If previosly selected the unit as A, the child unit list will sho only same as before, that is only A and 1 child unit of A instead of showing all. I have to make a selection to Unit B, then select Unit A again, then unit at SALE UNIT will display all child unit..

**Comment by hamzakifani** [comment]
We will fix this issue in next release this week . Thanks

**Comment by sam2909** [comment]
> We will fix this issue in next release this week . Thanks

Okie many thanks

**Comment by hamzakifani** [comment]
Version 3.4.0 - 30 July 2021

Added : Server requirements in Installation
Added: Automatically increase the quantity in POS when scanning items
Added: Option to choose unit when creating Transaction
Added: Paid Amount & due Amount in pos receipt
Fixed: Show Items in the dashboard with permissions
Fixed: if Transaction deleted the stock return to the previous status
Fixed: Profit Calculation based on (price & cost)
Fixed: Report Profit And Loss
Fixed: Bug in editing Transaction
Fixed: Bug in Units
Updated: Improve security
Updated : Documentation Updated

Please follow doc for update
https://stocky.ui-lib.com/documentation/index.html
