### ISSUE TITLE
how can i edit some language ? 

### ISSUE THREAD

**Issue by reanyouda** [uilibrary/Stocky-Issues-and-Feature-request#280]
how can i edit some language ?  and compile it

**Comment by hamzakifani** [comment]
Do you know vue js ?

**Comment by erkanulker23** [comment]
why do we need to know Vue to change languages, only friends who know, use the program

**Comment by hamzakifani** [comment]
Install node js with command " npm install"
And Go to /resources/src/translations/locales

After change 

run : npm run watch
run : npm run prod

**Comment by erkanulker23** [comment]
If there was an easier option than this
