### ISSUE TITLE
404 - File or directory not found.

### ISSUE THREAD

**Issue by sumanxch** [uilibrary/Stocky-Issues-and-Feature-request#281]
When I tried to install Its displayed the following error:
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by sumanxch** [comment]
Now again its showing:
403 - Forbidden: Access is denied.
You do not have permission to view this directory or page using the credentials that you supplied.
Please help.
Thanks

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel . Thank you
