### ISSUE TITLE
how to change the system name

### ISSUE THREAD

**Issue by lot2021** [uilibrary/Stocky-Issues-and-Feature-request#282]
How to change the name of the system, I would like to know how to change it I send you a photo.
https://prnt.sc/1fbmi1i
https://prnt.sc/1fbn9ic

**Comment by hamzakifani** [comment]
Please Go to https://stocky.ui-lib.com/app/settings/System_settings

Thanks

**Comment by lot2021** [comment]
If I already change the name in settings and nothing does not work.
https://prnt.sc/1fd1ke4

**Comment by hamzakifani** [comment]
Please remove cache in settings +  browser 
Thanks

**Comment by lot2021** [comment]
If I already did it more than 5 times and nothing tell me maybe that will never change.
https://prnt.sc/1fd4xfv

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your app access . Thank you
