### ISSUE TITLE
Code Product generator is dead ?

### ISSUE THREAD

**Issue by reanyouda** [uilibrary/Stocky-Issues-and-Feature-request#285]
i want this feature 
please let it able to manual and auto generate please

**Comment by hamzakifani** [comment]
This option is available now . Please upgrade to latest release 3.3.2 
Thanks

**Comment by reanyouda** [comment]
I lost automatic generate code

**Comment by hamzakifani** [comment]
yes . just manual code

**Comment by reanyouda** [comment]
Please enable new also bcoz some local products or custom products doesn't
come with barcode.

**Comment by hamzakifani** [comment]
You can add barcode manual .

**Comment by reanyouda** [comment]
And how about minification language.
After rebuild vue js what file i should upload if my source code on server?
All of them or just some folder ?

**Comment by hamzakifani** [comment]
After rebuild . Upload folder js in /public/js
