### ISSUE TITLE
"We fixed this issue and will launch new release this maybe Monday . Thank you"

### ISSUE THREAD

**Issue by Johnson-Ichangai** [uilibrary/Stocky-Issues-and-Feature-request#286]
Hello, were u able to fix the profit calculation issue that we had discussed?

**Comment by hamzakifani** [comment]
please patience we will launch new release tomorrow.  we fixed more bugs
Thanks

**Comment by Johnson-Ichangai** [comment]
Hello, I see in the demo that you have fixed it but I haven't seen any update. I know I do seem impatient, but it's my boss who is impatient. He's been waiting for me to rectify that error, to him, I'm taking forever. Please, do understand, these are not my frustrations but rather my employer. I'm only kindly requesting you show me where to code or just anything, I really need to fix this immediately.

**Comment by Johnson-Ichangai** [comment]
Bro, is it possible for me to get version 3.3.1 the one that is being used
for the demo?

**Comment by hamzakifani** [comment]
Hi bro . I will send you the reportController . That you can fix the problem of profit

**Comment by Johnson-Ichangai** [comment]
Okay, please if possible do send it now bro, I urgently and desperately
need it bro.

**Comment by hamzakifani** [comment]
Do you know vue js ? How to re build webpack ?

**Comment by hamzakifani** [comment]
Please extract this zip
[update.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6894959/update.zip)

1) go to \app\Http\Controllers and replace ReportController.php
2) go to \resources\src\views\app\dashboard and replace dashboard.vue
3) go to \resources\src\views\app\pages\reports and replace profit_and_loss.vue

4) run  : npm run watch   and run:  npm run prod

**Comment by Johnson-Ichangai** [comment]
Thank you, thank u so much, bro. I know a bit of Vue Js. I'll try to modify
it and then get back to you. I'm headed home from work, I'll get back to
you in an hour's time. Thank you so much again, u r a lifesaver.

**Comment by naime-hossain** [comment]
If you like our item and support you can rate it on codecanyon. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Thank you

**Comment by Johnson-Ichangai** [comment]
Hello, the profit issue has finally been resolved. It's such a huge relief for me, so thank you so much. However, there's a small issue, I successfully managed to modify it, but today sales and income are not being displayed.

**Comment by Johnson-Ichangai** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/49409387/127394000-ac8b7631-ab2b-4b7a-af1d-8d437ccbb3aa.png)

**Comment by hamzakifani** [comment]
Please re-build  webpack with npm run watch & prod

**Comment by Johnson-Ichangai** [comment]
Yes, I had already installed npm and ran the command "npm run watch" since
it's locally hosted. It's only showing revenue.

**Comment by hamzakifani** [comment]
Yes I changed today sales to revenue .

**Comment by hamzakifani** [comment]
Version 3.4.0 - 30 July 2021

Added : Server requirements in Installation
Added: Automatically increase the quantity in POS when scanning items
Added: Option to choose unit when creating Transaction
Added: Paid Amount & due Amount in pos receipt
Fixed: Show Items in the dashboard with permissions
Fixed: if Transaction deleted the stock return to the previous status
Fixed: Profit Calculation based on (price & cost)
Fixed: Report Profit And Loss
Fixed: Bug in editing Transaction
Fixed: Bug in Units
Updated: Improve security
Updated : Documentation Updated

Please follow doc for update
https://stocky.ui-lib.com/documentation/index.html

**Comment by Johnson-Ichangai** [comment]
Okay, what about expenses and income? Is it possible to display?

**Comment by Johnson-Ichangai** [comment]
Btw, I've downloaded the latest version, and I don't know if I'm the only one running this, but when I try to create a payment, it keeps telling me "invalid data".

**Comment by hamzakifani** [comment]
Payment for sales or purchases ?

**Comment by Johnson-Ichangai** [comment]
Payment for sales, under POS

**Comment by Johnson-Ichangai** [comment]
![Screenshot (67)](https://user-images.githubusercontent.com/49409387/127561895-793b938e-2ae5-4a49-b995-7842200d0a6c.png)

**Comment by hamzakifani** [comment]
Please make debug= true . And send us the error

**Comment by Johnson-Ichangai** [comment]
![Screenshot (68)](https://user-images.githubusercontent.com/49409387/127562452-3d119b04-e7fb-4421-8dec-84f179bbb3da.png)
The debug has already been set to "True"

**Comment by hamzakifani** [comment]
Send me the error in console

**Comment by Johnson-Ichangai** [comment]
![Screenshot (69)](https://user-images.githubusercontent.com/49409387/127562754-a197e0b6-c50d-498a-9da7-761810f5782c.png)
This is from Mozilla

**Comment by Johnson-Ichangai** [comment]
![Screenshot (70)](https://user-images.githubusercontent.com/49409387/127562910-96c8fa0b-62dc-4fec-914a-c29040d4565a.png)
This is from Chrome

**Comment by hamzakifani** [comment]
![IMG_20210729_214248](https://user-images.githubusercontent.com/50219942/127563057-f3d3aad9-7fb8-42db-aa58-e55287dd7d58.jpg)
Click here and send me the error

**Comment by Johnson-Ichangai** [comment]
It's redirecting me to a 404 page, just a minute I try opening with edge
![Screenshot (71)](https://user-images.githubusercontent.com/49409387/127563679-ca27818e-8404-4876-8878-2461c113be5f.png)

**Comment by hamzakifani** [comment]
![IMG_20210729_214941](https://user-images.githubusercontent.com/50219942/127563886-a060e473-cc18-4076-bf73-93809a5ec45f.jpg)

Please click on Network and you well get the error .

**Comment by Johnson-Ichangai** [comment]
![Screenshot (72)](https://user-images.githubusercontent.com/49409387/127564607-c7509438-7236-4b9c-b276-6c17373a6526.png)
![Screenshot (73)](https://user-images.githubusercontent.com/49409387/127564614-79f3ddb1-f777-4b1c-a5f4-48667620152d.png)
I don't know if these will help

**Comment by hamzakifani** [comment]
I think you are forget to update database .
Please go to http://your-app/update and update it . 
Thanks

**Comment by Johnson-Ichangai** [comment]
It has worked, thank you so much. I've added $item['expenses']['sum'] to the profit equation, so as to deduct expenses from the profit

**Comment by hamzakifani** [comment]
Great work .
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by Johnson-Ichangai** [comment]
Before I close this issue and leave a like on codecanyon, 1. is it possible to display the expenses and income? That's not so important, but I would love to have that. 2. Then Is it also possible to nullify some of the customer fields? For example the country and address? (I tried setting required: true to required: false, but didn't work)

**Comment by hamzakifani** [comment]
![IMG_20210729_221438](https://user-images.githubusercontent.com/50219942/127566839-bf4218b6-d91e-4976-b8e9-006d1674cd7e.jpg)
1) You can use old code for expense and income
2)Go to clientController and remove required 
Also go to client.vue and delete required .

**Comment by Johnson-Ichangai** [comment]
Okay, thank you so so so much. You've been helpful, responsive, and supportive. Massive appreciation

**Comment by hamzakifani** [comment]
Thank you

**Comment by naime-hossain** [comment]
Hello, can you please spend some time giving a stocky 5-star rating and review?
 if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & reviews please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
