### ISSUE TITLE
Instalation Error 419

### ISSUE THREAD

**Issue by WryanCartie** [uilibrary/Stocky-Issues-and-Feature-request#288]
Greetings, 
I recently purchased this application and has begun setuping it.
I followed all the steps in the documentation( I checked whether all of my php extensions are installed, create db, etc)
Then i run npm watch and php artisan serve to start the application. 
Strangely after connecting to the lastStep it returns a 419 error.

(P.S will provide file if asked, i just dont know which one is relevant to this)

**Comment by hamzakifani** [comment]
Please follow guide installation in doc . 
Thanks

**Comment by WryanCartie** [comment]
I have followed everything in the doc.
I first installed xampp php server and its extension, i then create the database and give the prividlege for the users.
Then, i copy 127.0.0.1 stocky.local hosts file and <VirtualHost stocky.local:80>
                  ServerAdmin webmaster@stocky.local
                  DocumentRoot "C:/xampp/htdocs/stocky"
                  ServerName www.stocky.local
                  ServerAlias stocky.local
              
                   <Directory "C:/xampp/htdocs/stocky">
                          Options Indexes FollowSymLinks Includes ExecCGI
                          AllowOverride All
                          Require all granted
                      </Directory>
              
                  ErrorLog "logs/stocky.local-error.log"
                  CustomLog "logs/stocky.local-access.log" common
              </VirtualHost> this to my httpd-vhosts.conf
After that, i run npm dev and php artisan serve.
Then i open at http://stocky.local/setup and followed everything(local, debug false, i checked the db ip and everything) and it still lead me to a 419 error.
Can you help me?

**Comment by hamzakifani** [comment]
<VirtualHost stocky.local:80>
    ServerAdmin webmaster@stocky.local
    DocumentRoot "C:/xampp/htdocs/stocky"
    ServerName www.stocky.local
    ServerAlias stocky.local

     <Directory "C:/xampp/htdocs/stocky">
            Options Indexes FollowSymLinks Includes ExecCGI
            AllowOverride All
            Require all granted
        </Directory>

    ErrorLog "logs/stocky.local-error.log"
    CustomLog "logs/stocky.local-access.log" common
</VirtualHost>

**Comment by hamzakifani** [comment]
`<VirtualHost` stocky.local:80>
    ServerAdmin webmaster@stocky.local
    DocumentRoot "C:/xampp/htdocs/stocky"
    ServerName www.stocky.local
    ServerAlias stocky.local

     <Directory "C:/xampp/htdocs/stocky">
            Options Indexes FollowSymLinks Includes ExecCGI
            AllowOverride All
            Require all granted
        </Directory>

    ErrorLog "logs/stocky.local-error.log"
    CustomLog "logs/stocky.local-access.log" common
`</VirtualHost>`

**Comment by hamzakifani** [comment]
If you have a problem with xampp . You can use laragon .
Thanks

**Comment by hamzakifani** [comment]
> I have followed everything in the doc.
> I first installed xampp php server and its extension, i then create the database and give the prividlege for the users.
> Then, i copy 127.0.0.1 stocky.local hosts file and
> ServerAdmin [webmaster@stocky.local](mailto:webmaster@stocky.local)
> DocumentRoot "C:/xampp/htdocs/stocky"
> ServerName [www.stocky.local](http://www.stocky.local)
> ServerAlias stocky.local
> 
> ```
>                <Directory "C:/xampp/htdocs/stocky">
>                       Options Indexes FollowSymLinks Includes ExecCGI
>                       AllowOverride All
>                       Require all granted
>                   </Directory>
>           
>               ErrorLog "logs/stocky.local-error.log"
>               CustomLog "logs/stocky.local-access.log" common
>           </VirtualHost> this to my httpd-vhosts.conf
> ```
> 
> After that, i run npm dev and php artisan serve.
> Then i open at http://stocky.local/setup and followed everything(local, debug false, i checked the db ip and everything) and it still lead me to a 419 error.
> Can you help me?

D'ont run npm dev and php artisan serve.

**Comment by WryanCartie** [comment]
Oh yes, that was just an error when i copied that to github in text.
I see. i might try to switch from xampp if its a xampp specific error.

I just tried rerunning it without npm run dev and it still returns a 419 error.
Here is a screenshot of all relevant parts(the hosts file,database,xampp,etc) and a screen recording of me filling the setup form

https://user-images.githubusercontent.com/33276404/127160377-61b43d25-3e6e-48bc-a9ec-89bf2d4e7e25.mp4

<img width="960" alt="stocky_4" src="https://user-images.githubusercontent.com/33276404/127160401-c4ff31e2-94a9-408e-833f-e12a2dd175e0.png">
<img width="960" alt="stocky_3" src="https://user-images.githubusercontent.com/33276404/127160404-7e0e9115-103c-4c11-b764-d1281d555e79.png">
<img width="960" alt="stocky_2" src="https://user-images.githubusercontent.com/33276404/127160409-0f055d02-39a7-49d6-a2f9-2fede82268fc.png">
<img width="960" alt="stocky_1" src="https://user-images.githubusercontent.com/33276404/127160411-a20d1869-2d19-433f-8ae8-463af7086b23.png">
<img width="960" alt="stocky_5" src="https://user-images.githubusercontent.com/33276404/127160414-d5eefbf7-9287-47cf-b808-cedf7b364bf3.png">

**Comment by hamzakifani** [comment]
Please make debug = true , and check console and send us this error . 
Thanks

**Comment by hamzakifani** [comment]
*Try clearing your cache and config via

php artisan config:cache
php artisan cache:clear

*Try hard refreshing your browser with CTRL + F5

**Comment by WryanCartie** [comment]
I did the cache clear and config clear, also ctrl f5 but doesnt seem to help.
console as in the one i ran the php with? or the web console?

**Comment by hamzakifani** [comment]
Go to inspect -> Network

**Comment by hamzakifani** [comment]
You can use laragon 

https://drive.google.com/file/d/1WbkEjqHTF54yiO_SVu6mFnYaZTYTs3Rd/view

**Comment by WryanCartie** [comment]
<img width="960" alt="stocky_6" src="https://user-images.githubusercontent.com/33276404/127178225-162a56c6-abac-4dce-835b-030a49fe16c6.png">
I found this in the console.

Yes i am trying to configure laragon now.

**Comment by hamzakifani** [comment]
> <img alt="stocky_6" width="960" src="https://user-images.githubusercontent.com/33276404/127178225-162a56c6-abac-4dce-835b-030a49fe16c6.png">
> 
> I found this in the console.
> Yes i am trying to configure laragon now.

I don't see.  Stocky.local.  Why localhost:8000 ?

**Comment by hamzakifani** [comment]
Please see this video 

https://drive.google.com/file/d/1_1Hqelfm4vgK80je7-Ya_u4U5WcySrOx/view

**Comment by WryanCartie** [comment]
Sorry that was the wrong link i entered.
It still returns the same error tho with stocky.local
![image](https://user-images.githubusercontent.com/33276404/127204039-839e58ef-33a3-4b43-a19a-aadb334b84df.png)
I think there is a bit of difference when the name stocky_db is used as the feedback turns to seems okay.
The same issue persist tho it seems and the video steps are the same as before

**Comment by WryanCartie** [comment]
I already done all of the steps in the video

![image](https://user-images.githubusercontent.com/33276404/127206023-8cec9d9e-c97c-4c56-b3b7-65107a069b24.png)
Here is my hosts file



and here is the vhost file in xampp
![image](https://user-images.githubusercontent.com/33276404/127206765-e14a1b08-8818-4788-8ad8-b8a7cb7897f3.png)

**Comment by hamzakifani** [comment]
Re-install it and check again . If still issue . then use laragon 
Thanks

**Comment by WryanCartie** [comment]
I just reinstalled and am using laragon right now but it returns the same error.
I manage to copy the log of the POST request that causes the error and found this
 {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "pageref": "page_11",
        "request": {
          "method": "POST",
          "url": "http://stocky.local/setup/lastStep",
          "httpVersion": "",
          "headers": [
            {
              "name": "Host",
              "value": "stocky.local"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "47"
            },
            {
              "name": "Cache-Control",
              "value": "max-age=0"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "Origin",
              "value": "http://stocky.local"
            },
            {
              "name": "Content-Type",
              "value": "application/x-www-form-urlencoded"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
            },
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
            },
            {
              "name": "Referer",
              "value": "http://stocky.local/setup/step-3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Accept-Language",
              "value": "en,en-US;q=0.9,zh-TW;q=0.8,zh;q=0.7"
            },
            {
              "name": "Cookie",
              "value": "stocky_session=eyJpdiI6ImM3ZlJ2OE9zSE9RM0licnBiNHF6MHc9PSIsInZhbHVlIjoiTFFkZW54WHBDQnJxU0RHbFl0SFJYWHZrYXJiK0RPUnY2ZkdlNGhDNkxsSStJVThnQmd1aTgreW9aR1lYblhxQ2F5M2ZOSyszUUNVaFI4QU5vaXlSM0x5eFU5RVdWWjExTDMwNE5qcjhLSHZLdE5sbnNHZ0owZG55MmhrNmNmOEkiLCJtYWMiOiIyM2NjYWNkMTRlMTZkMTAzYmYyMGQxYTg1YmJhYTIwYjI3ZGI4YTFlYTg5YzJlN2NjZjg0NDEzNjY3ZjZkMGI2In0%3D; XSRF-TOKEN=eyJpdiI6IlRubkErcjRwdm0xYkdOYWY3eU5oUEE9PSIsInZhbHVlIjoiTnRTZ0tTR0g2dUhlWFRUQklZT1ptMUZWRnh3eTI5clBPekVEVGticDZ0aEFqaWVlMDErTVlKRWtJY3FiOEtaaVE0cmNrcmc0S2JmNlVGaWxjbFhNS3JtcWNKQnJYbG9EY3Zyc1hRMnVSUGU3SFJqWkcvNGd1c3BGWXlIc2lXaVciLCJtYWMiOiJiYTQ5ZWQ3NjRmMzQ3MjNmMmZlY2QwOGFlZWIxZTg4ZWQyOTlkMDAxZWVmNTgzODhkZTEzODBlZjBlNzA4MmYwIn0%3D; stocky_test_session=eyJpdiI6IjZwUjJuYnlESWdueVZhTzBrR2tpN1E9PSIsInZhbHVlIjoiMVcvNEpKTzFEM0xVbkFBQzR4M0hkL1ArV043Y0loRmUvaCt1OHRMM3QvTmZvSHBpVGtOVFlqQno1RmIrRkhRYWJFb3I3OHpDQUVaeHJPbE1aOU1xdWdlcyt2aDVVaE1IbEJmM2RRTUw2cUR6TTEyL1p4emQwMXp2eHRPUHBvYlUiLCJtYWMiOiIwZWU3YWJmM2E4ZmNmNTY5MDgwMTU4ZDNmMjExNTE1NGZiMjExZGM1NDUxZjMzMmEzMzM5YWM3M2QxYTJlOTA5In0%3D"
            }
          ],
          "queryString": [],
          "cookies": [
            {
              "name": "stocky_session",
              "value": "eyJpdiI6ImM3ZlJ2OE9zSE9RM0licnBiNHF6MHc9PSIsInZhbHVlIjoiTFFkZW54WHBDQnJxU0RHbFl0SFJYWHZrYXJiK0RPUnY2ZkdlNGhDNkxsSStJVThnQmd1aTgreW9aR1lYblhxQ2F5M2ZOSyszUUNVaFI4QU5vaXlSM0x5eFU5RVdWWjExTDMwNE5qcjhLSHZLdE5sbnNHZ0owZG55MmhrNmNmOEkiLCJtYWMiOiIyM2NjYWNkMTRlMTZkMTAzYmYyMGQxYTg1YmJhYTIwYjI3ZGI4YTFlYTg5YzJlN2NjZjg0NDEzNjY3ZjZkMGI2In0%3D",
              "path": "/",
              "domain": "stocky.local",
              "expires": "2021-07-28T16:34:59.128Z",
              "httpOnly": true,
              "secure": false,
              "sameSite": "Lax"
            },
            {
              "name": "XSRF-TOKEN",
              "value": "eyJpdiI6IlRubkErcjRwdm0xYkdOYWY3eU5oUEE9PSIsInZhbHVlIjoiTnRTZ0tTR0g2dUhlWFRUQklZT1ptMUZWRnh3eTI5clBPekVEVGticDZ0aEFqaWVlMDErTVlKRWtJY3FiOEtaaVE0cmNrcmc0S2JmNlVGaWxjbFhNS3JtcWNKQnJYbG9EY3Zyc1hRMnVSUGU3SFJqWkcvNGd1c3BGWXlIc2lXaVciLCJtYWMiOiJiYTQ5ZWQ3NjRmMzQ3MjNmMmZlY2QwOGFlZWIxZTg4ZWQyOTlkMDAxZWVmNTgzODhkZTEzODBlZjBlNzA4MmYwIn0%3D",
              "path": "/",
              "domain": "stocky.local",
              "expires": "2021-07-28T16:36:22.860Z",
              "httpOnly": false,
              "secure": false,
              "sameSite": "Lax"
            },
            {
              "name": "stocky_test_session",
              "value": "eyJpdiI6IjZwUjJuYnlESWdueVZhTzBrR2tpN1E9PSIsInZhbHVlIjoiMVcvNEpKTzFEM0xVbkFBQzR4M0hkL1ArV043Y0loRmUvaCt1OHRMM3QvTmZvSHBpVGtOVFlqQno1RmIrRkhRYWJFb3I3OHpDQUVaeHJPbE1aOU1xdWdlcyt2aDVVaE1IbEJmM2RRTUw2cUR6TTEyL1p4emQwMXp2eHRPUHBvYlUiLCJtYWMiOiIwZWU3YWJmM2E4ZmNmNTY5MDgwMTU4ZDNmMjExNTE1NGZiMjExZGM1NDUxZjMzMmEzMzM5YWM3M2QxYTJlOTA5In0%3D",
              "path": "/",
              "domain": "stocky.local",
              "expires": "2021-07-28T16:36:22.861Z",
              "httpOnly": true,
              "secure": false,
              "sameSite": "Lax"
            }
          ],
          "headersSize": -1,
          "bodySize": 47,
          "postData": {
            "mimeType": "application/x-www-form-urlencoded",
            "text": "_token=4LTp9TWsMdT58uuTrmEhyrHxtheIowXeUz1Gmvb7",
            "params": [
              {
                "name": "_token",
                "value": "4LTp9TWsMdT58uuTrmEhyrHxtheIowXeUz1Gmvb7"
              }
            ]
          }
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_CONNECTION_RESET"
        },
        "serverIPAddress": "",
        "startedDateTime": "2021-07-28T14:36:23.808Z",
        "time": 708.3039999999983,
        "timings": {
          "blocked": 708.3039999999983,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "_blocked_queueing": -1
        }
      }
    ]
  }
}
[console.txt](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6893999/console.txt)

**Comment by hamzakifani** [comment]
Please contact me on https://join.skype.com/invite/v6Cqli3xreT9

**Comment by WryanCartie** [comment]
Okay i just accepted your invitation

**Comment by hamzakifani** [comment]
Issue fixed .

**Comment by naime-hossain** [comment]
If you like our item and support you can rate it on codecanyon. If you don’t know how to provide ratings & reviews please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Thank you
