### ISSUE TITLE
How to upload product image via postman

### ISSUE THREAD

**Issue by alifpramanarasa** [uilibrary/Stocky-Issues-and-Feature-request#289]
i have try upload product via form data and raw json, but it not uploaded yet, and data not parse to API, do u have a tutorial or some tips for uploading image in API via postman ? thankyou

**Comment by hamzakifani** [comment]
You can add with base64.  Thanks

**Comment by hamzakifani** [comment]
You could encode the file to base64 and send it.

https://base64.guru/converter/encode/file

**Comment by alifpramanarasa** [comment]
Send text?

**Comment by alifpramanarasa** [comment]
Ohh i see, just send text in base64 ?

**Comment by hamzakifani** [comment]
Yes

**Comment by alifpramanarasa** [comment]
Oke , thankyou sir
