### ISSUE TITLE
update

### ISSUE THREAD

**Issue by abdfarisy** [uilibrary/Stocky-Issues-and-Feature-request#294]
Hello
 if you update the program
Is the code I modified affected?

**Comment by hamzakifani** [comment]
Yes

**Comment by abdfarisy** [comment]
how to solve it , without .
If I modify the code does it come back as if I didn't modify it after the update ؟

**Comment by hamzakifani** [comment]
Yes

**Comment by abdfarisy** [comment]
Do system settings such as name, etc., change?

**Comment by hamzakifani** [comment]
if  you have modified somthing in the program does not change.  But if you have added something in the code or changed something, for example, if you are a developer and you have added some code in the code.  Of course you will lose it after the update.

**Comment by hamzakifani** [comment]
Anything registered in the database will not be lost .

**Comment by abdfarisy** [comment]
ok . System Settings  is not change when update yes ? like 
Default Currency
Default Email
Change Logo
Company Name
Company Phone
Developed by
footer
Default Customer
Default Warehouse
Address

**Comment by hamzakifani** [comment]
No . Don't worry 
Just follow the correct etape to update stocky
