### ISSUE TITLE
last version 

### ISSUE THREAD

**Issue by abdfarisy** [uilibrary/Stocky-Issues-and-Feature-request#295]
Do you have to update every time?
Suppose I did not update this version.
After a while, you made another update.
If you decide to upgrade, get the latest version.
Do you like to update gradually?

**Comment by hamzakifani** [comment]
you can update whenever you want without problem. 
Thanks

**Comment by abdfarisy** [comment]
You have updated a new version of the program. Then in the future you will also make other updateds
I do not want to update now but after 5 updates.

Is when I update everything is fine (I mean I don't want to update every time and sequentially). I want to update every 5 update from you i am update , is this normal?

**Comment by hamzakifani** [comment]
Yes is normal .
