### ISSUE TITLE
[Feature suggestion] Sale return based on sale reference

### ISSUE THREAD

**Issue by ByteMorocco** [uilibrary/Stocky-Issues-and-Feature-request#297]
Imagine someone bought product  ONE TWO and THREE, and He wanted to return product TWO. The customer has a reference printed on his receipt.

Return sale should edit his order based on "sale reference" shows what he bought as a list of products and let the cashier edit his order and automatically adjust the stock and add the product(s) back to the warehouse stock.

**Comment by hamzakifani** [comment]
This option added . Thanks
