### ISSUE TITLE
http://my-app/update show an error "SQLSTATE42000: Syntax error or access violation: 1280 Incorrect index name ‘sale_unit_id’ (SQL: alter table `sale_details` add index `sale_unit_id`(`sale_unit_id`))"

### ISSUE THREAD

**Issue by sam2909** [uilibrary/Stocky-Issues-and-Feature-request#299]
I’d update new version (from 3.3.2 to 3.4.0) and it show an error “SQLSTATE42000: Syntax error or access violation: 1280 Incorrect index name ‘sale_unit_id’ (SQL: alter table `sale_details` add index `sale_unit_id`(`sale_unit_id`))”

I access url http://my-app/update, and this error appear when url go to http://my-app/update/lastStep

I tried F5 to re-submit form, it show "SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'sale_unit_id' (SQL: alter table `sale_details` add `sale_unit_id` int null after `price`)"

Please help, many thanks

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel + app access . Thank you

**Comment by sam2909** [comment]
> Please contact via : [uilib.help@gmail.com](mailto:uilib.help@gmail.com) with your cpanel + app access . Thank you

Ty for your reply, I can fix it temporary by delete file `2021_07_19_141906_add_sale_unit_id_to_sale_details.php` in `mirgration` folder and press F5 to complete update.

But I've a question that If i do that, my application can work without any error in the future?

Thanks

**Comment by hamzakifani** [comment]
it will be a  error . You must change index name in database/migrations . 
Please contact me in skype . I will send you the file and replace it . 
https://join.skype.com/invite/v6Cqli3xreT9
