### ISSUE TITLE
Error Pay Purchase

### ISSUE THREAD

**Issue by tjaoc** [uilibrary/Stocky-Issues-and-Feature-request#3]
Every Pay, but appear Parcial

<img width="602" alt="Captura de pantalla 2021-04-06 a las 19 26 51" src="https://user-images.githubusercontent.com/6704635/113753248-2c176880-970e-11eb-96e5-a92d6bc8ea7d.png">

**Comment by naime-hossain** [comment]
it's working fine without any problem. thank you

**Comment by tjaoc** [comment]
Work Fine????? Invoice Value 478,65€ i pay 478,65€€ and the information it's "Partial"????? It's is normal. work???????

**Comment by naime-hossain** [comment]
Please check the demo, we fixed it, we will update the code. please check the demo https://stocky.ui-lib.com/ , if you still got the issue in the demo please send us a screenshot. thank you
