### ISSUE TITLE
CSS FAILS

### ISSUE THREAD

**Issue by jean1991** [uilibrary/Stocky-Issues-and-Feature-request#304]
CSS is not working. from the installation go up to the ends.
https://katas.tech/setup

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel . Thank you

**Comment by jean1991** [comment]
I have emailed you all the details

**Comment by hamzakifani** [comment]
Please contact me on skype
https://join.skype.com/invite/v6Cqli3xreT9

**Comment by jean1991** [comment]
what time is it good for me to contact you

**Comment by hamzakifani** [comment]
Contact me now

**Comment by hamzakifani** [comment]
issue fixed . 

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you 

Giving Feedback On Items
https://help.market.envato.com
