### ISSUE TITLE
Where is the barcode scanner button?

### ISSUE THREAD

**Issue by siusang** [uilibrary/Stocky-Issues-and-Feature-request#305]
Hello

I can't find the barcode scanner function in easy pos, i saw a search bar which said "Scan/Searh Product by Code Name" only.. so where is the barcode scanner button? i can't find it even in your Demo system, my stocky version is V3.5, thank you.

![qooah-screenshot_2903](https://user-images.githubusercontent.com/86476694/127900369-4809abd2-3400-44ba-9a37-f3175ad9964a.jpg)

**Comment by hamzakifani** [comment]
Just plug the scanner, hover the mouse cursor on the scan/search product text field and scan the barcode. If your scanner can read the product code from barcode correctly then it will work .

**Comment by siusang** [comment]
> Just plug the scanner, hover the mouse cursor on the scan/search product text field and scan the barcode. If your scanner can read the product code from barcode correctly then it will work .

can i use the mobile phone camera as a scanner? I tried my phone and click scan/search product text field, no camera screen, it let me type and search only, it doesn't load a camera screen for scanning..

**Comment by hamzakifani** [comment]
The only requirement for barcode scanners/readers is that they must send return command after typing the codes. If your barcode scanner does this, you are ready to use it with this script. Just focus the barcode scanner input and start scanning. If you already have one . Thank you

**Comment by siusang** [comment]
> The only requirement for barcode scanners/readers is that they must send return command after typing the codes. If your barcode scanner does this, you are ready to use it with this script. Just focus the barcode scanner input and start scanning. If you already have one . Thank you

Now i also have trouble when creating product, the code product field is required, but the scan code function is not working.
your app have a generator button at previous version, but it disappeared at V3.5 ,, so i have to input the code manually ever time when I create a product?? thanks.


![qooah-screenshot_2904](https://user-images.githubusercontent.com/86476694/127954099-d45c7c70-1fa0-4303-8b21-7e5e5c89cf6a.jpg)

**Comment by hamzakifani** [comment]
Yes . Put your code and select the correct barcode symblogic .
