### ISSUE TITLE
not able to open using http// as now only use php artisan serve http://127.0.0.1:8000 need help

### ISSUE THREAD

**Issue by Max0101id** [uilibrary/Stocky-Issues-and-Feature-request#306]
not able to open using http// as now only use php artisan serve http://127.0.0.1:8000 need help

**Comment by hamzakifani** [comment]
Please follow doc if you want install it in local.
You can use xampp or laragon .
You don't want php artisan serve . Just follow doc .

**Comment by Max0101id** [comment]
Yea I am using XAMPP but it’s just blank when use local. Not sure why. But
if use php artisan to launch only work. Any solution?:)

**Comment by hamzakifani** [comment]
Please contact me on skype
https://join.skype.com/invite/v6Cqli3xreT9

**Comment by hamzakifani** [comment]
Please follow this guide for install laravel on macOS  
https://laravel.com/docs/8.x/valet
