### ISSUE TITLE
how to add warranty option for electronics item

### ISSUE THREAD

**Issue by Robelrana** [uilibrary/Stocky-Issues-and-Feature-request#307]
brother i have mobile shop how can i add warranty option in customer invoice ..?
please add  warranty option

**Comment by hamzakifani** [comment]
We will add it to our queue .

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by Robelrana** [comment]
same request i am submit you befor 20-25 days ago.
you same answer me but not any update.
please first priority this requirement

**Comment by hamzakifani** [comment]
we are more features in our queue. every week we launch new update, please cooperate with us.
thanks

**Comment by hamzakifani** [comment]
This feature has been added in latest version
