### ISSUE TITLE
Invalid data when submit payment

### ISSUE THREAD

**Issue by farolr** [uilibrary/Stocky-Issues-and-Feature-request#308]

**Comment by farolr** [comment]
<img width="1437" alt="Screen Shot 2021-08-03 at 12 27 42" src="https://user-images.githubusercontent.com/47473215/127962682-8b2d200e-8fb7-49c3-96e3-05a00d74f58a.png">

**Comment by farolr** [comment]
<img width="1437" alt="Screen Shot 2021-08-03 at 12 29 59" src="https://user-images.githubusercontent.com/47473215/127962821-8a40bc06-d3f5-4fe2-abad-17c306f14f36.png">

**Comment by hamzakifani** [comment]
Please upgrade to latest version 3.5.0
Thanks
