### ISSUE TITLE
Signin to dashboard

### ISSUE THREAD

**Issue by kazmie** [uilibrary/Stocky-Issues-and-Feature-request#31]
Run using php artisan serve.

After signin it not go anywhere. Just loading in login screen

![image](https://user-images.githubusercontent.com/14286729/115491080-e7550b00-a291-11eb-88cd-1475f41135fc.png)

**Comment by hamzakifani** [comment]
if you have php 8, this version of stocky not compatible with php 8, so please use PHP 7.3 or 7.4
or wait a few hours we will launch a new update which will be compatible with php 8, thank you

**Comment by naime-hossain** [comment]
This issue will be solved with Stocky Version 2.0.0 and check this #https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues/16
