### ISSUE TITLE
Compiling stops with errors!!

### ISSUE THREAD

**Issue by Vertex21** [uilibrary/Stocky-Issues-and-Feature-request#312]
Not able to compile your project. I commented out the template code for the customizer and tried to recompile with,
npm install
npm run production
but I get these errors after waiting a LONG time for it to finish.

  stocky export NODE_OPTIONS=--max_old_space_size=8000
➜  stocky npm run prod

> npm run production

> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 ERROR  Failed to compile with 2 errors                               2:35:19 PM

These relative modules were not found:

* ./views/app/pages/expense/Create_expense in ./resources/src/router.js
* ./views/app/pages/expense/Edit_expense in ./resources/src/router.js
 621 assets

ERROR in ./resources/src/router.js
Module not found: Error: Can't resolve './views/app/pages/expense/Create_expense' in '.../resources/src'
 @ ./resources/src/router.js 170:15-172:51
 @ ./resources/src/main.js
 @ multi ./resources/src/main.js ./resources/src/assets/styles/sass/globals/globals.scss

ERROR in ./resources/src/router.js
Module not found: Error: Can't resolve './views/app/pages/expense/Edit_expense' in '/.../resources/src'
 @ ./resources/src/router.js 178:15-180:49
 @ ./resources/src/main.js
 @ multi ./resources/src/main.js ./resources/src/assets/styles/sass/globals/globals.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2021-08-05T21_35_20_530Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2021-08-05T21_35_20_557Z-debug.log
➜  stocky

**Comment by hamzakifani** [comment]
Hi ,
You can remove this plugin on mode dev from webpack . This plugin for transcompiling final bundles so they support legacy browsers
Please watch this video
https://www.loom.com/share/5996281ca03a4380b9fa4103b5f3e9d0
.thank you

**Comment by Vertex21** [comment]
Thank you! I also found that there is a capitalization error in your code. On linux systems the route has to match the capitalization of the file name. In your router.js file you have:
`{
    name: "store_expense",
    path: "store",
    component: () =>
    import(/* webpackChunkName: "store_expense" */"./views/app/pages/expense/Create_expense")
},
{
    name: "edit_expense",
    path: "edit/:id",
    component: () =>
    import(/* webpackChunkName: "edit_expense" */"./views/app/pages/expense/Edit_expense")
},`

**But it needs to be:**
`{
name: "store_expense",
path: "store",
component: () =>
import(/* webpackChunkName: "store_expense" */"./views/app/pages/expense/create_expense")
},
{
name: "edit_expense",
path: "edit/:id",
component: () =>
import(/* webpackChunkName: "edit_expense" */"./views/app/pages/expense/edit_expense")
},`

This solved the compiling errors for me.

**Comment by Vertex21** [comment]
Also, now that the site is live, I am having a CORS error in Chrome with the POS submit script.

https://www.loom.com/share/a7fc01b8fad54ca49f8eb8a7e5c80fed

**Comment by Vertex21** [comment]
Also, I am having a CORS issue with the POS script that creates a new sale. It seems some of the code is unsafe and Chrome is now blocking it. Please watch the video:

https://www.loom.com/share/4b9d675fd4ed46c396b2634fa35b93ce

**Comment by hamzakifani** [comment]
Please Remove this from html

<meta http-equiv="Content-Security-Policy" content="default-src 'self'">

**Comment by Vertex21** [comment]
Thank you but I can't tell which file contains that code? I found a couple of index.js files that contained res.setHeader('Content-Security-Policy', "default-src and I commented those lines out but after building the project again I still have the same issue.

**Comment by hamzakifani** [comment]
Please tel me what server you using apache or nginx ?

**Comment by Vertex21** [comment]
I am using Apache

**Comment by Vertex21** [comment]
I never received this error with the previous version.. Only this new version 3.5

**Comment by hamzakifani** [comment]
"I think You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html"

**Comment by Vertex21** [comment]
I think you are right.. however, I am running npm run prod and I have made no changes to your package.json file. In package.json it reads:
`"scripts": {

        "dev": "npm run development",

        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",

        "watch": "npm run development -- --watch",

        "watch-poll": "npm run watch -- --watch-poll",

        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",

        "prod": "npm run production",

        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"`
This shows NODE_ENV is being set to production.

**Comment by Vertex21** [comment]
I also just tried,
npm install --production
npm run prod

Still the same results.

**Comment by hamzakifani** [comment]
please re-upgrade stocky with the version 3.5.0 without edit any file if you don't know vue js better and let me know the result . thanks

**Comment by Vertex21** [comment]
Ok, I have created a fresh install with version 3.5. I have not edited any file. I have not run npm commands on the directory. I have only uploaded the v3.5 files and created a virtual host for the test site in Apache. I have the exact same error.

https://www.loom.com/share/75c5f55f01214ecfbb4135befeb18296

**Comment by Vertex21** [comment]
Now I have created a fesh install with version 3.3.2. I have not edited any files nor have I run any npm commands on the project. On this version 3.3.2, I still get the CSP error in Chrome, however, I do NOT get the CreatePOS function 500 error when submitting the order.

https://www.loom.com/share/cad31d7499f843e19c5d232ab3125ff1

**Comment by hamzakifani** [comment]
Please check your server. We have never had this problem and all buyers have not this problem. You can check all the issue here.
Thanks

**Comment by Vertex21** [comment]
This is the problem on my dev server and also on my shared server from Opalstack. My dev server is running Ubuntu 20.04 and was configured by me, but my production shared server is running CentOS 7 and is configured by Opalstack. It is unlikely that I would have the same error on 2 different Linux servers?
Can you please tell me what is the ideal server configuration for your program? Or tell me a hosting company that I should use?

**Comment by hamzakifani** [comment]
Bluehost , hostgator ... Thanks

**Comment by Vertex21** [comment]
Ok I actually found the problem! I did not realize the database structure had changed with v3.5. I used my existing database from v3.3.2 and that is what caused the 500 error when creating the POS or Sales order.
Can you tell me what changed? I have a LOT of information in version 3.3.2 database and need to use it in version 3.5.
Or should I only use v3.3.2 for now?
Thank you

**Comment by Vertex21** [comment]
And just so you know, the two ways that I tried restoring the database information was from the SQL backup function on your web app as well as the export function in phpmyadmin. Both methods resulted in the POST 500 error on CreatePOS function call. I have not tried manually exporting and importing the data in each table individually.
Please tell me what next steps I should take. I am attaching a copy of the SQL backup so you can test on your end. Again, this database works fine in V3.3.2
[backup-2021-08-11_dev.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6970757/backup-2021-08-11_dev.zip)

**Comment by Vertex21** [comment]
My final test was a success. I imported only the data from the tables; categories, clients, payment_sales, product_warehouse, products, providers, purchase_details, purchases, sale_details, sales, servers, settings, units, users, warehouses
I left all the other tables as the website setup created them.
And everything worked!
So I'm wondering, do you think it is a problem with importing the whole backup because of the oauth tables possibly??

**Comment by hamzakifani** [comment]
Please follow the upgrade guide .
after copying files and folders to your project . Go to the url http://your-app/update
To update your database. 
Thanks

**Comment by hamzakifani** [comment]
Import your last database of v3.3.2 . 
If upgrade to latest relase . Follow the upgrade guide in doc . And Go to the url http://your-app/update to update your database .
Thanks

**Comment by Vertex21** [comment]
Wow.. that http://your-app/update command was all that I was missing.. I am so sorry for the troubles! I ran the update URL and everything is working now. Thank you for your help!

**Comment by hamzakifani** [comment]
Great work .
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
