### ISSUE TITLE
Notes do not show on Invoice

### ISSUE THREAD

**Issue by hificom** [uilibrary/Stocky-Issues-and-Feature-request#315]
When I "Download Pdf"
I only see "Signature" at bottom center.

Where can we see the notes: 

![Screen Shot 2021-08-07 at 9 08 07 AM](https://user-images.githubusercontent.com/85292687/128601250-fa0179cd-cf96-4ed2-9330-3762c3a74484.JPG)

![Screen Shot 2021-08-07 at 9 08 56 AM](https://user-images.githubusercontent.com/85292687/128601276-b9b622c8-c51e-4637-b6ff-2830ffe10045.JPG)

**Comment by hificom** [comment]
@naime-hossain   was this issue fixed yet??

**Comment by naime-hossain** [comment]
We will fix one by one, have Patience. thank you
