### ISSUE TITLE
SMTP Script Error

### ISSUE THREAD

**Issue by deansga** [uilibrary/Stocky-Issues-and-Feature-request#318]
Hi,

 The smtp details I have entered are correct because the system sends out forgot password links.

However if I send a purchase or quotation from a list I receive error ' SMTP configuration incorrect'.

I contacted Namecheap my hosting company and they stated this below:

We have found the following error in the home/skiltbia/domain.com/storage/logs/laravel.log file.

[2021-08-13 01:24:17] production.ERROR: Address in mailbox given [n/a] does not comply with RFC 2822, 3.6.2. {"userId":1,"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [n/a] does not comply with RFC 2822, 3.6.2. at /home/skiltbia/domain.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)

Looks like there is some misconfiguration in the website script files related to emails sending.

Please can you provide the fix.  I recently purchased the script but the mail notifications are not all fully functional.

It's so strange as 'forgot password' works fine but any other mail notification does not work.   I have tried all methods with TLS and SSL.  Only can get forgot password working when testing.

Please help!!!

thanks,

Dean

**Comment by deansga** [comment]
This has now been fixed by myself without author help.

**Comment by hamzakifani** [comment]
how did you solve this problem ?
thanks

**Comment by hamzakifani** [comment]
Smtp is working fine without any problem . 
I tested it now . It's no bug in our script  .
Thanks

**Comment by ab-ashagrie** [comment]
@deansga I'd like to know how you fixed this
