### ISSUE TITLE
Remove Docs from left side menu... what file in file manager ?

### ISSUE THREAD

**Issue by deansga** [uilibrary/Stocky-Issues-and-Feature-request#319]
I want to remove the doc menu after installation from the dashboard login ?

What file in the file manager web files do I need to edit and what row?

thank you

**Comment by Vertex21** [comment]
**I'm not involved in this project in any way, just a user**
Being it's a Laravel/Vue app you have to recompile the project after you edit the code. Well to do it properly anyway. The file is Sidebar.vue.
To get away with not re-compiling the code and doing it right, you could possible add some CSS to the master.css file in the ./public/css folder to count down the number of ul->li elements in the nav bar and do a display:none on it.

Something like this could work, but I haven't tried it:
.layout-sidebar-large section.sidebar-left div ul.navigation-left li:last-child {
display: none;
}

**Comment by deansga** [comment]
thanks vertex21... unfortunately it did not work after entering the code

file is here:
https://www.filemail.com/d/sydnsnrpqsphluu

**Comment by deansga** [comment]
if possible can you re-compile and send the file to me on here... I can't seem to get any support the past 3 days from the team and also have this smtp error (but that is another issue)

many thanks

**Comment by hamzakifani** [comment]
Hello , 
Please watch this video
https://www.awesomescreenshot.com/video/4847172?key=53967aa7410eccca70de96927df8de7c

Thanks
