### ISSUE TITLE
NMP install gives errors -> npm version 7 issue ?

### ISSUE THREAD

**Issue by Stridesdata** [uilibrary/Stocky-Issues-and-Feature-request#32]
$  npm install                                                                                                           
npm ERR! code 1
npm ERR! path C:\xampp\htdocs\bookeepit\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\bookeepit\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\xampp\\htdocs\\bookeepit\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.8.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:13:12) 
npm ERR! gyp verb `which` failed     at F (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:13:12) 
npm ERR! gyp verb `which` failed     at F (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\Solomon Iseh\AppData\Local\Programs\Python\Python38-32\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\Solomon Iseh\AppData\Local\Programs\Python\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:327:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\bookeepit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\xampp\htdocs\bookeepit\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.8.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Solomon Iseh\AppData\Local\npm-cache\_logs\2021-04-21T14_51_49_570Z-debug.log

**Comment by hamzakifani** [comment]
Hi , Please deleting the node_modules directory and package-lock.json, then run command npm install.

**Comment by Stridesdata** [comment]
This was the response




$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree  
npm ERR! 
npm ERR! While resolving: undefined@undefined        
npm ERR! Found: eslint@7.24.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.17.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^6.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Solomon Iseh\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Solomon Iseh\AppData\Local\npm-cache\_logs\2021-04-23T06_42_51_626Z-debug.log

**Comment by naime-hossain** [comment]
Try to run npm rebuild node-sass
and if this won't work then delete node_modules and package.lock file then run `npm install --legacy-peer-deps`

if this also not work then run` yarn` for this you need to install yarn globally 

Thank you

**Comment by Stridesdata** [comment]
I have npm working well on my other project.. I dont understand why I am having this issue specifically in this app

**Comment by Stridesdata** [comment]
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: eslint@7.24.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.17.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^6.2.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Solomon Iseh\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Solomon Iseh\AppData\Local\npm-cache\_logs\2021-04-23T13_16_10_115Z-debug.log

**Comment by hamzakifani** [comment]
Try this command : 

npm install --save --legacy-peer-deps

**Comment by hamzakifani** [comment]
If you have node_modules folder and package-lock.json file in your root directory then remove those:

**Comment by Stridesdata** [comment]
Same errors... I think it has to do with your code,,, 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: eslint@7.25.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.17.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^6.2.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Solomon Iseh\AppData\Local\npm-cache\eresolve-report.txt for a full report.

**Comment by Stridesdata** [comment]
I cannot install packages using npm . I have been on this for too long.. Also there are a lot of deprecated codes and blocks of codes. No developer will be comfortable with editor showing numerous errors.

Please you need to fix all these..I cannot customize for my clients because of the errors in the code.

**Comment by naime-hossain** [comment]
If you have node_modules folder and package-lock.json file in your root directory then remove those:
rm -r node_modules
rm package-lock.json

2 ) Then run commands:
npm install --legacy-peer-deps

**Comment by Stridesdata** [comment]
When the command is running, I see the node module folder being created but before it finishes running, it disappears.

$ npm install --legacy-peer-deps
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code 1
npm ERR! path C:\xampp\htdocs\bookeepit\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\bookeepit\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\xampp\\htdocs\\bookeepit\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.8.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:13:12) 
npm ERR! gyp verb `which` failed     at F (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:13:12) 
npm ERR! gyp verb `which` failed     at F (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bookeepit\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\Solomon Iseh\AppData\Local\Programs\Python\Python38-32\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\Solomon Iseh\AppData\Local\Programs\Python\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:327:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\bookeepit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\xampp\htdocs\bookeepit\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.8.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Solomon Iseh\AppData\Local\npm-cache\_logs\2021-04-27T14_10_05_225Z-debug.log

**Comment by naime-hossain** [comment]
Plesse start from new stocky code. Run yarn if npm not working

**Comment by Stridesdata** [comment]
I don't understand.

**Comment by naime-hossain** [comment]
Download new stocky and then run npm install - - legacy-peer-deeps

**Comment by naime-hossain** [comment]
https://yarnpkg.com/

**Comment by Stridesdata** [comment]
I have tried yarn and the node module folder has been created.  I appreciate your assistance

**Comment by Stridesdata** [comment]
Although with warnings.. I still appreciate

**Comment by naime-hossain** [comment]
It's a warning, not an error, don't worry about it. and please in the codecanyon comment mention that your problem is fixed so that other buyers will know it. thank you :)

**Comment by Stridesdata** [comment]
I have done that already.
If I can delete I will

**Comment by naime-hossain** [comment]
Yarn fixed the issue https://yarnpkg.com/

**Comment by Stridesdata** [comment]
apparently this issue persists... Can you share details of your environment so I can understand why I only see the numerous errors at my own end.

**Comment by naime-hossain** [comment]
Did you solve the issue? Thank you

**Comment by Stridesdata** [comment]
It is still not solved Sir

**Comment by Stridesdata** [comment]
Please help me.. I don't know what else to do.. on my other project I do not get errors.. but here i can't even add any new page .. npm run dev .give errors . Yarn run Dev .. same thing
Build Is not working.. please..

**Comment by naime-hossain** [comment]
[package-lock.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6411901/package-lock.zip)
Please in new stocky, use this package-lock file in the root and then run npm commands. thank you

**Comment by pikapika10** [comment]
I too am stuck with this error from a week. Nothing works. Kind help will be appreciable.

**Comment by naime-hossain** [comment]
> I too am stuck with this error from a week. Nothing works. Kind help will be appreciable.

@hamzakifani check this

**Comment by Stridesdata** [comment]
@pikapika10 
Mine is OKay for over 1 month now.

But the issue had to do with my Dev environment.
  I don't know what exactly solved the issue. However, here are a few options.

Install windows Dev tools--
Start PowerShell as Administrator and run:
npm install --global windows-build-tools

Install Npm globally-- 
Start command prompt as Administrator and run:
npm install npm -g

Ensure you are running from your computer and not from your development editor..


Note.. I am a novice.. however let we know which worked for you.

**Comment by pikapika10** [comment]
@Stridesdata 
Hi there! Although I tried that earlier too, I did what you suggested and the result is still the same. I'm giving up on this for now. Maybe someday later return back to it. And thanks for the reply :-)

**Comment by nurularifin83** [comment]
> $ npm install npm ERR! code 1 npm ERR! path C:\xampp\htdocs\bookeepit\node_modules\node-sass npm ERR! command failed npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js npm ERR! Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\bookeepit\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library= npm ERR! gyp info it worked if it ends with ok npm ERR! gyp verb cli [ npm ERR! gyp verb cli 'C:\Program Files\nodejs\node.exe', npm ERR! gyp verb cli 'C:\xampp\htdocs\bookeepit\node_modules\node-gyp\bin\node-gyp.js', npm ERR! gyp verb cli 'rebuild', npm ERR! gyp verb cli '--verbose', npm ERR! gyp verb cli '--libsass_ext=', npm ERR! gyp verb cli '--libsass_cflags=', npm ERR! gyp verb cli '--libsass_ldflags=', npm ERR! gyp verb cli '--libsass_library=' npm ERR! gyp verb cli ] npm ERR! gyp info using node-gyp@3.8.0 npm ERR! gyp info using node@15.8.0 | win32 | x64 npm ERR! gyp verb command rebuild [] npm ERR! gyp verb command clean [] npm ERR! gyp verb clean removing "build" directory npm ERR! gyp verb command configure [] npm ERR! gyp verb check python checking for Python executable "python2" in the PATH npm ERR! gyp verb `which` failed Error: not found: python2 npm ERR! gyp verb `which` failed at getNotFoundError (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:13:12) npm ERR! gyp verb `which` failed at F (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:68:19) npm ERR! gyp verb `which` failed at E (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:80:29) npm ERR! gyp verb `which` failed at C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:89:16 npm ERR! gyp verb `which` failed at C:\xampp\htdocs\bookeepit\node_modules\isexe\index.js:42:5 npm ERR! gyp verb `which` failed at C:\xampp\htdocs\bookeepit\node_modules\isexe\windows.js:36:5 npm ERR! gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:196:21) npm ERR! gyp verb `which` failed python2 Error: not found: python2 npm ERR! gyp verb `which` failed at getNotFoundError (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:13:12) npm ERR! gyp verb `which` failed at F (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:68:19) npm ERR! gyp verb `which` failed at E (C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:80:29) npm ERR! gyp verb `which` failed at C:\xampp\htdocs\bookeepit\node_modules\node-gyp\node_modules\which\which.js:89:16 npm ERR! gyp verb `which` failed at C:\xampp\htdocs\bookeepit\node_modules\isexe\index.js:42:5 npm ERR! gyp verb `which` failed at C:\xampp\htdocs\bookeepit\node_modules\isexe\windows.js:36:5 npm ERR! gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:196:21) { npm ERR! gyp verb `which` failed code: 'ENOENT' npm ERR! gyp verb `which` failed } npm ERR! gyp verb check python checking for Python executable "python" in the PATH npm ERR! gyp verb `which` succeeded python C:\Users\Solomon Iseh\AppData\Local\Programs\Python\Python38-32\python.EXE npm ERR! gyp ERR! configure error npm ERR! gyp ERR! stack Error: Command failed: C:\Users\Solomon Iseh\AppData\Local\Programs\Python\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3]; npm ERR! gyp ERR! stack File "", line 1 npm ERR! gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3]; npm ERR! gyp ERR! stack ^ npm ERR! gyp ERR! stack SyntaxError: invalid syntax npm ERR! gyp ERR! stack npm ERR! gyp ERR! stack at ChildProcess.exithandler (node:child_process:327:12) npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:378:20) npm ERR! gyp ERR! stack at maybeClose (node:internal/child_process:1067:16) npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) npm ERR! gyp ERR! System Windows_NT 10.0.19041 npm ERR! gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\xampp\htdocs\bookeepit\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" npm ERR! gyp ERR! cwd C:\xampp\htdocs\bookeepit\node_modules\node-sass npm ERR! gyp ERR! node -v v15.8.0 npm ERR! gyp ERR! node-gyp -v v3.8.0 npm ERR! gyp ERR! not ok npm ERR! Build failed with error code: 1
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Solomon Iseh\AppData\Local\npm-cache_logs\2021-04-21T14_51_49_570Z-debug.log

In my case, I solved this problem by changing the node version to 14.15.1.
