### ISSUE TITLE
how to remove Docs from main left menu?

### ISSUE THREAD

**Issue by deansga** [uilibrary/Stocky-Issues-and-Feature-request#320]
please send proper instructions on how to remove Docs from the menu?

I have downloaded visual editor and node.js. but what do I do now?

Please see YouTube video on steps

**Comment by hamzakifani** [comment]
Hello , 
Please watch this video 
https://www.awesomescreenshot.com/video/4847172?key=53967aa7410eccca70de96927df8de7c
Thank you
