### ISSUE TITLE
Changed files list in updates

### ISSUE THREAD

**Issue by Vertex21** [uilibrary/Stocky-Issues-and-Feature-request#321]
Hi! Is it possible to have a list of the changed files in each update? For those of us that are doing custom things to the project it would be nice to know exactly which files are changed so that we can only implement the changes.

Thanks!

**Comment by hamzakifani** [comment]
You can pull it via github . It's easy

**Comment by Vertex21** [comment]
Where can I pull it via github? On the "Code" tab you only show information up to version 2.2.0 in the "README.md" file.
