### ISSUE TITLE
How to re-direct to product list page on login?

### ISSUE THREAD

**Issue by deansga** [uilibrary/Stocky-Issues-and-Feature-request#322]
Hi,

when a user logs in, I want them to see the Product List screen first and not the Dashboard.

Please can you send me the code and file to edit to achieve this?  Thank you,

https://domain.com/app/products/list

Dean

**Comment by hamzakifani** [comment]
Hello , 
Please watch this video
https://www.awesomescreenshot.com/video/4847194?key=09a01813a290fbd3f24e6fcd283bd546
Thanks

**Comment by deansga** [comment]
> Hello ,
> Please watch this video
> https://www.awesomescreenshot.com/video/4847194?key=09a01813a290fbd3f24e6fcd283bd546
> Thanks

Hi Hamza , thank so much but when I edited the file it did not work for me.

I have attached the file and made modification.   When I saved it on my server it does not seem to work like the demo?

https://www.filemail.com/d/blsfgavhjpaxzir

File to check above link.

thanks

**Comment by hamzakifani** [comment]
You need to upload also  folder js in   public/js .
Thanks

**Comment by deansga** [comment]
but there was no changes to public/js ?

can you add the folder please on here, so I can download then I can upload please

many thanks

**Comment by deansga** [comment]
> You need to upload also folder js in public/js .
> Thanks

but there was no changes to public/js ?

can you add the folder please on here, so I can download then I can upload please

many thanks

**Comment by hamzakifani** [comment]
All js change compiled in public/js .
You must upload it to your server after each change .
Thanks

**Comment by deansga** [comment]
> All js change compiled in public/js .
> You must upload it to your server after each change .
> Thanks

I'm receiving error when I try to compile

see screenshot please:

<img width="1377" alt="Screenshot 2021-08-15 at 14 33 30" src="https://user-images.githubusercontent.com/88865862/129480342-4a40bd03-5fa3-4294-b4ee-4c533be48aa3.png">

can you do it and send your public/js to me please ?

**Comment by hamzakifani** [comment]
Please first  run : npm install to install node js . Thanks

**Comment by deansga** [comment]
> Please first run : npm install to install node js . Thanks

I have done that and followed your video. Strange it still don't work.

I uploaded the public/js whole folder after re compiling and saving

I'm obviously doing something wrong

can you please sed me the public/js folder you updated you complied so my changes reflect the same way as yours?

many thanks

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel info. Thank you
