### ISSUE TITLE
after upload to aws ec2 get error 500 

### ISSUE THREAD

**Issue by mohamedyousef** [uilibrary/Stocky-Issues-and-Feature-request#323]
![Uploading Screen Shot 2021-08-14 at 6.15.50 PM.png…]()

**Comment by hamzakifani** [comment]
We don't tested it in aws . This system work only with apache or nginx.  

Please check doc for more info .
Thanks

**Comment by mohamedyousef** [comment]
I used apache

**Comment by mohamedyousef** [comment]
and followed the instructions

**Comment by mohamedyousef** [comment]
get same error

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your server info. Thank you

**Comment by mohamedyousef** [comment]
done
