### ISSUE TITLE
Thank You Buddy

### ISSUE THREAD

**Issue by hassanulhaque** [uilibrary/Stocky-Issues-and-Feature-request#324]
Thank you so much <3

**Comment by hamzakifani** [comment]
Yes you can do it as you need . Go to adjustment section. Thanks

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
