### ISSUE TITLE
Broken Installation Page.

### ISSUE THREAD

**Issue by CodeCurosity** [uilibrary/Stocky-Issues-and-Feature-request#325]
Hello,

I just purchased stocky, i have all the libraries and everything proper setup but when i run setup it shows this broken design and i tried installing and complete setup, it shows only broken logo on login page and no form, this is fresh installation now, how can i fix this?

**Comment by CodeCurosity** [comment]
![image](https://user-images.githubusercontent.com/16650859/129556683-1ba823a7-e249-48e2-8399-33d7902fdcdd.png)

**Comment by CodeCurosity** [comment]
All extensions are enabled on Cpanel.

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel access
