### ISSUE TITLE
photo upload does not apply

### ISSUE THREAD

**Issue by vbossa** [uilibrary/Stocky-Issues-and-Feature-request#326]
I have bought twice for two different customers, in both the hosting service are enabled all permissions and even if when uploading the product photo this does not load it and is left with the state of loading.
![productos](https://user-images.githubusercontent.com/67298313/129626693-b1d5e67f-51fd-42e5-9ae6-00b1b1a9435a.png)

**Comment by hamzakifani** [comment]
Hi ,
What version are you using ?

**Comment by vbossa** [comment]
Hello
the last version, and I've tried with previous versions and the same thing happens.

**Comment by hamzakifani** [comment]
Please contact via : stocky.ui.lib@gmail.com with your app access

**Comment by vbossa** [comment]
Thanks a lot

**Comment by hamzakifani** [comment]
issue fixed , 
"allow_url_fopen" not enabled
