### ISSUE TITLE
Can I change social sharing logo and title ?

### ISSUE THREAD

**Issue by SharifShimanta** [uilibrary/Stocky-Issues-and-Feature-request#327]
I have shared the URL with my partner through Facebook to share credentials with him and noticed the logo and title are the default software title and logo. Can we update this?

**Comment by hamzakifani** [comment]
Please send us your purchase code . Thanks

**Comment by SharifShimanta** [comment]
<html>
<body>
<blockquote type="cite" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div dir="ltr">

71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a
-- | -- | -- | -- | --
71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a
71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a
71f30540-a877-4f35-87f9-00e2689c161a | 71f30540-a877-4f35-87f9-00e2689c161a
71f30540-a877-4f35-87f9-00e2689c161a

</div></blockquote>
</body>
</html>

**Comment by SharifShimanta** [comment]
71f30540-a877-4f35-87f9-00e2689c161a

**Comment by hamzakifani** [comment]
Please go to settings to change your logo as you need . Thanks

**Comment by SharifShimanta** [comment]
I have already changed the logo from the dashboard but it did not changed here neither the title. 
![2021-08-17-03-51-www facebook com](https://user-images.githubusercontent.com/61265000/129636667-cd5e2c05-126f-4507-a98e-fef4d869dc35.png)

**Comment by hamzakifani** [comment]
it will be archived don't worry

**Comment by hamzakifani** [comment]
Please go to /resources/views/layouts/master.blade.php and  /resources/views/auth/login.blade.php
and add this solution in head


<meta property="og:image" content="https://www.website.com/logo.jpg">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1024">
<meta property="og:image:height" content="1024">
<meta property="og:type" content="website" />
<meta property="og:url" content="https://www.website.com/"/>
<meta property="og:title" content="Website title" />
<meta property="og:description" content="Website description." />
You can make test with https://developers.facebook.com/tools/debug/

Please check here . That help you https://stackoverflow.com/questions/19632323/default-website-image-for-social-sharing
