### ISSUE TITLE
Feature Request Category Icon

### ISSUE THREAD

**Issue by mohamedyousef** [uilibrary/Stocky-Issues-and-Feature-request#328]

**Comment by mohamedyousef** [comment]
Very nice POS

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
