### ISSUE TITLE
logo change

### ISSUE THREAD

**Issue by viveroquispe** [uilibrary/Stocky-Issues-and-Feature-request#329]
hello when I try to change the logo it doesn't change me completely.
I leave a small video:
https://reccloud.com/es/u/1ifrgwx

**Comment by hamzakifani** [comment]
Logo of login page change manual if you know vue js . Thanks

**Comment by naime-hossain** [comment]
> Logo of login page changed manually if you know vue js . Thanks

just make the login logo from DB like the main dashboard logo @hamzakifani
