### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by 1weedmain** [uilibrary/Stocky-Issues-and-Feature-request#33]
Hello Support,
So I need to create db and follow instructions?
[help.txt](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6354761/help.txt)

**Comment by hamzakifani** [comment]
Create a DB and user and connect this new DB with New User, follow the installation guide.Test connection is giving error that’s mean your DB credential and permissions are not ok. 

make sure you are enable PDO PHP EXTENSION in your cpanel . Thank you

**Comment by naime-hossain** [comment]
Hope This Solves your issue, I am closing the issue, if you still have the problem let us know, we will solve it as soon as possible.  

if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: 
[How to Rate ThemeForest item ](https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items )
thank you
