### ISSUE TITLE
How to remove/rename some menu items and fields

### ISSUE THREAD

**Issue by GauravKhare-19** [uilibrary/Stocky-Issues-and-Feature-request#331]
I want to hide certain menu items and also want to rename, add some fields in products. These fields should be displayed when we display the product information. Please share how we can do that along with the technical documentation

**Comment by hamzakifani** [comment]
Do you know vue js ?

**Comment by GauravKhare-19** [comment]
No, But if you tell me the steps or if you have any document which I can refer then I will be able to do that. Thanks

**Comment by hamzakifani** [comment]
1) install node js with command : npm install

2) go to /resources/src/containers/layouts/largeSidebar/Sidebar.vue 

2) after editing  run : npm run prod

3) if you upladed your projet in hosting . Upload this file edited and public/js

Thanks

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
