### ISSUE TITLE
How to edit invoice format ?

### ISSUE THREAD

**Issue by fiqahmad** [uilibrary/Stocky-Issues-and-Feature-request#332]
Hi, I try to download the purchase invoice and found out that the formatting like this.

![image](https://user-images.githubusercontent.com/22277263/130242246-b88d9b14-eed7-4ca1-b0af-91dad19c7195.png)

The default formatting its doesn't look professional, and bad alignment.  Can I edit the format ? Especially the purple color one.

The invoice should look minimal and official. 

Thank you.

**Comment by hamzakifani** [comment]
Please go to /resources/views/pdf
Thanks

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
