### ISSUE TITLE
Editable payment method ?

### ISSUE THREAD

**Issue by fiqahmad** [uilibrary/Stocky-Issues-and-Feature-request#333]
Current payment method and format look like this .

![image](https://user-images.githubusercontent.com/22277263/130243183-7f856710-2e2a-46ae-827a-eeead0b48e06.png)

The formatting is not consistent and please consider let user ADD UP/DELETE/EDIT our own payment mechanism to the POS System. That would be nice.

Thank you

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
Thanks

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by fiqahmad** [comment]
Thank you for your response. Could you add 'Payment Gateway' on the list ?

appreciate. Thank you.
