### ISSUE TITLE
Error unit

### ISSUE THREAD

**Issue by edgmtz08** [uilibrary/Stocky-Issues-and-Feature-request#336]
[https://youtu.be/qhC7gjmm5BQ](url)

Error en unidad de medida, cómo eliminar esas unidades y cual es el proceso disculpa?

**Comment by edgmtz08** [comment]
Cambie de servidor, lo mismo... Y bueno, ahora si no hay duda cual es el error.

**Comment by naime-hossain** [comment]
> Cambié el servidor y la respuesta fue la misma. Podrías apoyarme con la estructura de los permisos de cada archivo? podría ser que a la hora de cargar se cargaron con los permisos mal estructurados.

Write in English please

**Comment by edgmtz08** [comment]
I changed the server and the answer was the same. Could you help me with the permissions structure of each file? It could be that at the time of loading they were loaded with the wrongly structured permissions.

**Comment by hamzakifani** [comment]
your server configured to block anything except GET and POST
please contact your provider and ask him to enable PUT and DELETE methods .

Thanks

**Comment by edgmtz08** [comment]
Could you help me tell my provider what to do (hostgator) please :(
