### ISSUE TITLE
Create Adjusment Stuck in Search Products

### ISSUE THREAD

**Issue by farahmawan** [uilibrary/Stocky-Issues-and-Feature-request#337]
Hello,
I've an issue with creating adjustment stock like this video https://www.awesomescreenshot.com/video/4984244?key=65ae5418e4767434c68557e29a8be883
What should I do to solve my issue?

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
