### ISSUE TITLE
Print Shipping Label & SMS API

### ISSUE THREAD

**Issue by mustercorder** [uilibrary/Stocky-Issues-and-Feature-request#34]
Please add shipment label using customer address and SMS API auto perches notification to purchasers mobile phone.

**Comment by naime-hossain** [comment]
Hello, @mustercorder  Thank you for your feature request , we will add it to our Roadmap :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
SMS Is completed You will get it in stocky2.2.0 . if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by mustercorder** [comment]
I'm having some issues with SMS Api. Please develop it. Need some more feature here like Sent SMS, auto perches notification to customer phone & order status update, mass notification to all customer. And also add other random SMS providers API. 

I hope you consider these issues.

**Comment by praveenimpulse** [comment]
https://www.fast2sms.com/dashboard/dev-api

plz add this sms gateway
