### ISSUE TITLE
create new product

### ISSUE THREAD

**Issue by brhco** [uilibrary/Stocky-Issues-and-Feature-request#340]
you need to but create a new category and brand to create a new product page

**Comment by hamzakifani** [comment]
We will add this feature in future . Thanks

**Comment by brhco** [comment]
I have edit the code by myself, and add this feature. If you need the files
contact with me.

Thanks

**Comment by brhco** [comment]
brhoomcanon@gmail.com this is my email

**Comment by naime-hossain** [comment]
please send the code here : uilib.help@gmail.com thank you
