### ISSUE TITLE
MariaDB 

### ISSUE THREAD

**Issue by samialbashir** [uilibrary/Stocky-Issues-and-Feature-request#341]
Hello,
Can I Install your script on **MariaDB** ?

Actually I am trying to Install on my Amazon AWS server but I cant!! Its only testing not going to another step! Please Help me.....

Regards

**Comment by hamzakifani** [comment]
Hello 
Please send us a screen shot of your issue . Thanks

**Comment by samialbashir** [comment]
Hello sir, Its only testing not going for next step!! 

![Screenshot_1](https://user-images.githubusercontent.com/89750329/131408409-d45f11c1-286d-4665-8fd3-8ff59e9a1aab.png)
![Screenshot_2](https://user-images.githubusercontent.com/89750329/131408413-2dd56251-f255-4cb3-a115-25ab485fa133.png)
![Screenshot_3](https://user-images.githubusercontent.com/89750329/131408414-beb7c82c-e985-4135-b701-68fda96e7e32.png)
![Screenshot_5](https://user-images.githubusercontent.com/89750329/131408644-0c3c40d8-9fd5-46ab-9324-c139dae74942.png)

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel . Thank you

**Comment by samialbashir** [comment]
Please check the email

**Comment by hamzakifani** [comment]
Hello , 
your domain access or subdomain not working
account.probashit***.co 
you cannot do setup via http://3.19.****/plesk-site-preview/account.probas****
you must do it via  account.probashit***.co 
I uploaded an image for testing this subdomain but no access , it's not working

thanks
