### ISSUE TITLE
I Want the Written text (Thank You For Shopping With Us.) in the Receipt before the barcode to change to Partronics not Shopping 

### ISSUE THREAD

**Issue by Jesutofunmi5** [uilibrary/Stocky-Issues-and-Feature-request#343]
![sggg](https://user-images.githubusercontent.com/59127445/131846444-354ba466-0718-438f-892d-a9f91b228126.PNG)
I Want the Written text (Thank You For Shopping With Us.) in the Receipt before the barcode to change to Partronics not Shopping

**Comment by hamzakifani** [comment]
You request for the custom work
wait patiently when we have time we will do the edit for you otherwise do it by yourself . Its your custom need not system bug or anything . https://codecanyon.net/item/stockyultimate-inventory-management-system-with-pos/31445124/support read this carefully . thank you

**Comment by reneortega03** [comment]
> ![sggg](https://user-images.githubusercontent.com/59127445/131846444-354ba466-0718-438f-892d-a9f91b228126.PNG)
> Quiero que el texto escrito (Gracias por comprar con nosotros) en el recibo antes del código de barras cambie a Partronics not Shopping
hola puedo ayudar con la traducción escribeme al watssap +51952748066

**Comment by hamzakifani** [comment]
Latest Version 3.7.0 - 27 August 2021

-   Added:  Choose default language from area settings
-   Added:  Pos Settings
-   Fixed:  bug in Twilio SMS
-   Updated:  Hide Documentation from the sidebar
-   Updated:  Improve performance
-   Updated  :  Documentation Updated
-   Fixed:  bug fixes
