### ISSUE TITLE
Associate User to a warehouse or multiple or to all

### ISSUE THREAD

**Issue by nasseroali** [uilibrary/Stocky-Issues-and-Feature-request#345]
Asigning a user to a specific warehouse/s or all would be a good feature.

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by RickoM** [comment]
Yes, I would like that feature. I'm using Stocky - Ultimate Inventory with POS and have 10 Warehouse locations which I would like only staff in these locations to access their warehouse and inventory. This would reduce errors by users transacting stock from different warehouse. Maybe adding user permissions which could limit their access rights in certain warehouses.

**Comment by hamzakifani** [comment]
Hello , assigned warehouse to specific users  it's available now in version 4.0.  Thanks
