### ISSUE TITLE
Sales Return

### ISSUE THREAD

**Issue by TarekMAli** [uilibrary/Stocky-Issues-and-Feature-request#346]
you did the sales very well and its great it generates a bar code with the sales, but sales return would be alot better if what you look for is reference ID not the Product, so for example i sold an ITEM for 100USD with discount of 20 usd and i have a return policy of one week and someone came back wants to return the item, i go to sales return scan his reset or type his reference number, i get the transaction that its sold then i can return Back and take the item so like that i have a record for the sales and the sales return.
as now u go sales return u type like ur adding another item and add different pricing.. so please consider fixing this.

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
This option is added in latest version 4.0.2 . Thanks
