### ISSUE TITLE
i want to change Default  language

### ISSUE THREAD

**Issue by gamal22d** [uilibrary/Stocky-Issues-and-Feature-request#35]
i want to change language defulte

**Comment by hamzakifani** [comment]
if you want to make a default language

1) Go to /resources/src/plugins/i18n.js
![i18n](https://user-images.githubusercontent.com/50219942/117991163-5374dd00-b32d-11eb-8120-52af3bafd6ef.PNG)


2)  replace " en" ;

to :

 en,
 fr,
 ar,
 de,
 es,
 it,
 Ind,
 thai,
 tr_ch,
 sm_ch,
 tur,
 ru,
 hn,
 vn,

3) run : npm install
4) run : npm run watch
5) run : npm run prod

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
