### ISSUE TITLE
When will you release the next update?

### ISSUE THREAD

**Issue by willchan0101** [uilibrary/Stocky-Issues-and-Feature-request#350]
Hello Teams,

There is not features update released since 10/Aug, our shop is growing but this software still missing lot of features, can you  tell a roadmap for my reference or I'll start to find out another POS system to handle my product stocks, thank you.

**Comment by hamzakifani** [comment]
Hello ,
we have a lot of features in our queue . we will luanch new release soon . thank you

**Comment by hamzakifani** [comment]
Latest Version 3.7.0 - 27 August 2021

-   Added:  Choose default language from area settings
-   Added:  Pos Settings
-   Fixed:  bug in Twilio SMS
-   Updated:  Hide Documentation from the sidebar
-   Updated:  Improve performance
-   Updated  :  Documentation Updated
-   Fixed:  bug fixes

**Comment by siusang** [comment]
> Latest Version 3.7.0 - 27 August 2021
> 
>     * Added:  Choose default language from area settings
> 
>     * Added:  Pos Settings
> 
>     * Fixed:  bug in Twilio SMS
> 
>     * Updated:  Hide Documentation from the sidebar
> 
>     * Updated:  Improve performance
> 
>     * Updated  :  Documentation Updated
> 
>     * Fixed:  bug fixes

Thanks for the works, did you upload this version to codecanyon? i saw the last update date is 10 August 21, and the zip file is still v3.6.0 after i downloaded. 
btw, when will you update the report system? thanks.
