### ISSUE TITLE
Problem with setup 

### ISSUE THREAD

**Issue by n3113y** [uilibrary/Stocky-Issues-and-Feature-request#355]
As it loads the default router it gets stuck at the last link of  http://localhost:8000/setup/lastStep it kills the connections instead of finishing the procedure it says This site can’t be reached localhost refused to connect.

**Comment by hamzakifani** [comment]
Installation in Localhost
you need to download XAMPP or LAMPP Server

Step 1 : Go to C:\Windows\system32\drivers\etc\ open the "hosts" file in Administrator mode.

Step 2 : Add the following code to it. Here

127.0.0.1 stocky.local

Step 3 : Now go to, C:\xampp\apache\conf\extra for xampp users and for the wamp user "C:\wamp\bin\apache\Apache2.4.4\conf\extra" and open "httpd-vhosts.conf" file. Now add the following code into it.

Notes :Change the Document root as per your project also add domain name as you define into the "hosts" file.

```
 <VirtualHost stocky.local:80>
                  ServerAdmin webmaster@stocky.local
                  DocumentRoot "C:/xampp/htdocs/stocky"
                  ServerName www.stocky.local
                  ServerAlias stocky.local
              
                   <Directory "C:/xampp/htdocs/stocky">
                          Options Indexes FollowSymLinks Includes ExecCGI
                          AllowOverride All
                          Require all granted
                      </Directory>
              
                  ErrorLog "logs/stocky.local-error.log"
                  CustomLog "logs/stocky.local-access.log" common
              </VirtualHost>
```

Step 4 : Last but the important step is to restart your Xampp or Wamp

Setup Installation : Access the url http://stocky.local/setup

**Comment by n3113y** [comment]
i am using mac

**Comment by n3113y** [comment]
Am guessing problem is with the setup route because i update the the .env file  instead of completing the setup it exits the connection like as shown below
<img width="1433" alt="Screenshot 2021-09-17 at 6 44 34 PM" src="https://user-images.githubusercontent.com/40654704/133817156-afcaacf3-138c-4b83-8535-b21f011217cf.png">

**Comment by n3113y** [comment]
using the UI as shown  in the documentaiton i am a new user just purchased it

**Comment by hamzakifani** [comment]
Re-install your projet
If you use macOS you can run :
 php artisan serve

And start the setup 

But For macOs we recommand to install laravel with valet please follow this guide

https://laravel.com/docs/8.x/valet

**Comment by n3113y** [comment]
well i have followed your advise but still getting the same error

**Comment by hamzakifani** [comment]
Re-install your projet
And run :
php artisan serve

And start the setup

Send us a screen Shot or video

**Comment by n3113y** [comment]
kindly share an email so that i send you a video via we transfer

**Comment by hamzakifani** [comment]
Send us here . Via https://www.awesomescreenshot.com/

**Comment by hamzakifani** [comment]
Please add me on skype . I will help you
https://join.skype.com/invite/v6Cqli3xreT9

**Comment by hamzakifani** [comment]
issue fixed

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you 


Giving Feedback On Items
https://help.market.envato.com
