### ISSUE TITLE
Getting Blank Screen after adding Twilio Keys

### ISSUE THREAD

**Issue by niendoo** [uilibrary/Stocky-Issues-and-Feature-request#356]
Hi, I added Twilio keys and cleared the cache and then the whole system does not load again. Loads black page only. see https://www.awesomescreenshot.com/video/5272838?key=c70ef07d11caabed65aa78020d77f775

**Comment by niendoo** [comment]
Please help me fix this asap. Thanks

**Comment by hamzakifani** [comment]
I think you have a problem in your hosting

**Comment by niendoo** [comment]
When I remove the twilio keys from the env. File it loads fine but when I
add it back again the system loads blank!

If you think it's my host, then recommend a hosting that it will work fine
on. I am using interserver. Thanks

**Comment by hamzakifani** [comment]
I will check and let you know
Please contact via : uilib.help@gmail.com with your cpanel + app access + twilio keys . Thank you

**Comment by niendoo** [comment]
Please check your email. Thanks

**Comment by hamzakifani** [comment]
I will check and let you know . Thanks

**Comment by niendoo** [comment]
Ok, thanks.

**Comment by hamzakifani** [comment]
Hello , 
You have a problem with TWILIO_FROM=Alfares Enterprise

_**your issue is :**_ 

If any of your .env variables contains white space for example TWILIO_FROM=Alfares Enterprise ,
 make sure you wrap them in double-quotes. For example: TWILIO_FROM= "Alfares Enterprise"

**_solution :_** 
I fixed this issue i changed the code in SettingsController 

We will fix this issue in next release , Thank you

**Comment by niendoo** [comment]
Thanks a lot. Please can you recommend any other SMTP server that will send
customers email directly? I set up mailtrap but then the emails only goes
to the mailtrap inbox but doesn't go to the customer's email inbox. Thank
you

**Comment by niendoo** [comment]
Please is there any further configuration I must do to have the SMS work?
Whenever I try to send sms it says wrong configuration. Thanks & Regards.

**Comment by hamzakifani** [comment]
Please create account in twilio . I think the twilio from not valid . Must be a phone number .

**Comment by hamzakifani** [comment]
Twillio_from must be a phone number not Alfares Enterprise please check your account in twillio . And you'll get it

**Comment by hamzakifani** [comment]
TWILIO_FROM = "INSERT YOUR TWILIO NUMBER

GO to your account twillio under section phone numbers you'll get your number .

**Comment by niendoo** [comment]
OK, I got it.

**Comment by niendoo** [comment]
Please do I need to include country codes for customers number? Also please
address the SMTP issue I raised. Thank you.

**Comment by hamzakifani** [comment]
First test to another your number phone . try  with code country & without . And check if working .

**Comment by niendoo** [comment]
[image: image.gif]

I have added the phone number from twilio but still get the error
message  wrong
sms config invalid

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
09/20/21,
10:10:21 AM

**Comment by niendoo** [comment]
I have finally got it to work for me. Thank You. Please can you recommend a
SMTP service that would send the client an email instead of sending it to
the SMTP server inbox?


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/20/21,
10:20:43 AM

**Comment by niendoo** [comment]
Dear Abdul Rauf 
 We are contacting you in regard to a invoice #SL_1112 https://example.com/Sale_PDF/2 that has been created on your account. 
 We look forward to conducting future business with you.

Please this is the message that gets sent via the sms. The URL structure accompanying the sms leads the client to login to our system and that's not right. I think it should only send a downloadable pdf link of the invoice to the client so that when the client clicks on it, it downloads the receipt or invoice for him or her. Also can you show me the file that contains the message? I want to modify it. Thank you

**Comment by hamzakifani** [comment]
please go to /app/Http/Controllers/SalesController.php

In footer you'll get the function sms . Znd you can change the message.  
Thanks

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
