### ISSUE TITLE
Product and Variants Search Issue

### ISSUE THREAD

**Issue by fahimnaseem** [uilibrary/Stocky-Issues-and-Feature-request#357]
**The system should ask for the product first, then its variant.**

As per this structure, If you have 1000 Products and 5 Variant of Each product, and at the time purchasing system will start searching with 1000×5 products at the same time which is not good practice

**Comment by hamzakifani** [comment]
I have verified this problem.  We have a problem with the plugin's autocomplete if the data is large it will be a problem, not in the structure.  But we fixed this issue locally.  We will update the code ASAP. Thanks

**Comment by fahimnaseem** [comment]
You can also Break it into two steps, first the selection of product then It's variant selection.

please do let me know when you will resolve this issue, I need it urgently

**Comment by hamzakifani** [comment]
don't worry i will update the code in your cpanel . thank you

**Comment by fahimnaseem** [comment]
Thank you but when? because I need it on an urgent basis.

**Comment by hamzakifani** [comment]
I am working with it 
please watch this video

https://www.awesomescreenshot.com/video/5301249?key=6819ccd0a559133f01ae3931634f473d

**Comment by hamzakifani** [comment]
Please add me on skype . I will help you
https://join.skype.com/invite/v6Cqli3xreT9

**Comment by hamzakifani** [comment]
issue fixed

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

Giving Feedback On Items
https://help.market.envato.com

**Comment by fahimnaseem** [comment]
Hello Team,
I have an issue with Stocky Software, I want to change the Invoice design. The design is ready but my issue is I am not able to run the code on the local computer ( it gives some plugin errors ).
________________________________

**Comment by hamzakifani** [comment]
Please share your issue with us . Thanks

**Comment by fahimnaseem** [comment]
When I try to run the command it always stuck at 98%.
If you can please come on Skype then it will be highly appreciated
________________________________

**Comment by hamzakifani** [comment]
Hi ,
You can remove this plugin on mode dev from webpack . This plugin for transcompiling final bundles so they support legacy browsers
Please watch this video
https://www.loom.com/share/5996281ca03a4380b9fa4103b5f3e9d0
.thank you

**Comment by fahimnaseem** [comment]
Thank you so much.
________________________________

**Comment by fahimnaseem** [comment]
Hello Hamza,
I am done with my changes and made a built, but after the deployment, I am not able to see the changes on a live server.
can you please help me.

username: cloudcom
password: Paki$tan47
domain: https://cloud-haroonoptical.com/<https://cloud-haroonoptical.com/login>
________________________________

**Comment by hamzakifani** [comment]
You need upload public/js .
Please not share your private info here  .

**Comment by fahimnaseem** [comment]
Still not working, can you please help

**Comment by hamzakifani** [comment]
Edit you file after change run : npm run prod 
And upload public/js + your files changed .

**Comment by fahimnaseem** [comment]
did the same things but still not working

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hamzakifani** [comment]
It's working in local ? Clear your browser cache .

**Comment by fahimnaseem** [comment]
yes works in local but not on the server

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hamzakifani** [comment]
if you follow the correct procedure then it will be works fine . 

Upload files changed 
Upload public/js
Clear browser cache .
