### ISSUE TITLE
XAMPP INSTALLATION NOT WORKING

### ISSUE THREAD

**Issue by OliverWachira** [uilibrary/Stocky-Issues-and-Feature-request#358]
i have every possible steps on your guide but im still getting a "site cant be reached error" kindly help

**Comment by hamzakifani** [comment]
If you have a problem with xampp . Then install laragon is very easy . Thanks

**Comment by OliverWachira** [comment]
send me a guide on how to install on laragon

**Comment by hamzakifani** [comment]
Please add me on skype . I will help you
https://join.skype.com/invite/v6Cqli3xreT9

**Comment by OliverWachira** [comment]
can we use google meet instead please

**Comment by OliverWachira** [comment]
i'm using the user name elizabeth moore on skype so dont be confused please...haha...but i still need assistance bruh

**Comment by hamzakifani** [comment]
Issue fixed
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
