### ISSUE TITLE
Emails does not send to client emails

### ISSUE THREAD

**Issue by niendoo** [uilibrary/Stocky-Issues-and-Feature-request#359]
When I set up the mailtrap SMTP, the email does not get sent to the client but rather sends to the mailtrap account inbox. Am I missing something?

**Comment by hamzakifani** [comment]
Mailtrap is just for test . Please use sendgrill or elasticmail ..or another provider

**Comment by niendoo** [comment]
Ok. Thanks

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
