### ISSUE TITLE
Backup Issue 

### ISSUE THREAD

**Issue by lifetill** [uilibrary/Stocky-Issues-and-Feature-request#36]
Hi, there 
I couldn't find any backup file on backup menu.
I tried many times to generate a backup but it doesn't work.

https://prnt.sc/11zqb1x

**Comment by hamzakifani** [comment]
we fixed this problem on stocky v 2.1 , You can update it .  Thank you

**Comment by naime-hossain** [comment]
Download the latest version from codecanyon.if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by lifetill** [comment]
Thank you for your update.

**Comment by lifetill** [comment]
I'll rate your item top.

**Comment by naime-hossain** [comment]
> I'll rate your item top.

Thank you and you can check the avobe link to see how you can rate on envato.  By the way do you use our product for your personal store? Or for your client?

**Comment by lifetill** [comment]
I'm a developer I work on Scala but I'm using this for my personal business. 
and it Needless to say, you did a very good job.

**Comment by hamzakifani** [comment]
Great , you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
> I'm a developer I work on Scala but I'm using this for my personal business.
> and it Needless to say, you did a very good job.

Thank you, Please Don't redistribute or resell Stocky, you can point to our main item page to anyone if they need it. and please if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by naime-hossain** [comment]
I am closing this issue as it's fixed with Stocky-2.1.0
if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by lifetill** [comment]
> > I'm a developer I work on Scala but I'm using this for my personal business.
> > and it Needless to say, you did a very good job.
> 
> Thank you, Please Don't redistribute or resell Stocky, you can point to our main item page to anyone if they need it. and please if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)


Selling someone's property without owners permission it's not ethical. I won't do that brother & I practice my Religion it's also prohibited in my deen.
