### ISSUE TITLE
SMS invoice Link directs client to login screen

### ISSUE THREAD

**Issue by niendoo** [uilibrary/Stocky-Issues-and-Feature-request#360]
Please is it possible to avoid redirecting the client to the login screen when an invoice or quotation SMS is sent to the client? Can't we have the pdf direct link in the SMS so that when the client clicks on it downloads the invoice or quotation directly without sending them to the login screen? If there's any code you can send my way, kindly do that. Thank you

**Comment by niendoo** [comment]
Please also how can I reduce the file size of the application. I had to run npm legacy-peer-deps before I could get npm run prod to work, and after doing that, the file sizes grew astronomically big! Thanks

**Comment by hamzakifani** [comment]
I will check this issue . And let you know ASAP . Thanks

Please add me on skype . I will help you 
https://join.skype.com/invite/v6Cqli3xreT9

**Comment by niendoo** [comment]
I've added you on skype please.
