### ISSUE TITLE
Tax and discount on POS invoice

### ISSUE THREAD

**Issue by haristauqir** [uilibrary/Stocky-Issues-and-Feature-request#362]
Hi, 

On POS module, system doesn't show tax and discount on the Printed invoice. 

It only lists the products and grand total. 

Why is that? As customers get confuse?

Regards,
Haris

**Comment by hamzakifani** [comment]
Hello,
We will add it in next release  this week.

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

Giving Feedback On Items
https://help.market.envato.com

**Comment by haristauqir** [comment]
It is a very basic requirement, how come system doesn't show tax and discount on POS invoice? 

That is so strange! 

Is there any way to show??

**Comment by hamzakifani** [comment]
discount and tax was already showing. but several buyers asked to hide them. but we will add a pos settings that you can show it or hide from settings area . Thank you

**Comment by haristauqir** [comment]
Okay great.

So do I expect the next release within a week?

Thanks.

**Comment by hamzakifani** [comment]
Maybe tomorrow . Thanks
