### ISSUE TITLE
When installing -setup/laststep throwing Error SQLSTATE42000: Syntax error or access violation: 

### ISSUE THREAD

**Issue by erpsolns** [uilibrary/Stocky-Issues-and-Feature-request#364]
When installing -setup/laststep throwing Error SQLSTATE42000: Syntax error or access violation: 1280 Incorrect index name ‘sales_sale_unit_id’ (SQL: alter table `sale_details` add index `sales_sale_unit_id`(`sale_unit_id`)). goes back to installation

**Comment by hamzakifani** [comment]
Please use latest release 3.6.0 . Thanks

**Comment by hamzakifani** [comment]
Fixed
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by erpsolns** [comment]
Thanks!  I can leave a positive feedback once I explore and use it.  As I
checked the database and the particular view to try to solve the problem
myself - I am keen to know what was the problem and the code or database
field or index field correction code.  That will help me to understand in
my software job.
