### ISSUE TITLE
Feature: Warranty information of product & Bug

### ISSUE THREAD

**Issue by dxblck** [uilibrary/Stocky-Issues-and-Feature-request#365]
It would be nice if the product could also have warranty information and could be included also in the receipt of POS.

The Dropdown menu in Dark mode is broken.

![image](https://user-images.githubusercontent.com/91336279/134702648-77cac70a-dbe3-40e4-9fb2-2d2154a2ecdc.png)
![image](https://user-images.githubusercontent.com/91336279/134702801-3d3a9477-f37b-4a14-9708-03e73c3c4d16.png)

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
This feature has been added in latest version
