### ISSUE TITLE
Multiple email error

### ISSUE THREAD

**Issue by ab-ashagrie** [uilibrary/Stocky-Issues-and-Feature-request#368]
Hey there Stocky team. I wanted to save multiple customers with the same email because I wanted all sales reports to be sent to the same email. But I couldn't do that as I am faced with an error saying "This email already taken" and "Failed Invalid data". I get that you put the email checker there for a reason but I want it gone in this case. Since I'm already working on Vue you can tell me which files to tweak in order to customize it.

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by ab-ashagrie** [comment]
I've already given you a kickass review. What I'm asking is not a new feature request. I'm trying to suppress that feature and all I need is for you to lead me to the file and line of code I need to comment out 🙄

**Comment by hamzakifani** [comment]
Hello , 
Please go to \app\Http\Controllers\ClientController.php 

and comment this validate .

for Create customer
![ok](https://user-images.githubusercontent.com/50219942/134789843-544a3b04-ed8a-42cd-8983-4c31359d6dbe.PNG)

and for Edit customer
![ok2](https://user-images.githubusercontent.com/50219942/134789845-c7f2f2ee-b2b1-42fe-bb5e-13967c95e98b.PNG)

and save this file
