### ISSUE TITLE
Help.. My website went completely offline!!

### ISSUE THREAD

**Issue by hificom** [uilibrary/Stocky-Issues-and-Feature-request#369]
the website / application is a complete BLANK SCREEN with the text "LOGO" at top right.

Something has happened in which I can not fix.  Need help...

Please let me know what to do ASAP!

PS: It was working just fine a few days ago.  I also looked at the database, and the ftp files, but did not see any known issues. I even tried on different browsers

Thanks for your support!

Please let me know what to do ASAP

![web_mobile](https://user-images.githubusercontent.com/85292687/134947409-59a1c200-8d62-4073-88ca-13f751b7ceff.png)

![screenshot_website_desktop](https://user-images.githubusercontent.com/85292687/134947468-2e8d69c4-d29c-44be-b743-51a59afd6781.jpg)
!

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel access

**Comment by hificom** [comment]
we sent support ticket.  We will also try to install a back up version today, if we don't hear back from you soon.

**Comment by hificom** [comment]
IT'S BEN OVER 2 DAYS.  AND WE HAVE BEEN DOWN!
