### ISSUE TITLE
Can't change the "Stocky - Ultimate Inventory With POS" in footer -> need to make dynamic and will be able to control from Admin area

### ISSUE THREAD

**Issue by ajorani92** [uilibrary/Stocky-Issues-and-Feature-request#37]
I tried following your instructions. Did not work. Still loads the footer. I even deleted the entire the code and it's still showing Stocky - Ultimate Inventory With POS.......

**Comment by naime-hossain** [comment]
Hello, Did you update resources\src\containers\layouts\common\footer.vue file ? and then compile the code ? 
via `npm run prod`

**Comment by naime-hossain** [comment]
> I tried following your instructions. Did not work. Still loads the footer. I even deleted the entire the code and it's still showing Stocky - Ultimate Inventory With POS.......

Can you please tell me , what you did step by step ? thank you

**Comment by naime-hossain** [comment]
1. Install nodejs
2. install npm
3. run `npm install` in root
4. resources\src\containers\layouts\common\footer.vue file
5. run `npm run prod`
please do these and let me know. thank you

**Comment by naime-hossain** [comment]
> 1. Install nodejs
> 2. install npm
> 3. run `npm install` in root
> 4. resources\src\containers\layouts\common\footer.vue file
> 5. run `npm run prod`
>    please do these and let me know. thank you

Hello, Did you follow the step, and what's the Update? thank you

**Comment by feesyjean** [comment]
1. I also hae this issue am using windows and i use it locally on xamp.  
2. I have edite the code using ATOM IDE and it does not show..

YOUR SUGESTION
> > 1. Install nodejs
> > 2. install npm
> > 3. run `npm install` in root
> > 4. resources\src\containers\layouts\common\footer.vue file
> > 5. run `npm run prod`
> >    please do these and let me know. thank you
> 
> Hello, Did you follow the step, and what's the Update? thank you

Are we to install this on windows as a standalone software or what please guide properly..Thank you for the support

**Comment by naime-hossain** [comment]
> 1. I also hae this issue am using windows and i use it locally on xamp.
> 2. I have edite the code using ATOM IDE and it does not show..
> 
> YOUR SUGESTION
> 
> > > 1. Install nodejs
> > > 2. install npm
> > > 3. run `npm install` in root
> > > 4. resources\src\containers\layouts\common\footer.vue file
> > > 5. run `npm run prod`
> > >    please do these and let me know. thank you
> > 
> > 
> > Hello, Did you follow the step, and what's the Update? thank you
> 
> Are we to install this on Windows as standalone software or what please guide properly.Thank you for the support
it's not a windows/mac app it's a web application. follow the installation guide, please.
and to edit code do these : 

1. Install nodejs
2. install npm
3. run npm install in root
4. resources\src\containers\layouts\common\footer.vue file
5. run npm run prod

what is your issue in xampp? did you follow the installation guide? did your PHP version meet stocky minimum requirements? read full installation guide please. thank you

**Comment by feesyjean** [comment]
I have no issue installing the script, what am saying i have deploy stocky with xamp 

and all my customization changing the footer and in adding more module to dahsboard does reflect after i refresh the page.


What i want to know is how to successfully change things on the script and it will reflect.

Thank you

**Comment by feesyjean** [comment]
Thank you for the reply,

1. will i navigate to path where is am making changes to " run npm" or anywhere in cmd ?

2. after navigating to to C:\xampp\htdocs\STOCKY\resources\src\containers\layouts\common to run " run npm" in cmd i get the below error

@ prod C:\xampp\htdocs\STOCKY
npm run production

@ production C:\xampp\htdocs\STOCKY
cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Ola Animashaun\AppData\Roaming\npm-cache_logs\2021-04-25T12_27_12_520Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: npm run production
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Ola Animashaun\AppData\Roaming\npm-cache_logs\2021-04-25T12_27_12_736Z-debug.log

**Comment by naime-hossain** [comment]
You need to run the root npm command in the root directory. Thank you
here : C:\xampp\htdocs\STOCKY

**Comment by nayeemdev** [comment]
> Thank you for the reply,
> 
> 1. will i navigate to path where is am making changes to " run npm" or anywhere in cmd ?
> 2. after navigating to to C:\xampp\htdocs\STOCKY\resources\src\containers\layouts\common to run " run npm" in cmd i get the below error
> 
> @ prod C:\xampp\htdocs\STOCKY
> npm run production
> 
> @ production C:\xampp\htdocs\STOCKY
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> 
> 'cross-env' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ production: cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @ production script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Ola Animashaun\AppData\Roaming\npm-cache_logs\2021-04-25T12_27_12_520Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ prod: npm run production
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @ prod script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Ola Animashaun\AppData\Roaming\npm-cache_logs\2021-04-25T12_27_12_736Z-debug.log

I am facing the same problem also I ran it project root
I think it can be the node and npm version issue. can you please tell the version what we need to run this
My configuration is::__
node version 12.5.0
npm version 6.9.0

**Comment by feesyjean** [comment]
You need to run npm command in the root directory.
here : C:\xampp\htdocs\YOUR_PROJECT

make sure you have  Install nodejs

1. install npm
2  npm run watch

**Comment by nayeemdev** [comment]
@feesyjean I told my node and npm version that means it installed, also I run the command in the project directory you can see the error that shows directory.

**Comment by naime-hossain** [comment]
Use latest node version

**Comment by codecahill** [comment]
I too am having issues with editing these files. I've tried running each script in the package.json and none of them have worked properly. I've installed with npm install. I tried running npm run watch after changes and I get the following error with the changes not showing up:

```
> @ watch C:\wamp64\www\inventory
> npm run development -- --watch


> @ development C:\wamp64\www\inventory
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

10% building 2/2 modules 0 active
webpack is watching the files…

92% chunk asset optimization targets-optimize-chunk-assets
<--- Last few GCs --->

[66000:000001D4D4957760]   150231 ms: Mark-sweep 2041.8 (2079.4) -> 2033.9 (2052.8) MB, 159.3 / 0.0 ms  (+ 409.2 ms in 88 steps since start of marking, biggest step 7.3 ms, walltime since start of marking 723 ms) (average mu = 0.325, current mu = 0.316) f[66000:000001D4D4957760]   150958 ms: Mark-sweep 2042.
5 (2056.2) -> 2036.9 (2055.3) MB, 308.3 / 0.0 ms  (+ 282.7 ms in 62 steps since start of marking, biggest step 6.3 ms, walltime since start of marking 696 ms) (average mu = 0.262, current mu = 0.187) a

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF64241730D]
    1: StubFrame [pc: 00007FF64239D7B1]
Security context: 0x02fd8d8408d1 <JSObject>
    2: traceMappings [000000889E73FBD1] [C:\wamp64\www\inventory\node_modules\rollup\dist\shared\node-entry.js:~10325] [pc=0000039F1991F0DD](this=0x0325ebe43791 <Link map = 0000011B1B53CF79>)
    3: collapseSourcemaps(aka collapseSourcemaps) [000001FA513B41A1] [C:\wamp64\www\inventory\no...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20210702.000729.66000.0.001.json
Node.js report completed
 1: 00007FF64180CF2F napi_wrap+112799
 2: 00007FF6417ACF26 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+55702
 3: 00007FF6417ADDB3 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+59427
 4: 00007FF641FCA27E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF641FB2351 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF641E7E8AC public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF641E89AE0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF641E86604 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF641E7BE03 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF641E7A474 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2452
11: 00007FF641E9B67D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
12: 00007FF641C013D1 public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __ptr64+1665
13: 00007FF64241730D public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
14: 00007FF64239D7B1 public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+48113
15: 0000039F1991F0DD
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jc\AppData\Roaming\npm-cache\_logs\2021-07-02T05_07_29_789Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @ watch: `npm run development -- --watch`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jc\AppData\Roaming\npm-cache\_logs\2021-07-02T05_07_29_821Z-debug.log

Process finished with exit code 134
```

**Comment by codecahill** [comment]
Node version: v12.16.2
NPM version: 6.14.8

**Comment by hamzakifani** [comment]
Hi ,
You can remove this plugin from webpack . This plugin for transcompiling final bundles so they support legacy browsers
Please watch this video
https://www.loom.com/share/5996281ca03a4380b9fa4103b5f3e9d0
.thank you
