### ISSUE TITLE
stock movements

### ISSUE THREAD

**Issue by mstfaeroglu** [uilibrary/Stocky-Issues-and-Feature-request#387]
hello, it will be very useful to see who bought that product on the product detail screen on which day. For example, when was the last time Jack bought an iPhone? I have to look at my sales to Jack one by one to see this. I ask for your help. Good luck with.

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.

**Comment by hamzakifani** [comment]
This feature has been added in latest release 4.0.1 .
**Can you please leave us a review  That will motivate our team .**
Thanks
