### ISSUE TITLE
calculation error on returned Item

### ISSUE THREAD

**Issue by generalise** [uilibrary/Stocky-Issues-and-Feature-request#388]
I have issues with the system. I returned the item and got negative on my profit instead of 0. Ex. I sold item 15,000 which I bought for 10,000. I got a profit of 5,000 I returned the goods and got -10000 on the profit which is wrong. Please can you let me know what is the problem?

**Comment by hamzakifani** [comment]
We will fix this issue ASAP . Thank you

**Comment by generalise** [comment]
How does barcode scanner work?
I don`t understand how to add it.
