### ISSUE TITLE
print sales error 

### ISSUE THREAD

**Issue by lot2021** [uilibrary/Stocky-Issues-and-Feature-request#389]
It is necessary to configure the paper size for printing and I have seen other systems without the need for configuration, they print well.

why when I try to print a sale there is no when I finish printing the paper
![IMG-20211021-WA0006](https://user-images.githubusercontent.com/87911404/138359643-157a84a3-1f69-4fdb-8c93-dd5d3c43683d.jpg)

**Comment by hamzakifani** [comment]
Will fix this issue ASAP . Thank you
