### ISSUE TITLE
filtering un paid sales dose not work 

### ISSUE THREAD

**Issue by speed-88** [uilibrary/Stocky-Issues-and-Feature-request#392]
![image](https://user-images.githubusercontent.com/51831776/138614850-ff3142ff-5c41-457c-bad0-c0520eb5ff51.png)
![image](https://user-images.githubusercontent.com/51831776/138614859-1f5179b3-f79c-4270-8ba7-99912797c102.png)
![image](https://user-images.githubusercontent.com/51831776/138614876-a8eef1f6-22f9-47d3-acdc-f5534c372d01.png)
when checking fount that unpaid sales are stored with null value for payment_statut

**Comment by hamzakifani** [comment]
This issue fixed . Thank you
