### ISSUE TITLE
Changes made to code not reflecting

### ISSUE THREAD

**Issue by feesyjean** [uilibrary/Stocky-Issues-and-Feature-request#40]
Please i made changes to the code and its not reflecting when i refresh the page.. Expecially when i change text.. Am trying to Add more modules to the side dashboard.  

Thank you

**Comment by naime-hossain** [comment]
its vue js code so in order to reflect code, you need to compile it.
1. install nodejs
2. install npm
3. edit code
4. run <pre>npm run prod</pre> or <pre>npm run watch </pre>
Thank you

**Comment by naime-hossain** [comment]
duplicate of https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues/37

**Comment by feesyjean** [comment]
> its vue js code so in order to reflect code, you need to compile it.
> 
> 1. install nodejs
> 2. install npm
> 3. edit code
> 4. run npm run prod 

or npm run watch 
>    Thank you



Thank you for the reply,

1. will i navigate to path where is am making changes to " run npm"   or anywhere in cmd ?

2. after navigating to to C:\xampp\htdocs\STOCKY\resources\src\containers\layouts\common  to run " run npm"  in cmd i get the below error

> @ prod C:\xampp\htdocs\STOCKY
> npm run production


> @ production C:\xampp\htdocs\STOCKY
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ola Animashaun\AppData\Roaming\npm-cache\_logs\2021-04-25T12_27_12_520Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ola Animashaun\AppData\Roaming\npm-cache\_logs\2021-04-25T12_27_12_736Z-debug.log

**Comment by feesyjean** [comment]
WHEN I TRY TO RUN FROM THE STOCKY ROOT FOLDER


C:\xampp\htdocs\STOCKY>npm run prod

> @ prod C:\xampp\htdocs\STOCKY
> npm run production


> @ production C:\xampp\htdocs\STOCKY
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ola Animashaun\AppData\Roaming\npm-cache\_logs\2021-04-25T12_45_54_254Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ola Animashaun\AppData\Roaming\npm-cache\_logs\2021-04-25T12_45_54_436Z-debug.log

**Comment by naime-hossain** [comment]
You need to run in root npm command in the root directory 
thank you

**Comment by feesyjean** [comment]
> You need to run in root npm command in the root directory
> here : C:\xampp\htdocs\STOCKY
> thank you

c:\xampp\htdocs\STOCKY>install nodejs
'install' is not recognized as an internal or external command,
operable program or batch file.

**Comment by feesyjean** [comment]
here show i have installed 

c:\xampp\htdocs\STOCKY>node -v
v14.16.1

c:\xampp\htdocs\STOCKY>npm -v
6.14.12

c:\xampp\htdocs\STOCKY>


but still not run prod  ????????????

**Comment by naime-hossain** [comment]
SO I think you are new to web dev, right?
install nodejs in your laptop -> https://nodejs.org/en/
then in root directory run
`npm install`
edit code
run `npm run prod`

https://www.youtube.com/watch?v=rA2zUZqOYL4

**Comment by naime-hossain** [comment]
in root run
1. `npm install`
then
2. `npm run prod`
hope this will fix your issue , thank you

**Comment by naime-hossain** [comment]
Let me know if this fixes your issue or not. thank you :)

**Comment by feesyjean** [comment]
I GOT THIS ERROR WHILE INSTALLING 

c:\xampp\htdocs\STOCKY>npm install
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\pako-e6ddc257\lib\utils\strings.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\pako-e6ddc257\lib\zlib\trees.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\popper.js-01a85cb0\src\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\popper.js-01a85cb0\dist\esm\popper-utils.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-browser\v1.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-node\v1.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-browser\v3.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-node\v3.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-browser\v35.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-node\v35.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-browser\v4.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-node\v4.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-browser\v5.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-node\v5.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-browser\validate.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-node\validate.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-browser\version.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\uuid-58a64582\dist\esm-node\version.js'
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/base/-/base-0.11.2.tgz failed, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\node-fetch-a26c9456\lib\index.mjs'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\node-forge-b2ae6d89\lib\forge.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\node-forge-b2ae6d89\lib\form.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\esm\utils\bv-event.class.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\src\utils\bv-event.class.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\src\utils\bv-event.class.spec.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\esm\utils\cache.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\src\utils\cache.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\esm\mixins\card.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\src\mixins\card.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\esm\mixins\click-out.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\src\mixins\click-out.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\src\mixins\click-out.spec.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\esm\utils\clone-deep.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\src\utils\clone-deep.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\src\utils\clone-deep.spec.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\xampp\htdocs\STOCKY\node_modules\.staging\bootstrap-vue-fa2d406e\esm\utils\config-set.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ola Animashaun\AppData\Roaming\npm-cache\_logs\2021-04-25T13_05_28_630Z-debug.log

c:\xampp\htdocs\STOCKY>


WHATS THE ISSSUE ???
THANKS FOR YOUR SUPPORT

**Comment by naime-hossain** [comment]
Remove node_modules folder if any
remove package.lock file in the root if any
then in the root run 
1. npm install
2. npm run prod
Thank you

**Comment by feesyjean** [comment]
NOT THERE

![image](https://user-images.githubusercontent.com/51484909/115994815-7b93da80-a5d0-11eb-80de-0da79e2add34.png)

**Comment by naime-hossain** [comment]
![image](https://user-images.githubusercontent.com/12586039/115994901-bdd21180-a5fa-11eb-812e-0fa25ed663bf.png)
Delete this Two i red colored 
and try 

1. `npm install`
2. `npm run prod`

**Comment by naime-hossain** [comment]
Hope this will work, and please read the installation guide too. let me know. thank you

**Comment by naime-hossain** [comment]
if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by feesyjean** [comment]
LATEST RUN GAVE THIS 



c:\xampp\htdocs\STOCKY>npm install
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ola Animashaun\AppData\Roaming\npm-cache\_logs\2021-04-25T14_04_00_417Z-debug.log

c:\xampp\htdocs\STOCKY>

**Comment by naime-hossain** [comment]
If you have node_modules folder and package-lock.json file in your root directory then remove those:
`rm -r node_modules`
`rm package-lock.json`

2 ) Then run commands:
`npm install --save --legacy-peer-deps`

**Comment by naime-hossain** [comment]
If it's not working the install yarn -> https://yarnpkg.com/getting-started/install
then in root run :
`yarn`
thank you

**Comment by feesyjean** [comment]
AND RUNING "NPM RUN PROD"


c:\xampp\htdocs\STOCKY>npm run prod

> @ prod c:\xampp\htdocs\STOCKY
> npm run production


> @ production c:\xampp\htdocs\STOCKY
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ola Animashaun\AppData\Roaming\npm-cache\_logs\2021-04-25T14_08_23_458Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ola Animashaun\AppData\Roaming\npm-cache\_logs\2021-04-25T14_08_23_858Z-debug.log

c:\xampp\htdocs\STOCKY>

**Comment by naime-hossain** [comment]
hey, did your `npm install `work?
if so then run run 
`npm install --save-dev cross-env`
then run
`npm run prod `
Thank you

**Comment by naime-hossain** [comment]
If you follow every step it should work, I just recheck with a new Stocky copy, and everything working fine.
Hope your issue is fixed. thank you

**Comment by feesyjean** [comment]
Thank you very much for all your support, you have been very patient....  
I think i will remove this installation and re-install new stocky on xampp then try all the steps again.

please can you list the steps again for confirmation please 

Thank you so much

**Comment by hamzakifani** [comment]
Try this steps:

1) npm clean cache --force
2) delete package-lock.json
3) delete nodes_modules
4) npm install -g npm

**Comment by naime-hossain** [comment]
Try these steps:

1)run : ` npm clean cache --force`
2) delete package-lock.json
3) delete nodes_modules
4)` npm install -g npm`
in root run 
5. `npm install `
edit code then 
6) `npm run watch`
7) `npm run prod`

**Comment by feesyjean** [comment]
Try these steps:

RUN IN PROJECT FOLDER OR C:/  ???
1)run : npm clean cache --force
2) delete package-lock.json
3) delete nodes_modules
4) npm install -g npm



IN STOCK ROOT FOLDER  ?
in root run
5. npm install
edit code then
6) npm run watch
7) npm run prod

**Comment by hamzakifani** [comment]
All cmd IN STOCK ROOT FOLDER

**Comment by naime-hossain** [comment]
Everything ion project root 👍 
1)run : npm clean cache --force
2) delete package-lock.json
3) delete nodes_modules
4) npm install -g npm
5. npm install
edit code then
6) npm run watch
7) npm run prod

if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by feesyjean** [comment]
Thank you very much it works now.....

I use a new Stocky installation.....

Am happy for the support.


I have a request can i get guide on how to change the menu, add more modules ?

Thank you once again Sir

**Comment by feesyjean** [comment]
Thank you very much it works now.....

I use a new Stocky installation.....

Am happy for the support.


I have a request can i get guide on how to change the menu, add more modules ?

Thank you once again Sir

**Comment by naime-hossain** [comment]
if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
> Thank you very much it works now.....
> 
> I use a new Stocky installation.....
> 
> Am happy for the support.
> 
> I have a request can i get guide on how to change the menu, add more modules ?
> 
> Thank you once again Sir

edit sidebar.vue file for change menu, for add more modules please do further study on laravel and vue or hire freelancer. 

if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
> Thank you very much it works now.....
> 
> I use a new Stocky installation.....
> 
> Am happy for the support.
> 
> I have a request can i get guide on how to change the menu, add more modules ?
> 
> Thank you once again Sir

Write a review like this in ThemeForest. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
I am closing the issue as Your issue was solved.  
https://codecanyon.net/item/stockyultimate-inventory-management-system-with-pos/reviews/31445124
if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
