### ISSUE TITLE
Sales returns and Purchases returns can return any product and change stock even if there is no sales or purchases of that product

### ISSUE THREAD

**Issue by zebhi** [uilibrary/Stocky-Issues-and-Feature-request#406]
Hi. 

When i try Stocky version 3.5 and 3.8 there are a bugs that crucial. Sales returns and Purchases returns can return any product and change stock even if there is no sales or purchases of that product. I hope you can fix this issues. Thank you.

I tried to make a sale with customer Elizabeth Nancy and make a return with a different product.

![Sales-Capture](https://user-images.githubusercontent.com/7016790/140936496-e34f7c79-1f23-43a2-b929-994def55dd8e.JPG)
![Sales-Detail-Capture](https://user-images.githubusercontent.com/7016790/140936508-d9399607-80a1-4cbc-8abd-6005b612b73f.JPG)
![Sales-Return-Capture](https://user-images.githubusercontent.com/7016790/140936472-528838c8-47f3-4537-97af-4764650fbc72.JPG)
![Sales-Return-Detail-Capture](https://user-images.githubusercontent.com/7016790/140936480-ebc3530f-5d81-4461-b18b-d8802a4b1497.JPG)

**Comment by hamzakifani** [comment]
We will fix this issue soon .thanks

**Comment by rafey022** [comment]
Is this issue is fixed or not ?

**Comment by hamzakifani** [comment]
This feature has been fixed in latest version 4.0.2 .
Thanks
