### ISSUE TITLE
FAILED TO AUTHENTICATE ON SMTP SERVER

### ISSUE THREAD

**Issue by dxblck** [uilibrary/Stocky-Issues-and-Feature-request#409]
![image](https://user-images.githubusercontent.com/91336279/141526970-73d412f2-e8ec-468b-bb27-fed933289297.png)

GMAIL:
smtp.gmail.com
465
SSL

allowed access in Google ON.

**Comment by hamzakifani** [comment]
Please test with 587 or 2525 and tls . Thanks

**Comment by dxblck** [comment]
Hello,

Still not working.

any other things i could check?

Thanks!

**Comment by hamzakifani** [comment]
We will check smtp gmail and let you know ASAP . Thanks

**Comment by dxblck** [comment]
Hello Can I get an update on this?

**Comment by dxblck** [comment]
@hamzakifani any updates on this?

**Comment by hamzakifani** [comment]
Hi , 
Contact here uilib.help@gmail.com with your app access
we will check your issue and let you know ASAP . thanks
