### ISSUE TITLE
i cannot edit Quantity

### ISSUE THREAD

**Issue by gamal22d** [uilibrary/Stocky-Issues-and-Feature-request#41]
i cannot edit Quantity please help me

**Comment by naime-hossain** [comment]
> i cannot edit Quantity please help me

where? please write in details and with screenshot. thank you

**Comment by hamzakifani** [comment]
You can add product quantity via Adjustments https://stocky.ui-lib.com/app/adjustments/store, for this, you need to purchase the product first. please add feature request here: https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues Thank you

**Comment by naime-hossain** [comment]
I am closing the issue hope you are able to add quantity. 

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
