### ISSUE TITLE
Issue on restoring backup DB

### ISSUE THREAD

**Issue by rijahary** [uilibrary/Stocky-Issues-and-Feature-request#415]
Hello support,

I've trying to restore DB after backuping that, the issue is that after restoring DB, no error appear all is seems clear but on the web interface, there is nothing appear, everything missed.

For my case, I use local server and for restoring backup I'm directly connected on my Maria DB.

So can you help or provide some patch or fix or method to resolve that and thank you in advance.

BR

**Comment by hamzakifani** [comment]
If you use the backup of other version it will be issue . 
So you need use the same backup of the same version
Or go to:  http://your-app/update 
To update your database .

**Comment by rijahary** [comment]
Hello and thank you for your return,

It seems ok for using this solution but actually we have 3 another one issue
- The code product can't be change, it stays as freeze status
- When trying to sell something, we have an issue on the product, example we put 9 as count provided on the 1 items, the 2nd one is set as 3 and automatically number 9 disappear and change automatically to another one number
If you can share whatsapp contact or another way to discuss ASAP on this issue it's better for me please
Thank you in advance 
BR

**Comment by hamzakifani** [comment]
What version are you using ??

**Comment by rijahary** [comment]
The latest version that i can download on codecanyon

I ve do install since 3 days

**Comment by hamzakifani** [comment]
Please send us a video that showing your issue . Thanks

**Comment by rijahary** [comment]
Hi Hamzakifani,

Please find in attached the video screen recorder showing the issue about de the product code issue, I can't do nothing and can generate only automatic code for product, take note that before I can set manually this case.
[BR

https://user-images.githubusercontent.com/95011384/143778896-f4543e90-6412-4327-9e9c-5721cc901945.mp4

,

**Comment by hamzakifani** [comment]
Please upgrade to latest version 3.8.0 . Thanks
