### ISSUE TITLE
Notes should appear in  details

### ISSUE THREAD

**Issue by zebhi** [uilibrary/Stocky-Issues-and-Feature-request#417]
There are notes in the create product, adjustments, sales, purchases, etc. However, this note is not shown in details.. 

This is very important, such as returning a purchased product. What is the reason for returning the product? Maybe the product is damaged, incomplete, etc. So, I can add a note about this and view this note anytime in the details.

Perhaps, You can add it in the details of all pages. Thank you.

![image](https://user-images.githubusercontent.com/7016790/143496151-6a769809-d57d-4c77-8194-453ca655b45d.png)

![image](https://user-images.githubusercontent.com/7016790/143496252-045b1518-3402-4982-ab39-6e8583ebe4b6.png)

**Comment by hamzakifani** [comment]
This feature is added in latest version 3.9.0 . Thank you
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
