### ISSUE TITLE
Need to Remove somme menu in template of Invoice pos and print sale details

### ISSUE THREAD

**Issue by tsidikana** [uilibrary/Stocky-Issues-and-Feature-request#418]
1- Please I need to  change template of invoice pos because for example I need to remove the pourcentage numbers on the invoice, ... , please where and how can I modify it please ?

2- It's same, when I need to print sale details , i need to remove something like columns  of net price , columns  of net discount, columns  of tax because it's appear in the and of invoice ? I need also to remove somme information in customer info - Invoice info , ... 

3- Can I have an whatsapp number where I can join you privatly plese ?

**Comment by hamzakifani** [comment]
your support period is expired until renewing the support we cant provide support to you.

**Comment by ph4t0o0o0om** [comment]
Hi @hamzakifani  would you please help me with this?
