### ISSUE TITLE
Barcode Scanner in Create Product

### ISSUE THREAD

**Issue by srhsfa** [uilibrary/Stocky-Issues-and-Feature-request#421]
Hi! How do I scan barcode in create product? I did not find any button or option to scan barcode.
![scan](https://user-images.githubusercontent.com/95268107/143987421-89458438-c168-4c33-9943-e6924a7085a6.png)

**Comment by hamzakifani** [comment]
If you have already products then you need scan it . Otherwise create new code .

**Comment by srhsfa** [comment]
I'm sorry I don't quite understand. I have added products, but I couldn't find the barcode scanner. Also, I have issue with searching for products in Create Adjustments, Transfer and so on. The product does not appear in the list when I search for it. How do I fix this?
![adjustment](https://user-images.githubusercontent.com/95268107/144169898-9d2c7333-2f53-4b20-a5c3-af23b895f2b0.png)

**Comment by hamzakifani** [comment]
What version are you using ??

**Comment by srhsfa** [comment]
v3.7.0

**Comment by hamzakifani** [comment]
If use v3.7.0 you need crease purchase to make adjutment or transfer . 
But you can upgrade your app to latest release 3.8.0 then you can make adjutment without purchase product . Thanks

**Comment by srhsfa** [comment]
I see. So, how do I upgrade it to the 3.8.0?

**Comment by hamzakifani** [comment]
Please follow documentation . Thanks
