### ISSUE TITLE
Picture Quality is going very low

### ISSUE THREAD

**Issue by hassanulhaque** [uilibrary/Stocky-Issues-and-Feature-request#423]
![Original Image](https://user-images.githubusercontent.com/55600767/144213276-25aef009-4755-4e32-92f9-6afe3319a845.jpeg)
![When uploaded on stocky](https://user-images.githubusercontent.com/55600767/144213303-f8eabdde-df22-43f3-832e-64ff35e635fc.PNG)
I have attached both the images above the original one and what happens when I upload them....
Please help me out it is very urgent. If possible hamza can you please share your mail id. I will share the image again if you did not get the images.

**Comment by hamzakifani** [comment]
Picture is resize to (200, 200) when storing new picture .

**Comment by hassanulhaque** [comment]
Why is the picture getting unclear, what is the solution?

**Comment by hassanulhaque** [comment]
I just want to see a clear image of the fabric, how do I achieve that?

**Comment by hamzakifani** [comment]
You need remove this resize from ProductController.

**Comment by hassanulhaque** [comment]
Okie i will try this HAMZA.
