### ISSUE TITLE
Problem in Search Box in Stocky POS page

### ISSUE THREAD

**Issue by meetisthbest** [uilibrary/Stocky-Issues-and-Feature-request#424]
Hello Dear,

Problem in Search box of POS Page, it doesn't search the products properly, (For Example, if product name is - "Tablet T350 LCD Screen". If we search "T350", then all products having this word should in that page, it doesn't search anything, unless we are doing exact name word search. We have more than 1000 products, many other will have the same, and it is very hard for a human being to remember 1000's products with exact name. This is very big problem.

![seach box  peoblem](https://user-images.githubusercontent.com/95724521/145125982-b55fc3f9-0b75-4852-95cb-fe2d220e6cd2.jpg)

![seach box  peoblem](https://user-images.githubusercontent.com/95724521/145125058-1e22be51-f136-45d3-bd35-f1a08de468c4.jpg)

**Comment by hamzakifani** [comment]
The search box search by starting word . If you have this problem we will fix this issue ASAP. Thanks

**Comment by ravenreaving** [comment]
This issue is also in adjustments search product etc. All searches should be done by keyword, not the starting word I hope they release it soon! anyways the system is very good keep up the good work guys!

**Comment by hamzakifani** [comment]
Hello guys ,
We will update stocky tomorrow , and fixing this issue . Thanks

**Comment by Bytepie** [comment]
I might be the first one to take note of this and pointed it out instantly when the search was changed to starting word only. Thanks for fixing it back.

**Comment by hamzakifani** [comment]
This issue is fixed in latest release 3.9.0 . Thank you
