### ISSUE TITLE
Modify User Role Structures

### ISSUE THREAD

**Issue by Dxwork** [uilibrary/Stocky-Issues-and-Feature-request#425]
Hello 

I just purchased Stocky software and I want to modify one particular user's role structures, see below.

1) The particular users can able view their own inventory/stock only or assigned to them in the user's portal/warehouse; the particular users can view order fulfilled, orders delivery, total sales, inventory total, inventory balance, inventory type, number of returns with real-time and date ( Admin will add that information for the user view).

2) The particular user can able to request to add/top-up inventory by entering the information into forms like ticketing to the admin/team. The particular user can able to make/add Payments to the admin/team

- once inventory deliver to the warehouse, the Admin or team add will enter receive inventory details @website/warehouse

 
3) The particular user portal account can able to sync with their account in eCommerce marketplaces, use the fetch(ing) method to fetch the orders data from eCommerce marketplaces which will contain order details. 

- Fetching data from eCommerce marketplaces will be sent to the particular user and copied to the admin, ( Admin will add that information once the order is fulfilled for the user view).

**Comment by naime-hossain** [comment]
These are Paid task, send your Budget here uilib.help@gmail.com thank you
