### ISSUE TITLE
Stocky Get Stuck at last steps

### ISSUE THREAD

**Issue by TechMR05** [uilibrary/Stocky-Issues-and-Feature-request#426]
Hello Team
Hope you are fine.
we are trying to install this app stocky everything is working. But at the last step of installation its getting stop and keep loading 
![image](https://user-images.githubusercontent.com/41509179/145642833-8cb89fba-4576-401c-ac11-77d826d6f22c.png)
I am getting this error please help what i suppose to miss or any other issue ?

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel access
