### ISSUE TITLE
Changing URL in local server.

### ISSUE THREAD

**Issue by ravenreaving** [uilibrary/Stocky-Issues-and-Feature-request#427]
Hi is there a way to change the URL from stocky.local > myname.local something like that.

**Comment by ravenreaving** [comment]
Hi i'm using xampp thank you

**Comment by hamzakifani** [comment]
Go to C:\Windows\system32\drivers\etc\ open the "hosts" file in Administrator mode.

And change stocky.local to yourname.local

Step 2 : Now go to, C:\xampp\apache\conf\extra  and open "httpd-vhosts.conf" file. 

And change stocky.local to yourname.local

Step 3 : restart xampp

**Comment by ravenreaving** [comment]
Hi, Thank you so much it worked like a charm!

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
