### ISSUE TITLE
Update vUE js

### ISSUE THREAD

**Issue by MnlLBD1** [uilibrary/Stocky-Issues-and-Feature-request#431]
hELLO, CAN YU PLEASE SPECIFY TO ME FROM WHERE CAN I UPDATE THE FRONT END CODE, I NEED TO UPDATE THE VIEW OF S SPECIFIC STOCK  TRANSFER 

THANK YOU

**Comment by hamzakifani** [comment]
Step 1 : run : npm install

Step 2 : Go to /resources/src/views/app/pages/transfers
After change the code 

Step 3: Run : npm run prod

**Comment by MnlLBD1** [comment]
this is the view we would love to update, but it just doesn't work 
<img width="1031" alt="Capture d’écran 2021-12-19 à 14 55 43" src="https://user-images.githubusercontent.com/28704686/146677421-9c75bbc4-11ff-4ea8-a35b-ed582313688a.png">

**Comment by hamzakifani** [comment]
Just follow these steps . Thanks

**Comment by MnlLBD1** [comment]
It didn't work , do you have a version with HTML AND LARAVEL ..

**Comment by hamzakifani** [comment]
No we dont have HTML CSS Version . thank you

**Comment by MnlLBD1** [comment]
Thank you , we will update the version , we have created a new page and tried to send data thru JS, please check the file and tell me if we have done it right
[resources.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/7744918/resources.zip)
