### ISSUE TITLE
how to upload images

### ISSUE THREAD

**Issue by yogam30** [uilibrary/Stocky-Issues-and-Feature-request#433]
i try to upload images but images cant upload whats the reason i conect to the database+

**Comment by hamzakifani** [comment]
Send us the error .

**Comment by hamzakifani** [comment]
check if you have phpfileinfo extension 
 available in your server  + 
"allow_url_fopen"  enabled

**Comment by yogam30** [comment]
anyother option have

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel + app access . Thank you

**Comment by hamzakifani** [comment]
This option "allow_url_fopen" is disabled.

Please enable it or contact your server to enable it .
Check this maybe help you : https://chemicloud.com/kb/article/how-to-enable-or-disable-allow_url_fopen-in-cpanel/
