### ISSUE TITLE
How to change the label

### ISSUE THREAD

**Issue by nayeem22222** [uilibrary/Stocky-Issues-and-Feature-request#434]
How to change the label. example: product name, product note etc.
https://drive.google.com/file/d/1U3GpXPlVCnsU3AUucEQgXc-H6clzfJqS/view
![download (2)](https://user-images.githubusercontent.com/57500560/146943566-ad4e7a4b-18c7-4a8f-9dc6-1fff87e23bbc.png)

**Comment by hamzakifani** [comment]
Do you know vue js ? 

Step 1: run : install npm
Step 2: Go to /resources/src/views/app/pages/products/Add_product.vue  

Step 3 :  after change your code run : npm run prod

**Comment by nayeem22222** [comment]
not working

**Comment by hamzakifani** [comment]
I think you don't know vue js . 
We will send you a video that showing how it work soon . Thanks

**Comment by nayeem22222** [comment]
I am waiting for the video. thanks

**Comment by nayeem22222** [comment]
I am waiting for the video

**Comment by hamzakifani** [comment]
Thank you for the reminder.  I totally forgot 
I will send you in few hours . Thanks

**Comment by nayeem22222** [comment]
![Screenshot (247)_LI](https://user-images.githubusercontent.com/57500560/148589862-274a144f-c035-44bb-9e43-c47d9e784a32.jpg)

**Comment by hamzakifani** [comment]
First run:

rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force

Then run the command
npm install cross-env

npm install 
and then you can also run

npm run watch

**Comment by nayeem22222** [comment]
![Screenshot (248)](https://user-images.githubusercontent.com/57500560/148591704-22f74252-eb11-400c-a2f1-9e8fe0219a5b.png)

**Comment by hamzakifani** [comment]
Please run 
npm install cross-env

**Comment by nayeem22222** [comment]
![Screenshot (249)](https://user-images.githubusercontent.com/57500560/148592770-d9cf17d0-7f2e-4707-b17d-16142f19e721.png)

**Comment by hamzakifani** [comment]
Please check this 
https://stackoverflow.com/questions/45034581/laravel-5-4-cross-env-is-not-recognized-as-an-internal-or-external-command

**Comment by hamzakifani** [comment]
1) Delete node_modules directory
2) Delete package-lock.json file
2) Run : npm cache clear --force
4) Run : npm install
5) Run : npm run watch
