### ISSUE TITLE
rename the title

### ISSUE THREAD

**Issue by viveroquispe** [uilibrary/Stocky-Issues-and-Feature-request#437]
hi how can i change title name when sharing my page always shows script name is there any way to change it please ??

**Comment by hamzakifani** [comment]
Your query not clear , send us a screenShot that descripe your issue . Thank you

**Comment by viveroquispe** [comment]
I mean how to rename the title if there is any option.
![image](https://user-images.githubusercontent.com/89100089/147392673-0ec9923f-85c8-484a-82f5-3079c5ddc93b.png)
it always shows that when I want to share my site url

**Comment by hamzakifani** [comment]
Please Go to /resources/views/layouts/master.blade.php
And change it . 

![IMG_20211225_213537](https://user-images.githubusercontent.com/50219942/147393221-6ef7f47f-a335-4adc-9963-d3b11a9eb5ec.jpg)

**Comment by viveroquispe** [comment]
![image](https://user-images.githubusercontent.com/89100089/147393500-6c818eff-312d-4c64-8eb1-46c458833c53.png)
I just changed and cleared the cache and it continues with the same

**Comment by hamzakifani** [comment]
it will be archived don't worry

**Comment by viveroquispe** [comment]
How is that archiving then you mean that it will always show those details? :(

**Comment by hamzakifani** [comment]
Please go to  /resources/views/layouts/master.blade.php and add this solution In head

    
    <meta property="og:image" content="https://www.website.com/logo.jpg">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1024">
    <meta property="og:image:height" content="1024">
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.website.com/"/>
    <meta property="og:title" content="Website title" />
    <meta property="og:description" content="Website description." />


You can make test with https://developers.facebook.com/tools/debug/

**Comment by viveroquispe** [comment]
![image](https://user-images.githubusercontent.com/89100089/147394046-96669489-3031-40f9-a2c1-f71605ce8212.png)
![image](https://user-images.githubusercontent.com/89100089/147394060-968033c1-7ba4-4123-b6fc-f7a5894f2fa6.png)

**Comment by hamzakifani** [comment]
Please go to login page. /resources/views/auth/login.blade.php  and do same solution

**Comment by viveroquispe** [comment]
thank you very much problem turned out

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
