### ISSUE TITLE
CREAT PURCHESE

### ISSUE THREAD

**Issue by yogam30** [uilibrary/Stocky-Issues-and-Feature-request#438]
I TRY TO CREATE PURCHAES 
BUT PURCHAES DOESNOT CREATE

**Comment by yogam30** [comment]
![Uploading Screenshot 2021-12-25 at 7.55.24 PM.png…]()

**Comment by hamzakifani** [comment]
ScreenShot not showing

![Uploading` Screenshot_2021-12-25-18-49-31-053_com.android.chrome.jpg…]()

**Comment by yogam30** [comment]
[image: Screenshot (3).png]
