### ISSUE TITLE
I TRY TO IMPORT PRODUCT

### ISSUE THREAD

**Issue by yogam30** [uilibrary/Stocky-Issues-and-Feature-request#439]
I TRY TO IMPORT  PRODUCT AS PER EXAMBLE STILL I GOT ERROR 
ERROR SHOW FAILED WE ALREADY FOLLOW THE INSTRUCTION

**Comment by hamzakifani** [comment]
Please watch this video
https://www.loom.com/share/3a3f99c5fa114cbea68a31c2d0fa3614

it works well if you have already created units. you can test with default csv products. but if you have a problem with the units it gives you an error on the program.
