### ISSUE TITLE
whats is no_unit in purchase edit ? 

### ISSUE THREAD

**Issue by hHossamMokhtarh** [uilibrary/Stocky-Issues-and-Feature-request#440]
What is the benefit of a no_unit in modifying the purchase process, when it is used and when it is removed?

![image](https://user-images.githubusercontent.com/31066039/147457699-fef3f1f3-11c0-46fa-910f-80d4d4638308.png)

**Comment by hamzakifani** [comment]
The unit_id not exist in the old release . so when we added it , we added new column unit_id in purchase_details
 if no_unit !==0 then unit exist already  if no_unit ===0  then unit_id not exist
