### ISSUE TITLE
Error selecting new language "Korea"

### ISSUE THREAD

**Issue by juniorhernandezg** [uilibrary/Stocky-Issues-and-Feature-request#442]
Goodnight,

Create a file called ko.js where I translated everything to Korea, compiled it in the directory C:\xampp\htdocs\crm\resources\src\translations\locales and then in /resources/src/containers/layouts/largeSidebar/TopNav. I added the code

<a @click="SetLocal('ko')">
                <i title="sa" class="flag-icon flag-icon-squared flag-icon-kr"></i>
                <span class="title-lang">South Korea</span>
              </a>
It already shows me the icon, but when I click it doesn't translate, it only shows me in English. Help me please? With the others it works less with the language that I added.

![image](https://user-images.githubusercontent.com/24769106/147515604-7bb936ca-aa30-4670-b838-bcfcb10d7f15.png)

**Comment by hamzakifani** [comment]
Hello ,
Are you imported it in 
/resources/src/translations/index.js

**Comment by juniorhernandezg** [comment]
Ready thanks. When you submit an update, will this language code change be lost?

**Comment by hamzakifani** [comment]
Yes . But if you colaborate with us and send us this file . We will add it in next update . Thanks

**Comment by juniorhernandezg** [comment]
Yes, of course. I attached it with .txt format because it won't let me .js thank you very much. When is the next update coming out?
[ko.txt](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/7786824/ko.txt)

**Comment by hamzakifani** [comment]
Withing 15-20 days . Thank you for colaborate with us .
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. Thanks

**Comment by hamzakifani** [comment]
We added korean language in latest version 3.9.0. Thanks
