### ISSUE TITLE
Employee salaries and avance

### ISSUE THREAD

**Issue by Habibci** [uilibrary/Stocky-Issues-and-Feature-request#446]
Employee salary is very important in accounting The are also kind of expenses...
Also in the middle of the month an employee might need some amount from his next coming salary 
So their must be way to type their net salary

**Comment by hamzakifani** [comment]
we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
Hello , 
Hrm module added in latest version 4.0
Thanks
