### ISSUE TITLE
There is a big problem in Stocky POS Page – Search box.

### ISSUE THREAD

**Issue by abdalghanimubarak** [uilibrary/Stocky-Issues-and-Feature-request#447]
It doesn’t search the products properly, (For Example, if product name is – “Tablet T350 LCD Screen”. If we search “T350”, then all products having this word should in that page, it doesn’t search anything, unless we are doing exact name word search. We have more than 1000 products, many other will have the same, and it is very hard for a human being to remember 1000’s products with exact name. This is very big problem

**Comment by hamzakifani** [comment]
This issue is fixed in latest version 3.9.0 . Please upgrade your app to v3.9.0. thanks

**Comment by abdalghanimubarak** [comment]
dear, its same error


‫في الأحد، 2 يناير 2022 في 6:18 م تمت كتابة ما يلي بواسطة ‪hamzakifani‬‏ <‪
***@***.***‬‏>:‬

**Comment by hamzakifani** [comment]
It's fixed . Please upgrade to latest version 3.9.0 . Thanks

**Comment by abdalghanimubarak** [comment]
i upload it but its same 3.8

**Comment by abdalghanimubarak** [comment]
<img width="335" alt="Screen Shot 2022-01-03 at 12 54 43 AM" src="https://user-images.githubusercontent.com/64291459/147891595-f612a3d7-8cee-42ee-9f2d-ee3277e4d4a4.png">

**Comment by hamzakifani** [comment]
Do you update your code or uploaded latest version from code canyon ?
We updated our code today please upload latest version from envato . Thanks

**Comment by abdalghanimubarak** [comment]
yes, i upload last version from code canyo
<img width="455" alt="Screen Shot 2022-01-03 at 12 59 05 AM" src="https://user-images.githubusercontent.com/64291459/147891675-f18bc8f8-74fc-440e-8ed8-514fa352eb7e.png">
n

**Comment by hamzakifani** [comment]
Please clear your cache from browser

**Comment by abdalghanimubarak** [comment]
i enter by incognito

**Comment by hamzakifani** [comment]
Please go to /resources/src/containers/layouts/common/footer.vue
And send me ScreenShot

**Comment by abdalghanimubarak** [comment]
<img width="729" alt="Screen Shot 2022-01-03 at 1 05 28 AM" src="https://user-images.githubusercontent.com/64291459/147891807-254b44a3-912e-4199-9c44-bfef893ed715.png">

**Comment by hamzakifani** [comment]
You are uploaded the latest release 3.9.0
Please open your app in google chrome or .. and hard clear your browser cache

**Comment by abdalghanimubarak** [comment]
ok i will do that

**Comment by hamzakifani** [comment]
You have just an issue with cache.we fixed this issue , you can test our demo . Thanks
