### ISSUE TITLE
Barcode print issue 

### ISSUE THREAD

**Issue by saiketjaman** [uilibrary/Stocky-Issues-and-Feature-request#449]
there is an issue in the barcode generate page when click the print button its not printing the barcode and showing type error in the console. Need your help plz.
![test](https://user-images.githubusercontent.com/15108281/147965327-9f622309-d024-477e-a31c-f3ebebebce69.png)

**Comment by hamzakifani** [comment]
There no issue . Please first click on "update" and click on "print ".  

![Screenshot_2022-01-04-02-12-42-269_com android chrome](https://user-images.githubusercontent.com/50219942/147996938-7b11615f-651e-4a05-8aab-3cabdb2f8425.jpg)
