### ISSUE TITLE
Warehouse assignment

### ISSUE THREAD

**Issue by Habibci** [uilibrary/Stocky-Issues-and-Feature-request#452]
Overall, Very Good, Feature-Rich and Production-Ready Software. However, I will request you to develop a very essential feature, which is the ability to assign warehouses to users. I want to assign only 1 or “few” warehouses to a particular user who only have access to the “data” and metrics of that particular warehouse with reports and dashboard syncing to the warehouse that he is assigned to.

Also, I will be happy to buy an out-of-the-box SaaS version of Stocky, so please consider it developing.

Thank you for such a good software.

**Comment by hamzakifani** [comment]
This feature already in our queue , will add it soon . Thank you
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you 


Giving Feedback On Items
https://help.market.envato.com

**Comment by cissehabib** [comment]
When?

**Comment by hamzakifani** [comment]
Hello , 
assigned warehouse to specific users  it's available now in version 4.0.  
Thanks
