### ISSUE TITLE
POS option for Balance Change 

### ISSUE THREAD

**Issue by jojogmattam** [uilibrary/Stocky-Issues-and-Feature-request#46]
When choose cash option in POS, please add the option to receive the amount and show the change to give back to customer

**Comment by hamzakifani** [comment]
Thank you for your suggestions :) we have lots of features on the queue. We will let you know when we add this feature, by the meantime, if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by hamzakifani** [comment]
Fixed
