### ISSUE TITLE
New features: customer database

### ISSUE THREAD

**Issue by cheezzi** [uilibrary/Stocky-Issues-and-Feature-request#466]
Do you do customisation for additional forms? 

I want a more detailed forms for customers database. 
My customer has multiple delivery address and I would like to record that in my system. 

On order page I would like to choose the delivery address to delivery their order. 

please quote me a customisation for such service.

**Comment by hamzakifani** [comment]
We don't provide customisation for now , very busy with other projects . but This feature in our queue , will add it soon .
