### ISSUE TITLE
Modification Guide Request

### ISSUE THREAD

**Issue by Wenykeny** [uilibrary/Stocky-Issues-and-Feature-request#470]
@hamzakifani, Hi Team

I don't know if you guys a doing it on purpose or what.

But, please be honest with people who bought your code.

Please, provide us with guide so we can changes it.

I tried to modify the code, and after:
Run the code :

npm install

I got lots of error during the npm install....

**Comment by hamzakifani** [comment]
Our code is based in laravel & vue js , 
Do you know vue js ? You need compile your code after change the code . 

Step 1 : npm install
Step 2 :  change your code ...
Step 3 : npm run prod

**Comment by femilopsy** [comment]
A detailed step-by-step will be appreciated, please.

**Comment by hamzakifani** [comment]
Hello , 

- Step 1) download & install [node js](https://nodejs.org/en/)
- Step 2) run "npm install" in your command line in the directory of the project.
- Step 3) make your  change to the sidebar file  ...
- Step 4) run "npm run watch"
- Step 5) run "npm run prod"
