### ISSUE TITLE
Code modification guide, please

### ISSUE THREAD

**Issue by femilopsy** [uilibrary/Stocky-Issues-and-Feature-request#471]
I will like to make little changes to the UI but I am not familiar with Vue.js. I tried to remove some menu from the sidebar just don’t know how to make it in the frontend.

A detailed step-by-step will be appreciated, please.

Please help.

**Comment by hamzakifani** [comment]
Hello , 

- Step 1) download & install [node js](https://nodejs.org/en/)
- Step 2) run "npm install" in your command line in the directory of the project.
- Step 3) make your  change to the sidebar file  ...
- Step 4) run "npm run watch"
- Step 5) run "npm run prod"

**Comment by femilopsy** [comment]
![image](https://user-images.githubusercontent.com/2646692/152087138-aef4f565-d21a-4273-bd03-97c5955ef505.png)

I got this error. What do I do next?

**Comment by hamzakifani** [comment]
That help you
https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh

Le mer. 2 févr. 2022 à 04:07, Femi Olaapegba ***@***.***> a
écrit :

**Comment by femilopsy** [comment]
![image](https://user-images.githubusercontent.com/2646692/152652916-8abc380b-bc16-452e-873c-751e0206f67f.png)

After several efforts. I kept getting this error when I run "npm run prod"

**Comment by hamzakifani** [comment]
step 1 : Remove node_modules directory and package-lock.json then clear the cache by using this command

npm cache clear --force

step 2 : Please extract this zip
[new_file.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/7999391/new_file.zip)

and replace the package.json & webpack.mix in root folder
![ac](https://user-images.githubusercontent.com/50219942/152681770-c8cf0a8c-fdf8-489f-a39b-36bcab031836.PNG)

and then run again : ( npm install )
Thank you
