### ISSUE TITLE
npm not install localhost

### ISSUE THREAD

**Issue by domaingood** [uilibrary/Stocky-Issues-and-Feature-request#474]
HI, I want to try install npm but npm not install localhost.

Please tell me how I can I do that. here is screenshot.

See this : http://prntscr.com/26nt1hc

**Comment by hamzakifani** [comment]
Please extract this zip
[new_file.zip](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/7999391/new_file.zip)

and replace the package.json & webpack.mix in root folder

![ac](https://user-images.githubusercontent.com/50219942/152681667-b418e96a-d8c4-4038-ad9a-15acc0d61f01.PNG)

and then run again : ( npm install )
Thank you

**Comment by domaingood** [comment]
I m getting new error like
![1](https://user-images.githubusercontent.com/30205596/152758950-02d77f17-ec2f-4093-b108-030014ea57f0.png)

**Comment by hamzakifani** [comment]
Send me an msg here https://join.skype.com/invite/v6Cqli3xreT9

**Comment by hamzakifani** [comment]
Fixed
if you like our work & support, you can leave a review that will motivate our team toward further development if possible . Thanks
