### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by aminev2** [uilibrary/Stocky-Issues-and-Feature-request#477]
when i go to https://app.yahimagsm.com/setup to setup application i got this message

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at postmaster@yahimagsm.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Apache/2.4.25 (Debian) Server at app.yahimagsm.com Port 80

**Comment by hamzakifani** [comment]
Please contact me here 
 https://join.skype.com/invite/v6Cqli3xreT9

**Comment by hamzakifani** [comment]
Fixed
