### ISSUE TITLE
Filter By Date for all reports

### ISSUE THREAD

**Issue by AntZ-Dush** [uilibrary/Stocky-Issues-and-Feature-request#48]
In all reports, we need to filter by date range not only one date.  those are the general functions please add a date range filter not one date filter

**Comment by hamzakifani** [comment]
thank you for your suggestion we will add more features in the future.
if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by naime-hossain** [comment]
We will add this feature. if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
Hello , 
This option added in latest version 4.0
Thanks
