### ISSUE TITLE
i update version 3.9.0 after product list not working properly not show full list

### ISSUE THREAD

**Issue by yogam30** [uilibrary/Stocky-Issues-and-Feature-request#481]
https://user-images.githubusercontent.com/96453599/153564967-88631b4d-23e5-4bed-b976-7e366e37c696.mp4

**Comment by hamzakifani** [comment]
Please wait withing 2-3 days , Will launch new release 4.0 . Thank you

**Comment by yogam30** [comment]
OKAY THANKS

**Comment by yogam30** [comment]
ALREADY 12 DAYS STILL MY PROBLEM NOT SOLVED

**Comment by hamzakifani** [comment]
Hello , 
we will publish new release soon that fixing some issues , have patience
if you don't need wait until new Release
Please contact me here : https://join.skype.com/invite/v6Cqli3xreT9
I will Help you .
Thank you

**Comment by hamzakifani** [comment]
This issue fixed in latest version 4.0
