### ISSUE TITLE
Add text field in product

### ISSUE THREAD

**Issue by ph4t0o0o0om** [uilibrary/Stocky-Issues-and-Feature-request#483]
Hi I want to add a new text field of product. can you tell me where is the path for the create product vue and for the insert query for database? thanks

**Comment by hamzakifani** [comment]
For frontend Go here : /resources/src/views/app/pages/products/Add_product.vue

For backend Go here : 
app/Http/Controllers/ProductsController.php

**Comment by ph4t0o0o0om** [comment]
@hamzakifani  hi thank you . now can you tell me where is the CSS file for POS vue? I want to change the CSS for list-thumb class

**Comment by hamzakifani** [comment]
/resources/src/assets/styles
