### ISSUE TITLE
Make the tax default to 12% 

### ISSUE THREAD

**Issue by ph4t0o0o0om** [uilibrary/Stocky-Issues-and-Feature-request#486]
Hi im going to make the tax default to 12% . I already add a default value and run a 'npm run watch' and 'npm run prod' but it does nothing . I tried to find the script for me to add my return value to set tax 12% to default 

this my code to add but I dont find the script 

new Vue({
<img width="329" alt="Capture" src="https://user-images.githubusercontent.com/41504668/155252860-45b70b21-0cd5-460f-b550-322eeb8320e2.PNG">

  el:"#tax",
  data() { return { sale.tax_rate: "12" } }
});

please see attached picture

**Comment by ph4t0o0o0om** [comment]
Hi I already change the default tax to 12% . now I want a checkbox that says 'NON TAX' and the default 12% will be 0 . please see attached image
<img width="250" alt="Capture" src="https://user-images.githubusercontent.com/41504668/155254865-20d261ff-cc96-4bbd-9a57-ae32c1bab9fd.PNG">

**Comment by hamzakifani** [comment]
Sory , we don't provide customization for now . 
We can help you if you have any issue. Thanks
