### ISSUE TITLE
Sale Return erorr

### ISSUE THREAD

**Issue by AntZ-Dush** [uilibrary/Stocky-Issues-and-Feature-request#49]
In the Sale Return section, we must need just select a particular return invoice number, but in your system, we have to crate return manually.  
same in the  purchase return 
and also in sale return, we must need 2 option as Usability;
1- adjust with stock
2- Wastage

**Comment by hamzakifani** [comment]
thank you for your suggestion we will add more features in the future.
if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by rafey022** [comment]
This issue is still there

**Comment by hamzakifani** [comment]
This feature has been fixed in latest version 4.0.2 .
Thanks
