### ISSUE TITLE
Find sale done by a specific POS user

### ISSUE THREAD

**Issue by srigurubyo** [uilibrary/Stocky-Issues-and-Feature-request#491]
We have multiple persons operating POS in different shifts.  I am wondering, how do we find sales done by a particular shift user (POS User). 

This is neither there in the Reports or the Sale List.

**Comment by srigurubyo** [comment]
How do I implement this?

**Comment by ph4t0o0o0om** [comment]
@hamzakifani  why you are not replying with my concern?

**Comment by hamzakifani** [comment]
> How do I implement this
You can do it if you know laravel .
By the way every sale have user_id , then you need get all sales by user_id
Sale::where('user_id' , $id_of_user)->get();

**Comment by hamzakifani** [comment]
> How do I implement this?

You can do it if you know laravel .
By the way every sale have user_id , then you need get all sales by user_id
Sale::where('user_id' , $id_of_user)->get();

**Comment by hamzakifani** [comment]
> @hamzakifani why you are not responding to my concern?

Sorry , Check now

**Comment by srigurubyo** [comment]
Can you guide me how this can be include in the existing sales report?  I just need another column where the username is displayed for each row/sale.

**Comment by naime-hossain** [comment]
you need to pay for custom work, thank you

> Can you guide me how this can be include in the existing sales report? I just need another column where the username is displayed for each row/sale.

**Comment by srigurubyo** [comment]
I am not asking you to do the work.  I am just asking you the details so that we can see if our team can implement. 

Btw, how much would you charge for this work?

**Comment by ph4t0o0o0om** [comment]
@srigurubyo hi did you find the solution for this?
