### ISSUE TITLE
What happen to the 6 months free support? 

### ISSUE THREAD

**Issue by ph4t0o0o0om** [uilibrary/Stocky-Issues-and-Feature-request#492]
No one is responding to my concern

**Comment by hamzakifani** [comment]
Hello , 
Check your issue https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues/490
Thanks

**Comment by hamzakifani** [comment]
Free support includes:
Availability of the author to answer questions
Answering technical questions about item’s features
Assistance with reported bugs and issues
Help with included 3rd party assets

Free support does not include:
Customization services
Installation services
