### ISSUE TITLE
can't download excel report in all module

### ISSUE THREAD

**Issue by ph4t0o0o0om** [uilibrary/Stocky-Issues-and-Feature-request#496]
Hi, pls see attached image for console error when trying to download excel report.
<img width="957" alt="asdasdsadsada" src="https://user-images.githubusercontent.com/41504668/159213926-78cd7fd9-bb06-4bd6-887e-e65ce5f3bf03.PNG">

**Comment by hamzakifani** [comment]
First you need buy our product to get support . Sorry

**Comment by ph4t0o0o0om** [comment]
I already purchased the product sir. pls reply on my inquiry on your discord. thank you
<img width="707" alt="Capture" src="https://user-images.githubusercontent.com/41504668/159388705-04d28a63-bd97-48c1-9f8a-ec1c9cf27868.PNG">
