### ISSUE TITLE
How can I make fields optional?

### ISSUE THREAD

**Issue by proffmkt** [uilibrary/Stocky-Issues-and-Feature-request#499]
I don't want every field to be mandatory. Example customer field for name, email, phone, address. If I want this to be optional so I can still submit the form what will be the changes I have to make?

If you can use one simple example to show me how, then I can do the rest. 

Thank you,

**Comment by ph4t0o0o0om** [comment]
Hi just go to file e.g customer.vue and change the rules to false 

From this
  <b-col md="6" sm="12">
              <validation-provider
                name="Phone Customer"
                :rules="{ required: true}"
                v-slot="validationContext"
              >
                <b-form-group :label="$t('Phone')">
                  <b-form-input
                    :state="getValidationState(validationContext)"
                    aria-describedby="Phone-feedback"
                    label="Phone"
                    v-model="client.phone"
                  ></b-form-input>
                  <b-form-invalid-feedback id="Phone-feedback">{{ validationContext.errors[0] }}</b-form-invalid-feedback>
                </b-form-group>
              </validation-provider>
            </b-col>

to this 

  <b-col md="6" sm="12">
              <validation-provider
                name="Phone Customer"
                :rules="{ required: false}"
                v-slot="validationContext"
              >
                <b-form-group :label="$t('Phone')">
                  <b-form-input
                    :state="getValidationState(validationContext)"
                    aria-describedby="Phone-feedback"
                    label="Phone"
                    v-model="client.phone"
                  ></b-form-input>
                  <b-form-invalid-feedback id="Phone-feedback">{{ validationContext.errors[0] }}</b-form-invalid-feedback>
                </b-form-group>
              </validation-provider>
            </b-col>

and go to cmd and cd to the file root and run 'npm run watch' after that run 'npm run prod' 

Im not a support I just bought the system too I see your comment on the codenayon and try to fix for you

**Comment by hamzakifani** [comment]
Hello, 
This issue fixed in stocky version 4.0 
Thank you
