### ISSUE TITLE
Decimal only accepted . and not , or both

### ISSUE THREAD

**Issue by tjaoc** [uilibrary/Stocky-Issues-and-Feature-request#5]

**Comment by naime-hossain** [comment]
It's Normal, we think,

**Comment by tjaoc** [comment]
Verify others App and you see, and not it's normal if you what sell to every countries.

**Comment by naime-hossain** [comment]
- Decimal only accepted. and not , or both
Please explain in detail what you want to have for this issue, we will try if its possible we will add this feature. thank you
