### ISSUE TITLE
Adding new page

### ISSUE THREAD

**Issue by yasirbte** [uilibrary/Stocky-Issues-and-Feature-request#502]
Hello, 

I have created a new page, I have sorted the permissions as well but the new page is not accessible. 
Can you help with this? I have created the vue, js, model, and controller files. It's on localhost, the following link gives the 404 error. 

http://inventory/app/settings/new_page

**Comment by hamzakifani** [comment]
hello , 
are you created the route in route.js ??

**Comment by hamzakifani** [comment]
Do you know vue js ?

**Comment by hamzakifani** [comment]
Please contact me here for fast support https://discord.gg/pVW9wdBuYW

**Comment by yasirbte** [comment]
Yes, I know the basics but I just need a few guidelines to include a few things regarding the variations. 

I tried to visit the link but due to security, it's not letting me sign in. Is there anything that you can help with using discord? Even I tried on the phone and it stuck on the verification screen (Mobile and Email) and an infinite loop started. 

is there any other way to get fast support?

**Comment by hamzakifani** [comment]
https://join.skype.com/invite/v6Cqli3xreT9

**Comment by yasirbte** [comment]
Thank you so Much, i have sorted to get through. 

I have created a thread: https://discord.com/channels/832126174468505600/966197391483101184/966197398516936734

I am there with the name Yasir

**Comment by hamzakifani** [comment]
Fixed
