### ISSUE TITLE
a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

### ISSUE THREAD

**Issue by theaccidentaltrader** [uilibrary/Stocky-Issues-and-Feature-request#51]
*Support for Stocky - Ultimate Inventory Management System with Pos

Hello,
I am having trouble installing this script in the cpanel.
I have other PHP Laravel / JS apps installed too in the server.
Can you help me?

**Comment by theaccidentaltrader** [comment]
after npm install ,everything is ok.

**Comment by naime-hossain** [comment]
Great Job , if you need any further help, let us know :)  if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
