### ISSUE TITLE
Feature request: Sale Return Module

### ISSUE THREAD

**Issue by ph4t0o0o0om** [uilibrary/Stocky-Issues-and-Feature-request#511]
Hi, It is usefull that we make sales return based on REFERENCE # not on the actual item itself. by means of that we lessen the hassle of typing each item and also we can execute the sales return well. Some users suggested this feature also pls consider this. 

In sales return when I type the reference in the search box example ('SL_1234') It fetches the data below about that sale transaction . 

Thanks

**Comment by hamzakifani** [comment]
This feature has been fixed in latest version 4.0.2 .
Thanks
