### ISSUE TITLE
why am i having errors in mix --production

### ISSUE THREAD

**Issue by macjayz** [uilibrary/Stocky-Issues-and-Feature-request#513]
webpack compiled with 9 errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `mix --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MACJAYZ\AppData\Roaming\npm-cache\_logs\2022-08-02T13_09_53_894Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MACJAYZ\AppData\Roaming\npm-cache\_logs\2022-08-02T13_09_54_326Z-debug.log

**Comment by hamzakifani** [comment]
remove node module folder 
the re-install node js 14 
the run again 
npm install
