### ISSUE TITLE
Unable to add Customized Pricing for Product Variants

### ISSUE THREAD

**Issue by kllwk1357** [uilibrary/Stocky-Issues-and-Feature-request#523]
We need to have the option of being able to add customized pricing for Product variants (which is not possible now in Stocky). If you do a search in the comments section for ”variants”, you will be able to see quite a number of requests for this important and useful option.

(Some examples of requests for this feature:) 
1) shakibafri shakibafri PURCHASED over 1 year ago Flag ....and what about the multi product variant custom prices?

2) nurhalim88 15 days ago Flag This product has multi variant should has ask another Product Price, because every variant should have different price. If not, the price should be same.

3) stapha PURCHASED about 2 months ago Flag Hello, I want to buy, but a feature is not complete in your system, and especially several people have asked for this several times here in the comments: -the functionality is as follows: the possibility of creating variants for a product and also the purchase and sale price for each variant, -so I won’t need to enter these prices for each variant for each transaction, especially if we have many variants, so we will enter the prices only once when the product is created.

**Comment by hamzakifani** [comment]
This feature is added in latest version 4.0.6 . 
Thanks
