### ISSUE TITLE
Invoice printing issue

### ISSUE THREAD

**Issue by N-way1** [uilibrary/Stocky-Issues-and-Feature-request#530]
Hello, when I want to print out an invoice, there is a gap between the table and the barcode which results in printing two different pages.  
How can I get it to the left?
![Screenshot 2023-01-07 134444](https://user-images.githubusercontent.com/98032882/211148976-777467b0-7c57-41a2-9e57-f709db02679c.png)

**Comment by hamzakifani** [comment]
Hi , 
We will fix this issue within 2 days . Thanks

**Comment by N-way1** [comment]
Have you fixed the issue?

**Comment by hamzakifani** [comment]
Hi , 
I am sorry , we need some time we will add more features in next release That's why we're late . 
But we can help you , 
Send your query to [support@ui-lib.com] thank you

**Comment by hamzakifani** [comment]
This issue fixed in latest version
