### ISSUE TITLE
NPM Install is taking long and Profit

### ISSUE THREAD

**Issue by ichangai** [uilibrary/Stocky-Issues-and-Feature-request#532]
Issue 1:
Kindly assist. When running Npm install, it takes way too long. It's taking more than an hour. I have a stable internet connection that I am using to stream sports. Is there something in relation to the packages being installed?

Issue 2: 
The profit calculation should include expenses. I see that you are deducting cogs (cost of goods sold) but you also need to deduct expenses. Kindly, consider this. I raised this a couple years ago, you resolved it, but somehow, you reverted to where it was. 
I would highly appreciate any response in regards to these 2 issues.

**Comment by hamzakifani** [comment]
Hi , 
Please update your app to latest version 4.0.6 .
Thanks
