### ISSUE TITLE
error in npm install ?

### ISSUE THREAD

**Issue by filaliy71** [uilibrary/Stocky-Issues-and-Feature-request#540]
I want to edit the create product form. To apply changes, I need to run `npm run watch`. However, I'm encountering an error when trying to install packages.

npm warn deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\xampp\\htdocs\\stocky\\node_modules\\node-notifier',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\xampp\htdocs\stocky\node_modules\node-notifier\vendor'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\xampp\\htdocs\\stocky\\node_modules\\node-notifier\\vendor'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\xampp\\htdocs\\stocky\\node_modules\\@johmun',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\xampp\htdocs\stocky\node_modules\@johmun\vue-tags-input\screenshots'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\xampp\\htdocs\\stocky\\node_modules\\@johmun\\vue-tags-input\\screenshots'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\xampp\htdocs\stocky\node_modules\node-sass
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm error Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\stocky\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm error gyp info it worked if it ends with ok
npm error gyp verb cli [
npm error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm error gyp verb cli   'C:\\xampp\\htdocs\\stocky\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm error gyp verb cli   'rebuild',
npm error gyp verb cli   '--verbose',
npm error gyp verb cli   '--libsass_ext=',
npm error gyp verb cli   '--libsass_cflags=',
npm error gyp verb cli   '--libsass_ldflags=',
npm error gyp verb cli   '--libsass_library='
npm error gyp verb cli ]
npm error gyp info using node-gyp@3.8.0
npm error gyp info using node@20.17.0 | win32 | x64
npm error gyp verb command rebuild []
npm error gyp verb command clean []
npm error gyp verb clean removing "build" directory
npm error gyp verb command configure []
npm error gyp verb check python checking for Python executable "python2" in the PATH
npm error gyp verb `which` failed Error: not found: python2
npm error gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\stocky\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm error gyp verb `which` failed     at F (C:\xampp\htdocs\stocky\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm error gyp verb `which` failed     at E (C:\xampp\htdocs\stocky\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm error gyp verb `which` failed     at C:\xampp\htdocs\stocky\node_modules\node-gyp\node_modules\which\which.js:89:16
npm error gyp verb `which` failed     at C:\xampp\htdocs\stocky\node_modules\isexe\index.js:42:5
npm error gyp verb `which` failed     at C:\xampp\htdocs\stocky\node_modules\isexe\windows.js:36:5
npm error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:197:21)
npm error gyp verb `which` failed  python2 Error: not found: python2
npm error gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\stocky\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm error gyp verb `which` failed     at F (C:\xampp\htdocs\stocky\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm error gyp verb `which` failed     at E (C:\xampp\htdocs\stocky\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm error gyp verb `which` failed     at C:\xampp\htdocs\stocky\node_modules\node-gyp\node_modules\which\which.js:89:16
npm error gyp verb `which` failed     at C:\xampp\htdocs\stocky\node_modules\isexe\index.js:42:5
npm error gyp verb `which` failed     at C:\xampp\htdocs\stocky\node_modules\isexe\windows.js:36:5
npm error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:197:21) {
npm error gyp verb `which` failed   code: 'ENOENT'
npm error gyp verb `which` failed }
npm error gyp verb check python checking for Python executable "python" in the PATH
npm error gyp verb `which` succeeded python C:\Users\Youssef\AppData\Local\Programs\Python\Python312\python.EXE
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: Command failed: C:\Users\Youssef\AppData\Local\Programs\Python\Python312\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm error gyp ERR! stack   File "<string>", line 1
npm error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm error gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm error gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm error gyp ERR! stack
npm error gyp ERR! stack     at genericNodeError (node:internal/errors:984:15)
npm error gyp ERR! stack     at wrappedFn (node:internal/errors:538:14)
npm error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm error gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:457:11)
npm error gyp ERR! stack     at Socket.emit (node:events:519:28)
npm error gyp ERR! stack     at Pipe.<anonymous> (node:net:339:12)
npm error gyp ERR! System Windows_NT 10.0.22631
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\stocky\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm error gyp ERR! cwd C:\xampp\htdocs\stocky\node_modules\node-sass
npm error gyp ERR! node -v v20.17.0
npm error gyp ERR! node-gyp -v v3.8.0
npm error gyp ERR! not ok
npm error Build failed with error code: 1
npm error A complete log of this run can be found in: C:\Users\Youssef\AppData\Local\npm-cache\_logs\2024-11-14T13_16_18_628Z-debug-0.log

**Comment by jafini** [comment]
dear @filaliy71 I'm facing the same problem when i try to compile it, did you get a solution?

**Comment by filaliy71** [comment]
Yes, I do. @jafini  I switched to Node.js 12, and it worked for me.

**Comment by jafini** [comment]
I have tried it almost in all versions of nodejs, but it didn't work, any
suggestion please?
