### ISSUE TITLE
NPM error.

### ISSUE THREAD

**Issue by muhaiminShihab** [uilibrary/Stocky-Issues-and-Feature-request#541]
I have to change something on the Vue files, so I executed the `npm install` and `npm run dev` commands but got errors. What is the process of working on the script? My node version is 23.5.0

**Comment by sombathoudom** [comment]
i also error on that event i downgrade npm to v18 still error

**Comment by sombathoudom** [comment]
base on this case #540  please switch to node 12 and it works for me

**Comment by muhaiminShihab** [comment]
Yup, **NPM 12** is working for me too. Thanks, @sombathoudom brother. I think @uilibrary should update their Node Module Packages. The current node version is 23 and they are using 12.
