### ISSUE TITLE
Barcode

### ISSUE THREAD

**Issue by smhkrtlms2** [uilibrary/Stocky-Issues-and-Feature-request#55]
Hi! I wrote in codecanyon but let me write from here too  :)

I have stationery.
I cannot enter a barcode when adding a product. I have to enter the barcode of products such as pens, erasers and notebooks for the point of sale.  When the system gives a barcode, I cannot make sales because the system does not have a barcode on the product.  

"naime_bh" said it will be added in the next version gave the link of this place I felt the need to write here.
When is the next version?

Thank you successes

**Comment by smhkrtlms2** [comment]
And when I change the tur.js file, the change I want does not occur on the site.

**Comment by hamzakifani** [comment]
> Hi! I wrote in codecanyon but let me write from here too :)
> 
> I have stationery.
> I cannot enter a barcode when adding a product. I have to enter the barcode of products such as pens, erasers and notebooks for the point of sale. When the system gives a barcode, I cannot make sales because the system does not have a barcode on the product.
> 
> "naime_bh" said it will be added in the next version gave the link of this place I felt the need to write here.
> When is the next version?
> 
> Thank you successes

We have a lot of features in the queue. We will add barcode scanning soon, thank you

**Comment by hamzakifani** [comment]
> And when I change the tur.js file, the change I want does not occur on the site.

But must be installed node js. and after your change

Run : 
npm install 
npm run watch 
npm run prod

**Comment by smhkrtlms2** [comment]
It would be nice if you make the site language fixed on the settings page and add it on the translation page.

**Comment by hamzakifani** [comment]
Thank you we will discuss these feature and will try to implement. If you like our item you can rete it. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Thank you

**Comment by smhkrtlms2** [comment]
I updated to new version. Code Product part is still closed to write I still can’t enter existing barcode on product creation page, system creates. I need to enter my own barcode I need to enter the existing barcode in the Code Product section on the ../app/products/store page
![Ekran Görüntüsü (15)](https://user-images.githubusercontent.com/83378803/123491905-a32f0f80-d620-11eb-8bd1-a0e6bec83aa5.jpg)

**Comment by hamzakifani** [comment]
we will add it to our queue. Thank you

**Comment by waelamad** [comment]
Is that feature added to the new updated version 3.2?

**Comment by hamzakifani** [comment]
Yes
