### ISSUE TITLE
Set Darktheme as Default Theme

### ISSUE THREAD

**Issue by neowiz0** [uilibrary/Stocky-Issues-and-Feature-request#57]
How set dark theme as standard theme?

**Comment by naime-hossain** [comment]
Edit `src/store/modules/config.js ` Like this 
const state = {
  themeMode: {
    dark: true,
    light: false,
    semi_dark: false,
    theme_color: 'lite-purple',
    layout: 'large-sidebar',
    rtl: false,
  },
};

Thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
