### ISSUE TITLE
Add Default Customer or make customer details Nullable

### ISSUE THREAD

**Issue by Bytepie** [uilibrary/Stocky-Issues-and-Feature-request#59]
Not All customers submit their information. Adding customers option at POS is useful but it requires all the fields even address, city.

Which is rather too much and the customer just want to pay and leave. He is not obliged to fulfill our Required data fields.

**Comment by hamzakifani** [comment]
thank you for this suggestion , we will discuss this issue
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by hamzakifani** [comment]
Walk in customer added . Please use the latest version 2.2.0 .thank you

**Comment by Bytepie** [comment]
Alright, thanks.  Have you also updated the online demo? I could not see the changes there and In the demo 'Required data fields' for customers are still mandatory.

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
