### ISSUE TITLE
Error Income vs Profit

### ISSUE THREAD

**Issue by tjaoc** [uilibrary/Stocky-Issues-and-Feature-request#6]
Income it's de money enter in company
Profit it's the benefice now, Sell - Costs - Expenses = Profit

<img width="1206" alt="Captura de pantalla 2021-04-06 a las 20 39 49" src="https://user-images.githubusercontent.com/6704635/113761873-3e969f80-9718-11eb-8e5a-41d29ff7df5f.png">

**Comment by naime-hossain** [comment]
=> income = payment sales + payment return purchases
=> expense = Payment Purchase + Payment Sale Returns +  expenses in warehouse
=> profit = income - expense
Updated code will upload in codecanyon soon :)
