### ISSUE TITLE
SMTP Configuration Incorrect

### ISSUE THREAD

**Issue by smhkrtlms2** [uilibrary/Stocky-Issues-and-Feature-request#60]
I get "SMTP Configuration Incorrect" warning when I enter yandex corporate mail information

The values I entered are:
host: smtp.yandex.com.tr   / ssl://smtp.yandex.com.tr / .com / .ru - - - - 
port: 465                 / 587 / 25 
username: noreply@domain.com
password: password
encryption: tls        / ssl

**Comment by hamzakifani** [comment]
It is necessary in the account settings, on Yandex (Yanex Passport):
1. fill in personal information
2. In the “Passwords and Authorization” block there is a block “Application Passwords” and the link “Create another” – create a new password there and use it in the Laravel config

**Comment by naime-hossain** [comment]
Let us know if this working or not. if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by smhkrtlms2** [comment]
This didn't work and still gives an error  :(

**Comment by naime-hossain** [comment]
Give us some time we will fix your issue , don't worry :)

**Comment by smhkrtlms2** [comment]
thank you, luck :)

**Comment by naime-hossain** [comment]
We double check and smtp is working fine. Can you try again or contact with your hosting provider. Let us know if the issue wont solve. 
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
