### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Ggustavo1003** [uilibrary/Stocky-Issues-and-Feature-request#62]
Hello, I bought your product but when all the files were transferred to the hosting when I entered with my domain, nothing happens, the following error appears I tried with other htacces but nothing happens if you help me I will thank you

**Comment by hamzakifani** [comment]
try with this htaccess 

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteBase /
    Options +FollowSymLinks
    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Send Requests To Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

**Comment by hamzakifani** [comment]
please understand that 500 is a server error and it may occur due to a range of issues. the error may not even be related to our code. 
please send your cpanel access details to doda40081@gmail.com and we’ll have a look into it.

**Comment by Ggustavo1003** [comment]
with the htacces that you send me now it comes out this way

[image: Untitled.jpg]

**Comment by Ggustavo1003** [comment]
original htacces[image: Untitled.jpg]

**Comment by Ggustavo1003** [comment]
with the htacces that you send me now it comes out this way
![Untitled](https://user-images.githubusercontent.com/52747962/116634929-72d23a00-a92b-11eb-8b31-a1df854d2220.jpg)

**Comment by Ggustavo1003** [comment]
original htacces
![Untitled](https://user-images.githubusercontent.com/52747962/116634944-7ebdfc00-a92b-11eb-9d34-9bfef9a340aa.jpg)

**Comment by hamzakifani** [comment]
are you tested your site , is working ? 
try to upload an index.html and check

**Comment by naime-hossain** [comment]
If you still have the issue then send me your: CPanel access and your Envato invoice to uilib.help@gmail.com  . we Will check. But I think you better first contact with your Hosting Provider. thank you

**Comment by Ggustavo1003** [comment]
HELLO . my hosting does not have cpanel I am using ionos web hosting

**Comment by Ggustavo1003** [comment]
I can send you the ssh or sftp access that would work for you?

**Comment by Ggustavo1003** [comment]
i talk to the web hosting  they tell me to check the .htaccess i
change the file by various methods and nothing

**Comment by naime-hossain** [comment]
@Ggustavo1003  we don't provide free installation service and it's not included in Envato policy but provide us your server info we will try to fix it if possible. lots of our buyers using stocky without having issues. thank you

**Comment by hamzakifani** [comment]
![ionos](https://user-images.githubusercontent.com/50219942/116771161-bbc3e480-aa38-11eb-9c43-77cd046d5851.PNG)

I tried to fix the problem of htaccess , is working fine now !!
But you need to create a subdomain not a manual folder, because if you don't have a subdomain all requests will be redirected to root root /.

So create a subdomain and move content of folder stocky to folder of subdomain .

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
Hope your issue is fixed now :) 

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
