### ISSUE TITLE
sticky data in dashboard 

### ISSUE THREAD

**Issue by ramijd1** [uilibrary/Stocky-Issues-and-Feature-request#64]
hello there ,, 
i have added some demo data before adding actual and real data to the script , when i delete the data everything is fine but warning data stuck in dashboard , although i have deleted related products .
https://i.imgur.com/yyQxMKR.jpg

**Comment by hamzakifani** [comment]
we will fix this issue in next update tomorrow , thank you

**Comment by naime-hossain** [comment]
Thank you for your suggestions, we will consider This. if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
