### ISSUE TITLE
I could not upload product 

### ISSUE THREAD

**Issue by gbemilekeodu** [uilibrary/Stocky-Issues-and-Feature-request#65]
Please see the screenshot attached. those 3 item doesn't allow adding of product
<img width="947" alt="Screen Shot 2021-04-30 at 10 25 10 AM" src="https://user-images.githubusercontent.com/16852117/116676588-0f81ef80-a99f-11eb-93c0-5e850e6b6a03.png">

**Comment by gbemilekeodu** [comment]
ITs a dropdown its not fillable

**Comment by naime-hossain** [comment]
Choose from the dropdown what unit do you want. Thank you
![image](https://user-images.githubusercontent.com/12586039/116680561-a1a0ec80-a9cd-11eb-9d40-f93a505c2edf.png)

**Comment by naime-hossain** [comment]
Hope You will able to add product now :) if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by gbemilekeodu** [comment]
Yes Product was added successfully thank you. One more thing  I'm still having problem  removing this (Stocky - Ultimate Inventory With POS) the product is installed online... please guide me on what to do

**Comment by naime-hossain** [comment]
You need to do this in localhost, don't worry we will add an option to remove from the admin area soon then you can upgrade the product. please support us:  if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by naime-hossain** [comment]
I am closing the issue. if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
