### ISSUE TITLE
floated RTL and dark mode menu

### ISSUE THREAD

**Issue by ramijd1** [uilibrary/Stocky-Issues-and-Feature-request#68]
hello again , about the floated menu i suggest you put those two options within the general settings and remove the floating menu , some times it causes some conflicts , and i have to choose RTL every time i refresh or open the system .
https://i.imgur.com/fiw6j0n.png

* i cant update this line from settings :
* https://i.imgur.com/cbxjXnj.png

* you didn't mention how to use messaging and when the system send it and how to control that.

**Comment by hamzakifani** [comment]
Please upgrade to Stocky v2.2 . You can update footer now .
if you want to send a mail. first put your config smtp in settings

**Comment by ramijd1** [comment]
1- i have updated to 2.2 but i cant remove " stocky - ultimate inventory with pos " .
2- what sms messages sent and when and to who ? i cant find that on documentation
3- when i change layout to RTL use float menu and refresh browser it is LTR again.

**Comment by hamzakifani** [comment]
1) you can update footer in settings
![footer](https://user-images.githubusercontent.com/50219942/117080086-aa2a5780-ad2c-11eb-8ba6-0e7deb4c49d8.PNG)

2) you find sms option in sales details & purchases details & sales return & purchases return & quotations
![sms](https://user-images.githubusercontent.com/50219942/117080230-f1b0e380-ad2c-11eb-98d2-130ef538b478.PNG)

after saving the twilio sms config .you can sent a sms to customer or provider b clicking in sms option the msg contains invoice created to inform customer or provider

3) we will check this issue , thank you

**Comment by ramijd1** [comment]
i have do the update successfully but i didn't find any new feature , nothing written in script tell the version 
i have re install the script to use new features and thats work fine for me , i guess there should be an indicator in script footer telling script current version.

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
