### ISSUE TITLE
Error use é á ó í etc

### ISSUE THREAD

**Issue by tjaoc** [uilibrary/Stocky-Issues-and-Feature-request#7]
<img width="124" alt="Captura de pantalla 2021-04-06 a las 20 42 08" src="https://user-images.githubusercontent.com/6704635/113762144-90d7c080-9718-11eb-98c3-d4cb76afcb96.png">

**Comment by naime-hossain** [comment]
What is the issue here ?

**Comment by tjaoc** [comment]
In every names or words.

**Comment by naime-hossain** [comment]
> In every names or words.

details please

**Comment by tjaoc** [comment]
Célia, José Monção bla bla bla bla

**Comment by naime-hossain** [comment]
![image](https://user-images.githubusercontent.com/12586039/114150995-7a12b300-993e-11eb-8866-e40e6858d63c.png)
we tested and its working
