### ISSUE TITLE
How can i add walk in customer?

### ISSUE THREAD

**Issue by lakmalniranga** [uilibrary/Stocky-Issues-and-Feature-request#70]
Currently, as I can see in the demo customer is required. However most of the time for POS we have walk-in customers.

Is there an option to make the customer field nullable and non-required?

**Comment by hamzakifani** [comment]
we will add walk in customer in next update . thank you

**Comment by naime-hossain** [comment]
We are working on this feature, Hopefully, will be available in the next update.  if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by ra00f** [comment]
I'm also about to ask this same question. 

I've one more request. In my locality all the customers may not have an email id. 

Would it be possible to set which all fields are mandatory/optional while adding a customer. In my locality, I'm afraid, customers may only give Name and Phone number. 

Any possibilities? 

Thanks.

**Comment by hamzakifani** [comment]
Walk in customer added . Please use the latest version 2.2.0 .thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
