### ISSUE TITLE
Is there any step by step installation guide on VPS like Vultr, DigitalOcean?

### ISSUE THREAD

**Issue by airwavesmi** [uilibrary/Stocky-Issues-and-Feature-request#72]
Hi, may I know Is there any step by step installation guide on VPS like Vultr, DigitalOcean? 

The documentation is not complete for installation guide for VPS.

Thank you.

**Comment by hamzakifani** [comment]
if you familiar with VPS Server then follow normal procedure , upload stocky file and complete setup . Thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
