### ISSUE TITLE
Application startup file // CPanel Node.js plug-in

### ISSUE THREAD

**Issue by smhkrtlms2** [uilibrary/Stocky-Issues-and-Feature-request#73]
![node](https://user-images.githubusercontent.com/83378803/117157357-35f0c200-adc7-11eb-9f4f-1799c99ffe9a.jpg)

cpanel node.js plug-in when I create an existing application, I need to transfer the files to / Stocky folder for your mainframe so that I can use run NPM run js on node.js, so if I change the file, I need not install public_html to pull data from public_html / Stocky directory. and i don't have app.js file ?

**Comment by hamzakifani** [comment]
in public /js you find main.js

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
