### ISSUE TITLE
file import is not supporting arabic characters 

### ISSUE THREAD

**Issue by ramijd1** [uilibrary/Stocky-Issues-and-Feature-request#74]
hello ,, 
i have tried to import a .csv file with products info but the file format is not supporting Arabic language characters and read it like pic below:
https://i.imgur.com/W2ui6P1.png
- to solve this issue as standard csv files cant encode Arabic language i have save the file as csv utf8 :
https://i.imgur.com/DpsU0au.png
but the system is not recognizing this file type .
i have like 600 products written in Arabic language , can you help me please with this ?

**Comment by hamzakifani** [comment]
We will check this issue . thank you

**Comment by hamzakifani** [comment]
Solution :
please edit file with **notepad ++** and save it with format **csv**  like this : 
![not](https://user-images.githubusercontent.com/50219942/117392149-00d89280-aee1-11eb-90e0-fde134342db2.PNG)

is working for me i tested it : 
![ok](https://user-images.githubusercontent.com/50219942/117392218-236aab80-aee1-11eb-83a4-2e66e022dce8.PNG)

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
