### ISSUE TITLE
npm stuck 😏 not supported lib.? 

### ISSUE THREAD

**Issue by adarshk995** [uilibrary/Stocky-Issues-and-Feature-request#76]
D:\Angular Js\my app>npm install -g @angular/cli
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see [](https://github.com/request/request/issues/3142)

added 246 packages, and audited 247 packages in 27s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
![npm error](https://user-images.githubusercontent.com/37699835/117483849-e9061a80-af83-11eb-99f4-34f6e7ad633a.png)

**Comment by naime-hossain** [comment]
why angular?

**Comment by naime-hossain** [comment]
> I am going to install npm in my custom directory, when I give the cmd 'npm install -g @angular/cli' its shows error 22 packages are looking for funding ...?

Its message from npm, not an issue, if you lots of money you can fund them. Thank you

**Comment by adarshk995** [comment]
this issue fixed #76.
closed this issue #76
