### ISSUE TITLE
No date show in invoice

### ISSUE THREAD

**Issue by AntZ-Dush** [uilibrary/Stocky-Issues-and-Feature-request#77]
We cant see the sale date in the invoice please update this. and also should need a sales list

**Comment by hamzakifani** [comment]
Thank you for your suggestions, we will consider This.

**Comment by hamzakifani** [comment]
you will find the sale date on report sales

**Comment by AntZ-Dush** [comment]
No I mean we should need the sale date in the invoice. that is a common thing. 
![Capture](https://user-images.githubusercontent.com/73590831/117561663-5a45ea80-b0b6-11eb-947d-959acba6f42f.PNG)
