### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by mustercorder** [uilibrary/Stocky-Issues-and-Feature-request#78]
Hi, there 
I'm having issues during my update.
After extracting new files i'm getting this error on site/update 

https://prnt.sc/12o3oqo

you can also check this link "https://stock.umarperfumes.com/update/lastStep"

**Comment by hamzakifani** [comment]
please follow upgrade guide in docs.  there are files you cannot replace them like .env

**Comment by naime-hossain** [comment]
Please read the doc https://stocky.ui-lib.com/documentation/index.html
Thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
