### ISSUE TITLE
Not insert item in purchase, adjusment, sales etc

### ISSUE THREAD

**Issue by hakimalfatih** [uilibrary/Stocky-Issues-and-Feature-request#80]
i'am not insert item product in form purchase, adjusment, sales etc.. so not use this app.. please help , thank you
![image](https://user-images.githubusercontent.com/15247328/117565730-04d10400-b0dd-11eb-94c4-6d3287bdb9c0.png)

from username hakim46 in codecanyon

**Comment by hamzakifani** [comment]
You can edit product quantity via Adjustments https://stocky.ui-lib.com/app/adjustments/store, for this, you need to purchase the product first. Thank you

**Comment by hakimalfatih** [comment]
item product not search on form adjusment, plaese help, thank you, i have purchase on codecanyon.

**Comment by hakimalfatih** [comment]
![image](https://user-images.githubusercontent.com/15247328/117587276-41394a00-b147-11eb-8f4f-bdccb48aaf82.png)

**Comment by hamzakifani** [comment]
Please you need create purchase via http://stocky.ui-lib.com/app/purchases/store

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
