### ISSUE TITLE
Error on add variants to product

### ISSUE THREAD

**Issue by mateoagudelo** [uilibrary/Stocky-Issues-and-Feature-request#87]
Error when entering a variant to the product.

`Uncaught (in promise) TypeError: Cannot read property 'code' of undefined
    at edit_product.js:1`

![2](https://user-images.githubusercontent.com/22106542/118191787-c6a05100-b40a-11eb-8a58-d583a666d380.png)

**Comment by hamzakifani** [comment]
i think this error because code product empty please generate new .

**Comment by hamzakifani** [comment]
Issue fixed . Thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
