### ISSUE TITLE
Change footer code but nothing happen

### ISSUE THREAD

**Issue by MmadiZaib** [uilibrary/Stocky-Issues-and-Feature-request#89]
Hello when I changed the footer.vue  I run npm install , npm run watch , npm run prod but nothing happen. Front still the same.

**Comment by hamzakifani** [comment]
Please use the latest version 2.2.0 .
you can edit footer from setting area . Thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
