### ISSUE TITLE
Error Dark Theme not see the text's

### ISSUE THREAD

**Issue by tjaoc** [uilibrary/Stocky-Issues-and-Feature-request#9]
<img width="955" alt="Captura de pantalla 2021-04-06 a las 20 48 57" src="https://user-images.githubusercontent.com/6704635/113763039-84a03300-9719-11eb-839b-84cd5dfe712f.png">

**Comment by naime-hossain** [comment]
fixed, Updated code will upload in codecanyon soon :)
