### ISSUE TITLE
Can't Update Image and after adding products it isn't showing up in POS

### ISSUE THREAD

**Issue by lalopatel0021** [uilibrary/Stocky-Issues-and-Feature-request#90]
Hi there,

I've purchased this script and I've installed it on Ubuntu VPS with Webmin/Virtualmin. setup was successful without errors. But I can't upload any Images, Avatar, Company Logo, etc.

![Screenshot (64)](https://user-images.githubusercontent.com/61663704/118370321-d794c200-b5c4-11eb-9b2b-35a8934690cb.png)

**Comment by hamzakifani** [comment]
If you are a error when you change images try to check if you are enable "Fileinfo PHP extension" ?

After adding product try to check if product has stock 

You can edit product quantity via Adjustments https://stocky.ui-lib.com/app/adjustments/store,

for this, you need to purchase the product first. Thank you

**Comment by hamzakifani** [comment]
otherwise send us a screenshot of the console when you tried to change logo

**Comment by lalopatel0021** [comment]
Yes, I've tried different images with .jpeg and .png format. but it's not working...

Fileinfo PHP extension, I've installed all as you can see in SS.

**Comment by lalopatel0021** [comment]
I've purchased it from https://codecanyon.net/ and just installed it on VPS, WebMin/VirtualMin. I've downloaded code from https://codecanyon.net/ but while installing it didn't ask me for Code. Maybe Code is in those files?

**Comment by hamzakifani** [comment]
> I've purchased it from https://codecanyon.net/ and just installed it on VPS, WebMin/VirtualMin. I've downloaded code from https://codecanyon.net/ but while installing it didn't ask me for Code. Maybe Code is in those files?

we not integrated purchase code for now . we will add it in future . thank you

**Comment by hamzakifani** [comment]
> Yes, I've tried different images with .jpeg and .png format. but it's not working...
> 
> Fileinfo PHP extension, I've installed all as you can see in SS.

you can send us the stocky url.  to see the problem .

**Comment by lalopatel0021** [comment]
The image upload issue has been resolved, I've freshly installed your new 2.3 version. Now, After adding products it won't show in Sale. When I try to create a new sale I can't see any products. Why?

**Comment by hamzakifani** [comment]
Hi. To add Sale you have to purchase the product first. Because the sales comes when you have stock.

So purchase that product first. Then you can make Sale. Thank you

create purchase via http://stocky.ui-lib.com/app/purchases/store

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
