### ISSUE TITLE
Script upload 

### ISSUE THREAD

**Issue by zaidy00** [uilibrary/Stocky-Issues-and-Feature-request#91]
hello, i hope youre doing well, so I bought stocky 2 days ago and am having some issues with uploading it online am new into web hosting so am using WINSCP i just want to know what files must be in the HTML directory because when I open my website it says “INDEX OF /”  and it lists all of my files although I uploaded the whole zipped file in the html , thank you

**Comment by hamzakifani** [comment]
please check docs and follow the setup installation http://stocky.ui-lib.com/documentation/index.html

**Comment by naime-hossain** [comment]
Hope your issue fixed , Thank you :)
