### ISSUE TITLE
Assign seller to a warehouse.

### ISSUE THREAD

**Issue by Adib128** [uilibrary/Stocky-Issues-and-Feature-request#92]
If a company has many warehouses and many sellers and evrey seller sell products for his warehouse only and he must not seeign any information about the other warehouses.

**Comment by hamzakifani** [comment]
Thank you for your suggestions, we will discuss it and if this is reliable and useful for most of the users then we will add it to our queue.
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by kashifleo55** [comment]
This is very important this should must implement asap. Thanks

**Comment by hamzakifani** [comment]
Added in latest version 4.0
