### ISSUE TITLE
any document for developers

### ISSUE THREAD

**Issue by MarcelCH** [uilibrary/Stocky-Issues-and-Feature-request#95]
any document for developers?
I want to customize the product form
Best regards
RodoldoCH

**Comment by MarcelCH** [comment]
I bought sticky too, nobody answers

**Comment by MarcelCH** [comment]
where should I ask?

**Comment by hamzakifani** [comment]
Hi ,
Stocky is based in laravel & Vue js

If you want edit the product form . 

**Frontend** :
Go to 
/resources/src/views/app/pages/products/ 

**Backend** :
Go to 
/app/Http/Controllers/ProductsController.php

After edit code Run :

npm install
npm run watch
npm run prod

We will add developer guide in future . 
Thank you



And go to

**Comment by nokoya** [comment]
# npm run watch

> watch
> npm run development -- --watch


> development
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

[webpack-cli] Error: Unknown option '--hide-modules'
[webpack-cli] Run 'webpack --help' to see available commands and options

Please advise

**Comment by naime-hossain** [comment]
did you run , npm install first ?

**Comment by nokoya** [comment]
Reinstalled 2.3
1. run setup - done
2. npm install - done
3. npm run watch - stuck in after "Laravel mx build success"

Last view
```
                                                      js/bundle/vendors~index_sales~pos.js    92.6 KiB                         vendors~index_sales~pos  [emitted]  vendors~index_sales~pos
                                                         js/bundle/vendors~largeSidebar.js    81.3 KiB                            vendors~largeSidebar  [emitted]  vendors~largeSidebar
                                                     js/bundle/vendors~largeSidebar~pos.js     313 KiB                        vendors~largeSidebar~pos  [emitted]  vendors~largeSidebar~pos
                                                js/bundle/vendors~vue-perfect-scrollbar.js    73.1 KiB                   vendors~vue-perfect-scrollbar  [emitted]  vendors~vue-perfect-scrollbar
                                                             js/bundle/warehouse_report.js    96.4 KiB                                warehouse_report  [emitted]  warehouse_report
```

**Comment by hamzakifani** [comment]
> Reinstalled 2.3
> 
> 1. run setup - done
> 2. npm install - done
> 3. npm run watch - Laravel mx build success
> 
> What next ?

run : npm run prod   
to generate the production version of your application

whenever you edit something on the folder /ressources

 you need run : 

npm install
npm run watch
npm run prod

**Comment by nokoya** [comment]
Which file should I add the css ? 

I edit resources/src/assets/styles/css/theme/*.css and npm run watch & prod doesn't work at all

**Comment by hamzakifani** [comment]
npm run watch & prod doesn't work  ?

**Comment by nokoya** [comment]
Sorry, I mean after change css on resources/src/assets/styles/css/theme/*.css and do npm run watch & prod

css didn't change at all

**Comment by hamzakifani** [comment]
No , you must change Sass  on resources/src/assets/styles/sass/globals/_globals.scss and run  npm run watch & prod

**Comment by naime-hossain** [comment]
if you need any further help, let us know :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
