### ISSUE TITLE
product arrangement problem

### ISSUE THREAD

**Issue by serdaracy** [uilibrary/Stocky-Issues-and-Feature-request#96]
hi, if a variant is attached to a product, then that product is not edited. How we can solve this problem

**Comment by hamzakifani** [comment]
we will fix this issue in next update tomorrow , thank you

**Comment by hamzakifani** [comment]
Please use the latest version 2.3.0 . Thank you

**Comment by naime-hossain** [comment]
I Hope the Latest version fixes your issue. thank you
