### ISSUE TITLE
Problem install, error : require a PHP version >= 7.3.0

### ISSUE THREAD

**Issue by tsidikana** [uilibrary/Stocky-Issues-and-Feature-request#97]
When I do install I can’t finish it because I always this problem : Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0 ».

I already install in my Cpanel , PHP version 7.4 and 7.3 , or the problem still the same allways require a PHP version ">= 7.3.0

**Comment by hamzakifani** [comment]
1) Go to cpanel -> select php version -> Current php version(change it to 7.3)

![php](https://user-images.githubusercontent.com/50219942/118527561-5448ad00-b739-11eb-82f1-f0be24a968a5.PNG)

2) clean browser cache.

**Comment by tsidikana** [comment]
Already do that bro but there is always the same error.
I already try with version 7.4 and 7.3.

![IMG_0762](https://user-images.githubusercontent.com/84341260/118532521-b90f0200-b74f-11eb-8719-26908f24b10d.JPG)

- 
![IMG_0763](https://user-images.githubusercontent.com/84341260/118532477-aeed0380-b74f-11eb-8740-5b5405bb240e.JPG)

**Comment by hamzakifani** [comment]
which domain do you install stocky ?

**Comment by tsidikana** [comment]
Web site link

www.gasyonevision.mg/gstock

Cpanel :

http://95.216.33.140:2082/
User : gasyonev
Pass : gz5i8DX.6Xe+F4

**Comment by hamzakifani** [comment]
please do not publish your info cpanel here . please delete it

**Comment by tsidikana** [comment]
My web site link is : https://www.gasyonevision.mg/gstock/

**Comment by tsidikana** [comment]
don't you have privace discuss

**Comment by hamzakifani** [comment]
> don't you have privace discuss

No this place of all request and issues alors all people show this issues

**Comment by hamzakifani** [comment]
> My web site link is : https://www.gasyonevision.mg/gstock/

Please wait i will check now

**Comment by hamzakifani** [comment]
This problem is solved bro
you installed stocky on root "gasyonevision"
as you can see you have php 7.2 on "gasyonevision"
![root](https://user-images.githubusercontent.com/50219942/118539523-6c272d80-b747-11eb-8e00-df5bd1480e82.PNG)

then you have already created a subdomain "gstock.gasyonevision.mg" and you have installed php 7.3

so I tried to install it stocky on the sub domain "gstock.gasyonevision.mg"
You can check now 

login by default : 
Email : admin@example.com
Password : 123456

you can change password for security purpose

**Comment by hamzakifani** [comment]
good news ! we will Update Stocky tomorrow with new version 2.3.0
if you need any further help, let us know :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by tsidikana** [comment]
Thank's hamzakifani, one last question please : how can we change the Logo "Stocky" to our Logo "GSTOCK"

**Comment by hamzakifani** [comment]
yes you can edit logo from area settings

![logo](https://user-images.githubusercontent.com/50219942/118541916-320b5b00-b74a-11eb-98d6-18fdc8cc7e52.PNG)

**Comment by tsidikana** [comment]
ok

**Comment by hamzakifani** [comment]
Great Job , if you need any further help, let us know :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by tsidikana** [comment]
So another one question,

Can we re-install our stocky? now if we put our php installer under the current folder, is php 7.3 is actually apply on this folder?

We need also to encrypt this subdomain.

**Comment by hamzakifani** [comment]
But you can install it in gasyonevision not in folder /gstock 
Or install it in sub doamain is great .

**Comment by tsidikana** [comment]
Hi Hamzakifani,
OK so before I do that so I set my new subdomain to php 7.3 or what exactly I must do for our issue about php compatibility?

**Comment by hamzakifani** [comment]
> Hi Hamzakifani,
> OK so before I do that so I set my new subdomain to php 7.3 or what exactly I must do for our issue about php compatibility?

Set your subdomain to php >= 7.3

**Comment by tsidikana** [comment]
Hi, http://gstock.gasyonevision.mg/login that you have create for us work well, but we have try to re-install one by all step that you have say us in order to have https://www.gasyonevision.mg/gstock but it says always as to upgrade PHP version ">= 7.3.0. please can you take command of our cpanell and re-install all in order to make https://www.gasyonevision.mg/gstock working.

We have put all instalation in /public_html/gstocky/

Do you have a private account where we can send all information for loging in our cpanell ?

**Comment by hamzakifani** [comment]
Please set  gasyonevision.mg  to php >= 7.3

**Comment by naime-hossain** [comment]
if you need any further help, let us know :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by tsidikana** [comment]
fuck

**Comment by tsidikana** [comment]
Where can we take latest version of this app, after trying do install php 7.3 is ok but the interface is not correctly load.

Can u help
