### ISSUE TITLE
I want access rest api

### ISSUE THREAD

**Issue by alifpramanarasa** [uilibrary/Stocky-Issues-and-Feature-request#98]
I trying to access rest api, but its say need javascript all the time, if there have way for accessing rest api, how ?

**Comment by hamzakifani** [comment]
we consume our API from our JavaScript application .
So if you can consume api to other app you must have a good level on laravel to understand the structure.

we use laravel passport for authentication

You need to authenticate in the API first to get the token and then send any other request using that token.

When calling routes that are protected by Passport, your application's API consumers should specify their access token as a Bearer token in the Authorization header of their request. For example, when using the Guzzle HTTP library:

![guzzle](https://user-images.githubusercontent.com/50219942/118739933-90b40000-b842-11eb-885b-b508e6b061f2.PNG)

read more : https://laravel.com/docs/8.x/passport

**Comment by alifpramanarasa** [comment]
If i want access via postman, where i can access api endpoint for auth ? I predicting i dont have the token, so i cant access the api, but i dont know how to authenticate it

**Comment by alifpramanarasa** [comment]
I have try with access code, but always unauthenticated

![image](https://user-images.githubusercontent.com/47263523/118761133-17e29180-b89e-11eb-9c3d-53d815158426.png)

**Comment by alifpramanarasa** [comment]
Specially products api, its always unauthenticate, but when im try category its work

**Comment by hamzakifani** [comment]
Hi , 
please follow these steps : 
1) Add this route in routes/api
Route::post('getAccessToken', 'AuthController@getAccessToken');

![api](https://user-images.githubusercontent.com/50219942/118822043-b75c5000-b8af-11eb-9b21-eed0e16f17ff.PNG)

2) Get Access Token via Postman

![getaccess](https://user-images.githubusercontent.com/50219942/118822178-d78c0f00-b8af-11eb-8a51-79715080c81d.PNG)

3)  send any other request using that token.

![addaccess](https://user-images.githubusercontent.com/50219942/118822679-45383b00-b8b0-11eb-8831-80bba01eabf6.PNG)

4) For Product api You need to send these params 

![params](https://user-images.githubusercontent.com/50219942/118822888-6f89f880-b8b0-11eb-86ee-281174adcb35.PNG)

5) finally 

![json](https://user-images.githubusercontent.com/50219942/118823019-8fb9b780-b8b0-11eb-85ca-32f77bac0629.PNG)

**Comment by alifpramanarasa** [comment]
Hello sir, i have follow your instruction
i have found how to access api, i can access all api except products, and i dont know why


https://user-images.githubusercontent.com/47263523/118834605-88b09a80-b8ec-11eb-900e-5ba701fdeae9.mp4

**Comment by hamzakifani** [comment]
Great , if you need any further help, let us know :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
