### ISSUE TITLE
Is there any chance to get developer guide for any single module (ex. Product Module).

### ISSUE THREAD

**Issue by dhavalpatel2374** [uilibrary/Stocky-Issues-and-Feature-request#99]
Hello, Your product is awesome. Is there any chance to get developer guide for any single module (ex. Product Module). I just want to see the road map of the single module code. or Code flow of the crud. Thank You.

**Comment by hamzakifani** [comment]
Please here you can find solution
https://github.com/uilibrary/Stocky-Issues-and-Feature-request/issues/95
Thank you .

**Comment by naime-hossain** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
